[[projections.sdn]]
= Projections

[[projections.sdn.general-remarks]]
== General remarks

As stated above, projections come in two flavors: Interface and DTO based projections.
In Spring Data Neo4j both types of projections have a direct influence which properties and relationships are transferred
over the wire.
Therefore, both approaches can reduce the load on your database in case you are dealing with nodes and entities containing
lots of properties which might not be needed in all usage scenarios in your application.

For both interface and DTO based projections, Spring Data Neo4j will use the repository's domain type for building the
query. All annotations on all attributes that might change the query will be taken in consideration.
The domain type is the type that has been defined through the repository declaration
(Given a declaration like `interface TestRepository extends CrudRepository<TestEntity, Long>` the domain type would be
`TestEntity`).

Interface based projections will always be dynamic proxies to the underlying domain type. The names of the accessors defined
on such interfaces (like `getName`) must resolve to properties (here: `name`) that are present on the projected entity.
Whether those properties have accessors or not on the domain type is not relevant, as long as they can be accessed through
the common Spring Data infrastructure. The latter is already ensured, as the domain type wouldn't be a persistent entity in
the first place.

DTO based projections are somewhat more flexible when used with custom queries. While the standard query is derived from
the original domain type and therefore only the properties and relationship beeing defined there can be used, custom queries
can add additional properties.

The rules are as follows: first, the properties of the domain type are used to populate the DTO. In case the DTO declares
additional properties - via accessors or fields - Spring Data Neo4j looks in the resulting record for matching properties.
Properties must match exactly by name and can be of simple types (as defined in `org.springframework.data.neo4j.core.convert.Neo4jSimpleTypes`)
or of known persistent entites. Collections of those are supported, but maps are not.

[[projections.sdn.full-example]]
== A full example

Given the following entities, projections and the corresponding repository:

[[projections.simple-entity]]
[source,java]
.A simple entity
----
@Node
class TestEntity {
    @Id @GeneratedValue private Long id;

    private String name;

    @Property("a_property") // <.>
    private String aProperty;
}
----
<.> This property has a different name in the Graph

[[projections.simple-entity-extended]]
[source,java]
.A derived entity, inheriting from `TestEntity`
----
@Node
class ExtendedTestEntity extends TestEntity {

    private String otherAttribute;
}
----

[[projections.simple-entity-interface-projected]]
[source,java]
.Interface projection of `TestEntity`
----
interface TestEntityInterfaceProjection {

    String getName();
}
----

[[projections.simple-entity-dto-projected]]
[source,java]
.DTO projection of `TestEntity`, including one additional attribute
----
class TestEntityDTOProjection {

    private String name;

    private Long numberOfRelations; // <.>

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getNumberOfRelations() {
        return numberOfRelations;
    }

    public void setNumberOfRelations(Long numberOfRelations) {
        this.numberOfRelations = numberOfRelations;
    }
}
----
<.> This attribute doesn't exist on the projected entity

A repository for `TestEntity` is shown below and it will behave as explained with the listing.

[[projections.simple-entity-repository]]
[source,java]
.A repository for the `TestEntity`
----
interface TestRepository extends CrudRepository<TestEntity, Long> { // <.>

    List<TestEntity> findAll(); // <.>

    List<ExtendedTestEntity> findAllExtendedEntites(); // <.>

    List<TestEntityInterfaceProjection> findAllInterfaceProjections(); // <.>

    List<TestEntityDTOProjection> findAllDTOProjections(); // <.>

    @Query("MATCH (t:TestEntity) - [r:RELATED_TO] -> () RETURN t, COUNT(r) AS numberOfRelations") // <.>
    List<TestEntityDTOProjection> findAllDTOProjectionsWithCustomQuery();
}
----
<.> The domain type of the repository is `TestEntity`
<.> Methods returning one or more `TestEntity` will just return instances of it, as it matches the domain type
<.> Methods returning one or more instances of class that extend the domain type will just return instances
    of the extending class. The domain type of the method in question will the extended class, which
    still satifies the domain type of the repository itself
<.> This method returns an interface projection, the return type of the method is therefore different
    from the repository's domain type. The interface can only access properties defined in the domain type
<.> This method returns a DTO projection. Executing it will cause SDN to issue a warning, as the DTO defines
    `numberOfRelations` as additional attribute, which is not in the contract of the domain type.
    The annotated attribute `aProperty` in `TestEntity` will be correctly translated to `a_property` in the query.
    As above, the return type is different from the repositories domain type.
<.> This method also returns a DTO projection. However, no warning will be issued, as the query contains a fitting
    value for the additional attributes defined in the projection.
