[[faq]]
= Frequently Asked Questions

Here are a couple of more frequently asked question in addition to the ones in the <<what-is-sdn-rx,preface>>.

== Neo4j 4.0 supports multiple databases - How can I use them?

You can either statically configure the database name or run your own database name provider.
Bear in mind that SDN/RX will not create the databases for you.
You can do this with the help of a https://github.com/michael-simons/neo4j-migrations[migrations tool]
or of course with a simple script upfront.

=== Statically configured

Configure the database name to use in your Spring Boot configuration like this
(The same property applies of course for YML or environment based configuration, with Spring Boots conventions applied):

[source,properties]
----
org.neo4j.data.database = yourDatabase
----

With that configuration in place, all queries generated by all instances of SDN/RX repositories (both reactive and imperative)
and by the `ReactiveNeo4jTemplate` respectively `Neo4jTemplate` will be executed against the database `yourDatabase`.

=== Dynamically configured

Provide a bean with the type `Neo4jDatabaseNameProvider` or `ReactiveDatabaseSelectionProvider` depending on the type of your Spring application.

That bean could use for example Spring's security context to retrieve a tenant.
Here is a working example for an imperative application secured with Spring Security:

[source,java]
[[faq.databaseSelectionProvider]]
.Neo4jConfig.java
----
include::../../examples/multi-database/src/main/java/org/neo4j/springframework/data/examples/spring_boot/Neo4jConfig.java[tags=faq.multidatabase]
----

NOTE: Be careful that you don't mix up entities retrieved from one database with another database.
      The database name is requested for each new transaction, so you might end up with less or more
      entities than expected when changing the database name in between calls.
      Or worse, you could inevitable store the wrong entities in the wrong database.

== Do I need to use Neo4j specific annotations?

No.
You are free to use the following, equivalent Spring Data annotations:

[cols="4*", options="header"]
|===

|SDN/RX Neo4j specific annotation
|Spring Data common annotation
|Purpose
|Difference

|`org.neo4j.springframework.data.core.schema.Id`
|`org.springframework.data.annotation.Id`
|Marks the annotated attribute as the unique id.
|Specific annotation has no additional features.

|`org.neo4j.springframework.data.core.schema.Node`
|`org.springframework.data.annotation.Persistent`
|Marks the class as persistent entity.
|`@Node` allows customizing the labels

|===

== How do I use assigned ids?

Just `@Id` without `@GeneratedValue` and fill your id attribute via a constructor parameter or a setter or _wither_.
See this https://medium.com/neo4j/neo4j-ogm-and-spring-data-neo4j-a55a866df68c[blog post] for some general remarks about finding good ids.

== How do I use externally generated ids?

We provide the interface `org.neo4j.springframework.data.core.schema.IdGenerator`.
Implement it anyway you want and configure your implementation like this:

[source,java]
.ThingWithGeneratedId.java
----
@Node
public class ThingWithGeneratedId {

	@Id @GeneratedValue(TestSequenceGenerator.class)
	private String theId;
}
----

If you pass in the name of a class to `@GeneratedValue`, this class must have a no-args default constructor.
You can however use a string as well:

[source,java]
.ThingWithIdGeneratedByBean.java
----
@Node
public class ThingWithIdGeneratedByBean {

	@Id @GeneratedValue(generatorRef = "idGeneratingBean")
	private String theId;
}
----

With that, `idGeneratingBean` refers to a bean in the Spring context.
This might be useful for sequence generating.

NOTE: Setters are not required on non-final fields for the id.

[[template-support]]
== Do I have to create repositories for each domain class?

No.
Have a look at the <<sdn-rx-building-blocks, SDN/RX building blocks>> and
find the `Neo4jTemplate` respectively the `ReactiveNeo4jTemplate.`

Those templates know your domain and provide all necessary basic CRUD methods for retrieving, writing and counting entities.

This is our canonical movie example with the imperative template:

[source,java]
[[imperative-template-example]]
.TemplateExampleTest.java
----
include::../../examples/imperative-web/src/test/java/org/neo4j/springframework/data/examples/spring_boot/TemplateExampleTest.java[tags=faq.template-imperative]
----

And here is the reactive version, omitting the setup for brevity:

[source,java]
[[reactive-template-example]]
.TemplateExampleTest.java
----
include::../../examples/reactive-web/src/test/java/org/neo4j/springframework/data/examples/spring_boot/ReactiveTemplateTest.java[tags=faq.template-reactive]
----


== How do I audit entities?

All Spring Data annotations are supported.
Those are

* `org.springframework.data.annotation.CreatedBy`
* `org.springframework.data.annotation.CreatedDate`
* `org.springframework.data.annotation.LastModifiedBy`
* `org.springframework.data.annotation.LastModifiedDate`

== How do I use "Find by example"?

"Find by example" is a new feature in SDN/RX.
You instantiate an entity or use an existing one.
With this instance you create an `org.springframework.data.domain.Example`.
If your repository extends `org.neo4j.springframework.data.repository.Neo4jRepository` or `org.neo4j.springframework.data.repository.ReactiveNeo4jRepository`,
you can immediately use the available `findBy` methods taking in an example, like shown in <<find-by-example-example>>

[source,java]
[[find-by-example-example]]
.findByExample in Action
----
Example<MovieEntity> movieExample = Example.of(new MovieEntity("The Matrix", null));
Flux<MovieEntity> movies = this.movieRepository.findAll(movieExample);

movieExample = Example.of(
	new MovieEntity("Matrix", null),
	ExampleMatcher
	    .matchingAny()
        .withMatcher(
        	"title",
        	ExampleMatcher.GenericPropertyMatcher.of(ExampleMatcher.StringMatcher.CONTAINING)
        )
);
movies = this.movieRepository.findAll(movieExample);
----

