[[new-features]]
= New & Noteworthy

[[new-features.5-1-0]]
== What's new in Spring Data Neo4j 5.1.0
* Support for SpEL expressions inside @Query annotation.
* Support for optimistic locking using an @Version field.
* Support for persistence constructors: No need for default constructors any more.
* Methods annotated with @PostLoad now longer need to be public, they can be any of package protected, private and protected, thus allowing for a better design of your Domain that encapsulates your model.
* Support the IgnoreCase flag: Derived queries can be case insensitive without resorting to regular expressions or custom queries.
* Derived queries can traverse relationships and thus support nested properties several levels deep.
* Full support for using multiple Neo4j-Server instances in one SDN-module allows you to use as many repository packages as you like using different connections and target domain packages.
* Prevent eager initialization of beans needed for repository infrastructure.
* @UseBookmark can now be used in custom, composed annotations.
* Composable repositories are now supported in a CDI context.

[[new-features.5-0-0]]
== What's new in Spring Data Neo4j 5.0.0
* SDN 5.x is designed to work with Java 8, Neo4j 3.1+, Spring 5 and Spring Boot 2.x.
* Bolt is now the default database protocol.
* For simplicity, annotations are now only supported on entity attributes, no more on accessors.
* New id management ; database ids are not mandatory anymore.
* Smarter deep querying based on domain model structure.
* Dynamic properties allow mapping in `Map` structures.
* Projections support.
* Improved causal cluster support and bookmark management.
* More flexible configuration.
* Better Java 8 support : all type queries can now return stream results and `Optional`. Better date / time management.
* Internal metadata handling has been refactored for better reliability.
* Auditing support (since 5.0.1)

When migrating from 4.x, please see the <<migration,migration guide>>.

