[[preface]]
= Preface

The Spring Data Neo4j project applies Spring Data concepts to the development of solutions using the Neo4j graph data store.
We provide _"repositories"_ as a high-level abstraction for storing and querying documents.

The next section provides some basic introduction to Spring and Graph databases.

The Spring Data Commons section then describes the common foundation of all Spring Data projects: the repositories.
_This part is taken from from SD commons project and may include examples from other persistence type such as JPA_.

The rest of the document describes the Spring Data Neo4j features and specifics.
It includes the <<reference,Spring Data Neo4j reference>>, and the <<ogm-reference-documentation,reference for Neo4j-OGM>>, on which SDN is based on.
It assumes the user is familiar with the Neo4j graph database as well as Spring concepts.

[[preface.spring-data]]
== Spring and Spring Data

Spring Data uses Spring framework's https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[core] functionality,
such as the https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#beans[IoC] container,
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#core-convert[type conversion system],
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[expression language],
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/integration.html#jmx[JMX integration],
and portable https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html#dao-exceptions[DAO exception hierarchy].
While it is not important to know the Spring APIs, understanding the concepts behind them is.
At a minimum, the idea behind IoC should be familiar for whatever IoC container you choose to use.

The core functionality of the Neo4j support can be used directly, through the Neo4j-Session.
This class corresponds to the Hibernate Session or JPA EntityManager.

To learn more about Spring, you can refer to the comprehensive documentation that explains in detail the Spring Framework.
There are a lot of articles, blog entries and books on the matter - take a look at the Spring framework http://spring.io/docs[home page ] for more information.


[[preface.nosql]]
== NoSQL and Graph databases

A graph database is a storage engine that is specialised in storing and retrieving vast networks of information.
It efficiently stores data as nodes with relationships to other or even the same nodes,
thus allowing high-performance retrieval and querying of those structures.
Properties can be added to both nodes and relationships.
Nodes can be labelled by zero or more labels, relationships are always directed and named.

Graph databases are well suited for storing most kinds of domain models.
In almost all domains, there are certain things connected to other things.
In most other modelling approaches, the relationships between things are reduced to a single link without identity and attributes.
Graph databases allow to keep the rich relationships that originate from the domain equally well-represented in the database without resorting to also modelling the relationships as "things".
There is very little "impedance mismatch" when putting real-life domains into a graph database.


[[preface.nosql.neo4j]]
=== Introducing Neo4j

http://neo4j.com/[Neo4j] is an open source NoSQL graph database.
It is a fully transactional database (ACID) that stores data structured as graphs consisting of nodes, connected by relationships.
Inspired by the structure of the real world, it allows for high query performance on complex data, while remaining intuitive and simple for the developer.

The starting point for learning about Neo4j is https://neo4j.com/[neo4j.com].
Here is a list of useful resources:

* The https://neo4j.com/docs/[Neo4j documentation] introduces Neo4j and contains links to getting started guides, reference documentation and tutorials.
* The https://neo4j.com/sandbox/[online sandbox] provides a convenient way to interact with a Neo4j instance in combination with the online https://neo4j.com/developer/get-started/[tutorial].
* Neo4j https://neo4j.com/developer/java/[Java Bolt Driver]
* Neo4j https://neo4j.com/docs/ogm-manual/current/[Neo4j Object Graph Mapper (OGM) Library]
* Several https://neo4j.com/books/[books] available for purchase and https://www.youtube.com/neo4j[videos] to watch.


[[preface.requirements]]
== Requirements

Spring Data Neo4j 5.1.x at minimum, requires:

* JDK Version 8 and above.
* Neo4j Graph Database 3.4 and above.
* Spring Framework {springVersion} and above.

If you plan on altering the version of the Neo4j-OGM make sure it is a 3.1.0+ release, fitting into the https://github.com/neo4j/neo4j-ogm/wiki/Versions[matrix of compatible versions].

[[preface.additional-resources]]
== Additional Resources

[[preface.additional-resources.metadata]]
=== Project metadata

* Version control - https://github.com/spring-projects/spring-data-neo4j
* Bugtracker - https://github.com/spring-projects/spring-data-neo4j/issues
* Release repository - https://repo.spring.io/libs-release
* Milestone repository - https://repo.spring.io/libs-milestone
* Snapshot repository - https://repo.spring.io/libs-snapshot

[[preface.additional-resources.getting-help]]
=== Getting Help & give feedback

If you encounter issues, you can use the templates for reporting issues: https://github.com/neo4j-examples/neo4j-sdn-ogm-issue-report-template.
If you are looking for advice, here are some more resources:

* The https://github.com/neo4j-examples/sdn-university[sample project: SDN University].
More example projects for Spring Data Neo4j are available in the https://github.com/neo4j-examples?query=sdn[Neo4j-Examples] repository.

* The http://projects.spring.io/spring-data-neo4j[Spring Data Neo4j project site] contains links to basic project information such as source code, JavaDocs, issue tracking, etc.
* Talk and share with the community on the https://neo4j-users.slack.com[SDN/Neo4j-OGM Slack channel]
* For more detailed questions, use http://stackoverflow.com/questions/tagged/spring-data-neo4j[Spring Data Neo4j on StackOverflow]
* For professional support feel free to contact http://www.neo4j.com[Neo4j] or http://www.graphaware.com[GraphAware].

If you are new to Spring as well as to Spring Data, look for information about https://spring.io/projects[Spring projects].

