[[preface]]
= Preface

The Spring Data Neo4J project applies core Spring concepts to the development of solutions using the Neo4j graph data store. We provide "repositories" as a high-level abstraction for storing and querying documents. You will notice similarities to the JPA/Hibernate support in the Spring Framework.

This document is the reference guide for Spring Data - Graph Support. It explains Graph module concepts and semantics and the syntax for various store namespaces.

This section provides some basic introduction to Spring and Graph databases.

The Spring Data Commons section then describes the common foundation of all Spring Data projects : the repositories.
_This part is taken from from SD commons project and may include examples from other persistence type such as JPA_.

The rest of the document describes the Spring Data Neo4j features and specifics.
It includes the <<reference,Spring Data Neo4j reference>>, and the <<ogm-reference-documentation,reference for OGM>>, on which SDN is based on.
It assumes the user is familiar with the Neo4j graph database as well as Spring concepts.

[[preface.spring-data]]
== Spring and Spring Data

Spring Data uses Spring framework's https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[core] functionality,
such as the https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#beans[IoC] container,
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#core-convert[type conversion system],
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[expression language],
https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/integration.html#jmx[JMX integration],
and portable https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html#dao-exceptions[DAO exception hierarchy].
While it is not important to know the Spring APIs, understanding the concepts behind them is.
At a minimum, the idea behind IoC should be familiar for whatever IoC container you choose to use.

The core functionality of the Neo4J support can be used directly, with no need to invoke the IoC services of the Spring Container. This is much like Hibernate `Session` or JPA `EntityManager` which can be used 'standalone' without any other services of the Spring container. To leverage all the features of Spring Data Neo4j, such as the repository support, you will need to configure some parts of the library using Spring.

To learn more about Spring, you can refer to the comprehensive (and sometimes disarming) documentation that explains in detail the Spring Framework. There are a lot of articles, blog entries and books on the matter - take a look at the Spring framework http://spring.io/docs[home page ] for more information.


[[preface.nosql]]
== NoSQL and Graph databases

A graph database is a storage engine that is specialised in storing and retrieving vast networks of information.
It efficiently stores data as nodes and relationships and allows high performance retrieval and querying of those structures.
Properties can be added to both nodes and relationships.
Nodes can be labelled by zero or more labels, relationships are always directed and named.

Graph databases are well suited for storing most kinds of domain models.
In almost all domains, there are certain things connected to other things.
In most other modelling approaches, the relationships between things are reduced to a single link without identity and attributes.
Graph databases allow to keep the rich relationships that originate from the domain equally well-represented in the database without resorting to also modelling the relationships as "things".
There is very little "impedance mismatch" when putting real-life domains into a graph database.


[[preface.nosql.neo4j]]
=== Introducing Neo4j

http://neo4j.com/[Neo4j] is an open source NOSQL graph database.
It is a fully transactional database (ACID) that stores data structured as graphs consisting of nodes, connected by relationships.
Inspired by the structure of the real world, it allows for high query performance on complex data, while remaining intuitive and simple for the developer.

Neo4j is very well-established.
It has been in commercial development for 15 years and in production for over 12 years.
Most importantly, it has an active and contributing community surrounding it, but it also:

* has an intuitive, rich graph-oriented model for data representation. Instead of tables, rows, and columns, you work with a graph consisting of http://neo4j.com/docs/stable/graphdb-neo4j.html[nodes, relationships, and properties].
* has a disk-based, native storage manager optimised for storing graph structures with maximum performance and scalability.
* is scalable. Neo4j can handle graphs with many billions of nodes/relationships/properties on a single machine, but can also be scaled out across multiple machines for high availability.
* has a powerful graph query language called Cypher, which allows users to efficiently read/write data by expressing graph patterns.
* has a powerful traversal framework and query languages for traversing the graph.
* can be deployed as a standalone server, which is the recommended way of using Neo4j
* can be deployed as an embedded (in-process) database, giving developers access to its core Java http://api.neo4j.org/[API]

In addition, Neo4j provides ACID transactions, durable persistence, concurrency control, transaction recovery, high availability, and more.
Neo4j is released under a dual free software/commercial licence model.


The jumping off ground for learning about Neo4J is https://neo4j.com/[neo4j.com]. Here is a list of other useful resources:

* The https://neo4j.com/docs/[Neo4j documentation] introduces Neo4j and contains links to getting started guides, reference documentation and tutorials.
* The https://neo4j.com/sandbox/[online sandbox] provides a convenient way to interact with a Neo4j instance in combination with the online https://neo4j.com/developer/get-started/[tutorial].
* Neo4J https://neo4j.com/developer/java/[Java Bolt Driver]
* Neo4J http://neo4j.com/docs/ogm-manual/current/[Java Object Graph Mapper (OGM) Library]
* Several https://neo4j.com/books/[books] available for purchase and https://www.youtube.com/neo4j[videos] to watch.


[[preface.requirements]]
== Requirements

Spring Data Neo4j `5.0.x` at minimum, requires:

* JDK Version `8` and above.
* Neo4j Graph Database `3.1` and above.
* Spring Framework {springVersion} and above.

If you plan on altering the version of the OGM make sure it is only in the `3.0.0+` release family.

[[preface.additional-resources]]
== Additional Resources

[[preface.additional-resources.metadata]]
=== Project metadata

* Version control - http://github.com/spring-projects/spring-data-neo4j
* Bugtracker - https://jira.spring.io/browse/DATAGRAPH
* Release repository - https://repo.spring.io/libs-release
* Milestone repository - https://repo.spring.io/libs-milestone
* Snapshot repository - https://repo.spring.io/libs-snapshot

[[preface.additional-resources.getting-help]]
=== Getting Help & give feedback

If you encounter issues or you are just looking for advice, feel free to use one of the links below:

* The https://github.com/neo4j-examples/sdn-university[sample project: SDN University].  More example projects for Spring Data Neo4j are available in the https://github.com/neo4j-examples?query=sdn[Neo4j-Examples] repository
* The main http://projects.spring.io/spring-data-neo4j[SpringSource project site] contains links to basic project information such as source code, JavaDocs, Issue tracking, etc.
* Talk and share with the community on the https://neo4j-users.slack.com[SDN/OGM Slack channel]
* For more detailed questions, use http://stackoverflow.com/questions/tagged/spring-data-neo4j-5[Spring Data Neo4j on StackOverflow]
* Use the https://github.com/neo4j-examples/neo4j-sdn-ogm-issue-report-template[templates] for reporting issues (they can also be used to bootstrap your projects).
* For professional support feel free to contact http://www.neo4j.com[Neo4j] or http://www.graphaware.com[GraphAware].

If you are new to Spring as well as to Spring Data, look for information about http://www.springsource.org/projects[Spring projects].

