== Spring Data REST Example

=== Building SDN/RX and Examples.

NOTE: You need to have JDK 11 installed.

You can either built the complete project, including the examples.
Thus, the examples will use your copy of SDN/RX, and any potential changes you made:

[source,bash]
----
git clone git@github.com:neo4j/sdn-rx
cd sdn-rx
./mvnw -DskipTests -Drevision=1.0.0 -Dchangelist=-SNAPSHOT clean package
----

If you want to only try out the examples with the currently released version,
pick out the example you like (for example the `rest` example) and build it like this:

[source,bash]
----
git clone git@github.com:neo4j/sdn-rx
cd sdn-rx/examples/rest
mvn -DskipTests clean package
cd ../..
----

=== Running the examples.

You'll need a Neo4j instance and has a user name `neo4j` with a password of `secret`.
Please use `:play movies` in Neo4j browser to get some data in your graph.
With from SDN/RX root folder run

[source,bash]
----
java -jar target/movie-rest.jar
----

If your database has different credentials or is on a different host, run

[source,bash]
----
java -jar examples/reactive-web/target/movie-api.jar \
--org.neo4j.driver.uri=neo4j://yourhost:7687 \
--org.neo4j.driver.authentication.username=youruser \
--org.neo4j.driver.authentication.password=yourpassword
----

with parameters fitting to your needs.

Here are some _curl_ commands, you can try out.
The same examples are also available in the file `movie-rest-examples.http` that you can call from IDEA.

[source,bash]
.Get a overview of all exposed REST endpoints
----
curl http://localhost:8080/
----

[source,bash]
.Get all movies
----
curl http://localhost:8080/movies
----

[source,bash]
.Get all movies with a simple projection
----
curl http://localhost:8080/movies?projection=movie-overview
----

[source,bash]
.Get all movies with a nested projection
----
curl http://localhost:8080/movies?projection=movie-details
----

[source,bash]
.Find a movie by title / derived query method
----
curl http://localhost:8080/movies/search/findOneByTitle?title=The Matrix
----

If you want to learn more about Spring Data REST,
make sure to read https://docs.spring.io/spring-data/rest/docs/current/reference/html/#reference[its reference documentation].
