= Spring Data Neo4j⚡️RX Spring Boot Starter

[abstract]
--
Provides automatic configuration for Spring Data Neo4j⚡️RX.
--

== Architectural guidelines and principles

To make a possible move into Spring Boot project itself easier,
we don't use https://projectlombok.org[Lombok] currently in the starter as none of the official Spring Boot starters does.

=== Project hierarchy and dependency management

Currently the starter project itself is a descendant of `org.springframework.data:spring-data-neo4j-rx-parent`,
mainly to take advantage of the projects build configuration (checkstyle rules and others).

We import Spring Boots BOM (`org.springframework.boot:spring-boot-dependencies`) to be consistent with Boot.
As it is the officially recommended way for starters, this is not gonna change, regardless of the parent project of the starter.

=== Responsibilities

The starter and it's automatic configuration is responsible for configuring Spring Data Neo4j RX repositories and infrastructure.
It needs a configured Neo4j Java Driver and therefor is itself dependent on `org.neo4j.driver:neo4j-java-driver-spring-boot-starter`,
the official starter for the Neo4j Java Driver.

Having the starter provide automatic configuration is in accordance with the plans for Spring Data Neo4j RX.
Spring Data Neo4j RX should only deal with configured, ready to use driver objects and not be responsible for configuring those.

== Future plans

It would be nice having this starter here moved into https://github.com/spring-projects/spring-boot[Spring Boot] itself at some point.
Regardless of that, we might suggest backporting `Neo4jDriverAutoConfiguration` alone to Spring Boot and enhance https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.java[the existing `Neo4jDataAutoConfiguration`] to check whether there's a Driver bean available
and if so, pass this one to OGM instead of creating a new driver.
That would also remove the need for being able to unwrap the native driver.
