[[reference_programming-model_attachdetach]]
= Entity Attachment

In previous versions of Spring Data Neo4j, entities could be "attached" or "detached" depending on whether or not they were enhanced by AspectJ and actively managed by the framework. 
As of SDN 4, this is no longer the case and the AspectJ involvement has completely gone away.

[[reference_programming-model_lifecycle_persistence]]
== Persisting Entities

From version 4 onwards, the entity persistence is all performed through the `save()` method on the underlying `Session` object.  
This method is normally invoked indirectly via a Spring repository or `Neo4jTemplate`.

Under the bonnet, the implementation of `Session` has access to the `MappingContext` that keeps track of the data that has been loaded from Neo4j during the lifetime of the session.  
Upon invocation of `save()` with an entity, it checks the given object graph for changes compared with the data that was loaded from the database.  
The differences are used to construct a Cypher query that persists the deltas to Neo4j before repopulating it's state based on the response from the database server.

.Persisting entities
====
[source,java]
----
@NodeEntity
public class Person {
   private String name;
   public Person(String name) {
      this.name = name;
   }
}

// Store Michael in the database.
Person p = new Person("Michael");
personRepository.save(p);
// or alternatively
neo4jTemplate.save(p);
----
====

[[reference_programming-model_detached_relating]]
== Save Depth 

As mentioned previously, `save(entity)` is overloaded as `save(entity, depth)`, where depth dictates the number of related entities to save starting from the given entity.  
A depth of 0 will persist only the properties of the specified entity to the database, and a depth of -1 will persist everything in the object graph rooted at the given entity. 

Specifying the save depth is handy when it comes to dealing with complex collections, that could potentially be very expensive to load.

[NOTE]
====
If you're using this overloaded method rather than the repositories, it's *strongly* recommended to use depth consistently between load and save invocations.  
If you don't then you may unexpectedly see relationships deleted or updates not persisting as you expect.
====

.Relationship save cascading
====
[source,java]
----
@NodeEntity
class Movie {
    String title;
    Actor topActor;
    public void setTopActor(Actor actor) {
        topActor = actor;
    }
}

@NodeEntity
class Actor {
    String name;
}

Movie movie = new Movie("Polar Express");
Actor actor = new Actor("Tom Hanks");

movie.setTopActor(actor);
----
====

Neither the actor nor the movie has been assigned a node in the graph. 
If we were to call `repository.save(movie)`, then Spring Data Neo4j would first create a node for the movie. 
It would then note that there is a relationship to an actor, so it would save the actor in a cascading fashion.  
Once the actor has been persisted, it will create the relationship from the movie to the actor. 
All of this will be done atomically in one transaction.

The important thing to note here is that if `repository.save(actor)` is called instead, then only the actor will be persisted. 
The reason for this is that the actor entity knows nothing about the movie entity - it is the movie entity that has the reference to the actor. 
Also note that this behaviour is not dependent on any configured relationship direction on the annotations. 
It is a matter of Java references and is not related to the data model in the database.

If the relationships form a cycle, then the entities will first of all be assigned a node in the database, and then the relationships will be created. 
The cascading is however only propagated to related entity fields that have been modified.

In the following example, the actor and the movie are both attached entites, having both been previously persisted to the graph: 

.Cascade for modified fields
====
[source,java]
----
actor.setBirthyear(1956);
movieRepository.save(movie);
----
====

[NOTE]
====
In this case, even though the movie has a reference to the actor, the property change on the actor will not be persisted by the call to `movie.persist()`.
The reason for this is, as mentioned above, that cascading will only be done for fields that have been modified. 
Since the `movie.topActor` field has not been modified, it will not cascade the persist operation to the actor.
====

[[reference_programming-model_sorting_and_paging]]
= Sorting and Paging
Spring Data Neo4j supports Sorting and Paging of results, both when using Spring Data's Pageable and Sort interfaces, and also when using the Session object.
The syntax for the two is slightly different, the main difference being that the Session object methods take independent arguments for Sorting and Pagination, whereas Spring's Pageable interface embeds an optional Sort object.
Behind the scenes however, Repository-based paging and sorting delegates to the core OGM equivalents.

[NOTE]
====
As of Release Candidate 1, sorting and paging is not supported on derived query methods.
====

====
.Repository-based paging
[source,java]
----
Pageable pageable = new PageRequest(0, 3);
Page<World> page = worldRepository.findAll(pageable, 0);
----

.Repository-based sorting
[source,java]
----
Sort sort = new Sort(Sort.Direction.ASC, "name");
Iterable<World> worlds = worldRepository.findAll(sort, 0)) {
----

.Repository-based sorting with paging
[source,java]
----
Pageable pageable = new PageRequest(0, 3, Sort.Direction.ASC, "name");
Page<World> page = worldRepository.findAll(pageable, 0);
----

.Core OGM-based paging
[source,java]
----
Iterable<World> worlds = loadAll(World.class, new Pagination(0,3), 0)
----

.Core OGM-based sorting
[source,java]
----
Iterable<World> worlds = loadAll(World.class, new SortOrder().add("name"), 0)
----

.Core OGM-based sorting with paging
[source,java]
----
Iterable<World> worlds = loadAll(World.class, new SortOrder().add("name"), new Pagination(0,3), 0)
----
====