[[reference_programming-model_indexing]]
= Indexing

Indexing is used in Neo4j to quickly find nodes and relationships from which to start graph operations.
Indexes are also employed to ensure uniqueness of elements with certain labels and properties.

[NOTE]
====
Please note that the lucene-based manual indexes are deprecated with Neo4j 2.0.
The default index is now based on labels and schema indexes and the related old APIs have been deprecated as well.
The "legacy" index framework should only be used for fulltext and spatial indexes which are not currently supported via schema-based indexes.
====

== Index Management in Spring Data Neo4j 4


SDN 4.2 allows developers to mark up OGM managed classes with the `@Index` annotation.

To mark a field as indexed simply add the `@Index` annotation.  If your field must be unique add `@Index(unique=true)`.  You may add as many indexes or constraints as you like to your class.  If you annotate a field in a class that is part of an inheritance hierarchy then the index or constraint will only be added to that class's label.

By default index management is set to `None`.

Once you have annotated your classes you then have various Auto Indexing Options.  SDN will try to configure the the auto indexer from the `ogm.properties` file, which it expects to find on the classpath or via Spring through a `Configuration` bean.

The following sections describe how to setup Spring Data Neo4j using both techniques.


.ogm.properties

```
indexes.auto=assert
```


.Java Configuration

To configure the Driver programmatically, create a Configuration bean and pass it as the first argument to the SessionFactory constructor in your Spring configuration:

[source,java]
----

@Bean
public Configuration configuration() {
   Configuration config = new Configuration();
   config
       .autoIndexConfiguration()
       .setAutoIndex("assert");
   return config;
}

@Bean
public SessionFactory sessionFactory() {
    return new SessionFactory(configuration(), <packages> );
}
----

Below is a table of all options available for configuring Auto-Indexing.

|===
|Option|Description|Properties Example|Java Example

| *none (default)*
| Nothing is done with index and constraint annotations.
| -
| -

| *validate*
| Make sure the connected database has all indexes and constraints in place before starting up
| indexes.auto=validate
| config.autoIndexConfiguration().setAutoIndex("validate");

| *assert*
| Drops all constraints and indexes on startup then builds indexes based on whatever is represented in OGM by `@Index`. Handy during development
| indexes.auto=assert
| config.autoIndexConfiguration().setAutoIndex("assert");

| *dump*
| Dumps the generated constraints and indexes to a file. Good for setting up environments. none: Default. Simply marks the field as using an index.
| indexes.auto=dump
  indexes.auto.dump.dir=<a directory>
  indexes.auto.dump.filename=<a filename>
| config.autoIndexConfiguration().setAutoIndex("dump");
  config.autoIndexConfiguration().setDumpDir("XXX");
  config.autoIndexConfiguration().setDumpFilename("XXX");

|===



== Index queries in Repositories

Schema indexes are automatically used by Neo4j's Cypher engine, so using the annotated or derived repository finders will use them out of the box.

== Legacy Neo4j Auto Indexes

Neo4j allows to configure (legacy) http://neo4j.com/docs/stable/auto-indexing.html[auto-indexing] for certain properties on nodes and relationships.
It is possible to use the specific index names `node_auto_index` and `relationship_auto_index` when querying indexes in Spring Data Neo4j either with the query methods in template and repositories or via Cypher.

== Full-Text Indexes

Previous versions of Spring Data Neo4j offered support for full-text queries using the manual index facilities.
However, as of SDN 4, this is no longer supported.

To create fulltext entries for an entity you can add the updated nodes within `AfterSaveEvents` to a remote fulltext-index via Neo4j's REST API.
If you use Http Driver and the `HttpRequest` used by the OGM, then authentication will be taken care of as well.

[NOTE]
====
These methods work only with the HTTP and Embedded drivers. The Bolt driver does not support updates to legacy indexes.
If any of the methods below are employed, the user is responsible for managing resources such as the underlying GraphDatabaseService if the Driver used to get hold of the underlying implementation.
====

.Indexing Persons upon persistence with the HTTP Driver
[source,java]
----
final CloseableHttpClient httpClient = HttpClients.createDefault();

@Bean
ApplicationListener<AfterSaveEvent> afterSaveEventApplicationListener() {
    return new ApplicationListener<AfterSaveEvent>() {
        @Override
        public void onApplicationEvent(AfterSaveEvent event) {
            if(event.getEntity() instanceof Person) {
                String uri = Components.driver().getConfiguration().getURI() +
                            "/db/data/index/node/" + indexName;
                HttpPost httpPost = new HttpPost(uri);
                Person person = (Person) event.getEntity();
                //Construct the JSON statements
                try {
                    httpPost.setEntity(new StringEntity(json.toString()));
                    HttpRequest.execute(httpClient, httpPost,
                                        Components.driver().getConfiguration().getCredentials());
                } catch (Exception e) {
                    //Handle any exceptions
                }
            }
        }
    };
}
----

.Indexing Persons upon persistence with the Embedded Driver
[source,java]
----

@Bean
ApplicationListener<AfterSaveEvent> afterSaveEventApplicationListener() {
    return new ApplicationListener<AfterSaveEvent>() {
        @Override
        public void onApplicationEvent(AfterSaveEvent event) {

            if(event.getEntity() instanceof Person) {
                EmbeddedDriver embeddedDriver = (EmbeddedDriver) Components.driver();
                GraphDatabaseService databaseService = embeddedDriver.getGraphDatabaseService();
                Person person = (Person) event.getEntity();
                try (Transaction tx = databaseService.beginTx()) {
                    Node node = databaseService.getNodeById(person.getNodeId());
                    databaseService.index().forNodes(indexName).add(node, key, value);
                    tx.success();
                }
            }
        }
    };
}
----

Fulltext query support is still available via Cypher queries which can be executed via the `Session`, or as a `@Query` defined in a repository class.

== Spatial Indexes

Previous versions of Spring Data Neo4j offered support for spatial queries using the `neo4j-spatial` library.
However, as of SDN 4 at least, this is no longer supported.

A strategy similar to the full-text indexes being updated within `AfterSaveEvents` can be employed to support Spatial Indexes.
The http://neo4j-contrib.github.io/spatial/#spatial-server-plugin[Neo4j Spatial Plugin] exposes a REST API to interact with the library.

