[[reference_programming-model_mapping]]
= Under the hood

== Metadata collection
Metadata is collected about persistent entities in `org.neo4j.ogm.metadata.Metadata` which provides it to any part of the library.
This information is gathered by reading the class files directly rather than loading via reflection, resulting in much faster startup times.

The metadata holds all the required object-graph mapping information for each type.
This metadata is discovered at start-up by specifying a list of packages in which all classes are scanned, including those in sub-packages.
In order to omit a class from being metadata-mapped you should annotate it with `@org.neo4j.ogm.annotation.Transient`.

== The Session object
The Spring repositories and `Neo4jTemplate` are both backed by `org.neo4j.ogm.session.Session`, which is a key component of the framework.  
The Session provides methods to load, save or delete object graphs from the database and also provides transaction support.  
The new `Neo4jTemplate` is essentially a wrapper around this `Session`, which exposes all of its useful methods but handles transactions and provides the traditional Spring Data operations and exception translation.

== Explicit save
Unlike the previous AspectJ-driven mapping, Spring Data Neo4j 4 doesn't automatically commit when a transaction closes, so an explicit call to `save(...)` is required in order to persist changes to the database.

== Fine-grained control via depth specification
The new object mapping framework in Spring Data Neo4j introduces the concept of persistence horizon (depth).
On any individual request, the persistence horizon indicates how many relationships should be traversed in the graph when loading or saving data. 
A horizon of zero means that only the root object's properties will be loaded or saved, a horizon of 1 will include the root object and all its immediate neighbours, and so on. 
This attribute is enabled via a `depth` argument available on all repository and template methods, but SDN 4 chooses sensible defaults so that you don't have to specify the depth attribute unless you want change the default values.

=== Default depth for loading
By default, loading an instance will map that object's simple properties and its immediately-related objects (i.e. depth = 1).
This helps to avoid accidentally loading the entire graph into memory, but allows a single request to fetch not only the object of immediate interest, but also its closest neighbours, which are likely also to be of interest. 
This strategy attempts to strike a balance between loading too much of the graph into memory and having to make repeated requests for data.

If parts of your graph structure are deep and not broad (for example a linked list), you can increase the load horizon for those nodes accordingly. 
Finally, if your graph will fit into memory, and you'd like to load it all in one go, you can set the depth to -1.

On the other hand, when fetching structures which are potentially very "bushy" (e.g. lists of things that themselves have many relationships), you may want to set the load horizon to 0 (depth = 0) to avoid loading thousands of objects, most of which you won't actually inspect.

=== Default depth for persisting
When persisting changes to the model, the default depth is -1. 
This means that *all affected* objects in the entity model that are reachable from the root object being persisted will be modified in the graph. 
This is the recommended approach because it means you can persist all your changes in one request. 
The OGM is able to detect which objects and relationships require changing, so you won't flood Neo4j with a bunch of objects that don't require modification. 
You can change the persistence depth to any value, but you should not make it less than the value used to load the corresponding data or you run the risk of not having changes you expect to be made actually being persisted in the graph.


