[[reference_programming-model_annotations]]
= Defining node entities

Node entities are declared using the `@org.neo4j.ogm.annotation.NodeEntity` annotation.
Relationship entities use the `@org.neo4j.ogm.annotation.RelationshipEntity` annotation.

== @NodeEntity: The basic building block

The `@NodeEntity` annotation is used to declare that a POJO class is an entity backed by a node in the graph database.
Entities handled by Spring Data Neo4j must have a zero-argument constructor to allow the library to construct the objects, although it doesn't need to be declared public.

Fields on the entity are by default mapped to properties of the node.
Fields referencing other node entities (or collections thereof) are linked with relationships.

`@NodeEntity` annotations are inherited from super-types and interfaces.
It is not necessary to annotate your domain objects at every inheritance level.

If the `label` attribute is set then this will replace the default label applied to the node in the database.
This replaces the previous `@TypeAlias` annotation.
The default label is just the simple class name of the annotated entity.
All parent classes are also added as labels so that retrieving a collection of nodes via a parent type is supported.

Entity fields can be annotated with `@Property`, `@GraphId`, `@Transient` or `@Relationship`.
All annotations live in the `org.neo4j.ogm.annotation` package.
Marking a field with the transient modifier has the same effect as annotating it with `@Transient`; it won't be persisted to the graph database.


.Persisting an annotated entity
[source,java]
----
@NodeEntity
public class Actor extends DomainObject {

   @GraphId
   private Long id;

   @Property(name="name")
   private String fullName;

   @Relationship(type="ACTED_IN", direction=Relationship.OUTGOING)
   private List<Movie> filmography;

}

@NodeEntity(label="Film")
public class Movie {

   @GraphId Long id;

   @Property(name="title")
   private String name;

}
----

Saving a simple object graph containing one actor and one film using the above annotated objects would result in the following being persisted in Neo4j.

[source,cypher]
----
(:Actor:DomainObject {name:'Tom Cruise'})-[:ACTED_IN]->(:Film {title:'Mission Impossible'})
----

When annotating your objects, you can apply the annotations to either the fields or their accessor methods, but bear in mind the aforementioned `EntityAccessStrategy` ordering when annotating your domain model.

.Persisting a non-annotated entity
[source,java]
----
public class Actor extends DomainObject {

   private Long id;
   private String fullName;
   private List<Movie> filmography;

}

public class Movie {

   private Long id;
   private String name;

}
----

In this case, a graph similar to the following would be persisted.

----
(:Actor:DomainObject {fullName:'Tom Cruise'})-[:FILMOGRAPHY]->(:Movie {name:'Mission Impossible'})
----

While this will map successfully to the database, it's important to understand that the names of the properties and relationship types are tightly coupled to the class's member names.
Renaming any of these fields will cause parts of the graph to map incorrectly, hence the recommendation to use annotations.


== @GraphId: Neo4j ID Field

This is a required field which must be of type `java.lang.Long`.
It is used by Spring Data Neo4j to store the node or relationship-id to re-connect the entity to the graph.
As such, user code should _never_ assign a value to it.


[NOTE]
====
It must not be a primitive type because then an object in a transient state cannot be represented, as the default value 0 would point to a node with id 0.
====

If the field is simply named 'id' then it is not necessary to annotate it with `@GraphId` as the OGM will use it automatically.

=== Entity Equality

Entity equality can be a grey area, and it is debatable whether natural keys or database IDs best describe equality, as there is the issue of versioning over time, etc.
In previous versions of Spring Data Neo4j, it was recommended to honour the convention that database-issued IDs are the basis for equality, despite the consequences.

In version 4, the dependency of the framework upon a particular style of `equals()` or `hashCode()` implementation has been removed.

The graph-id field is directly checked to see if two entities represent the same node and a 64-bit hash code is used for dirty checking, so you're not forced to write your code in a certain way!

[WARNING]
You are free to write your `equals` and `hashcode` in a domain specific way for managed entities.  However, *we strongly advise developers to not use the `@GraphId` field in these implementations*.
This is because when you first persist an entity, its hashcode changes because SDN populates the database ID on save.
This causes problems if you had inserted the newly created entity into a hash-based collection before saving.



== @Property: Optional annotation for property fields

As we touched on earlier, it is not necessary to annotate property fields as they are persisted by default.
Fields that are annotated as `@Transient` or declared with the `transient` modifier are exempted from persistence.
All fields that contain primitive values are persisted directly to the graph.
All fields convertible to a `String` using the Spring conversion services will be stored as a string.
Spring Data Neo4j includes default type converters that deal with the following types:

- `java.util.Date` to a String in the ISO 8601 format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
- `java.math.BigInteger` to a String property
- `java.math.BigDecimal` to a String property
- binary data (as byte[] or Byte[]) to base-64 String
- `java.lang.Enum` types using the enum's `name()` method and `Enum.valueOf()`

Collections of primitive or convertible values are stored as well.
They are converted to arrays of their type or strings respectively.
Custom converters are also specified by using `@Convert` - this is discussed in detail <<reference_programming-model_conversion,later on>>.

Node property names can be explicitly assigned by setting the `name` attribute.
For example `@Property(name="last_name") String lastName`.  The node property name defaults to the field name when not specified.

[NOTE]
====
Property fields to be persisted to the graph must not be declared `final`.
====

== Runtime Managed Labels

The label applied to a node is the contents of the `@NodeEntity` label property, or if not specified,
it will default to the simple class name of the entity. Sometimes it might be necessary to add and remove additional
labels to a node at _runtime_. We can do this using the `@Labels` annotation. Let's provide a facility for adding
additional labels to the `Student` entity:

```
@NodeEntity
public class Student {

    @Labels
    private List<String> labels = new ArrayList<>();

}
```

Now, upon save, the node's labels will correspond to the entity's class hierarchy _plus_ whatever the contents of the
backing field are. We can use one `@Labels` field per class hierarchy - it should be exposed or hidden from sub-classes
as appropriate.
