[[reference_programming-model_repositories]]
= CRUD with repositories

The repositories provided by Spring Data Neo4j build on the composable repository infrastructure in http://static.springsource.org/spring-data/data-commons/docs/current/reference/html/#repositories[Spring Data Commons]. They allow for interface based composition of repositories consisting of provided default implementations for certain interfaces and additional custom implementations for other methods.

Spring Data Neo4j repositories support annotated and named queries for the Neo4j http://neo4j.com/docs/milestone/query-lang.html[Cypher] query-language.

Spring Data Neo4j comes with typed repository implementations that provide methods for locating node and relationship entities. There are several types of basic repository interfaces and implementations. `CRUDRepository` provides basic operations, `IndexRepository` and `NamedIndexRepository` delegate to Neo4j's internal indexing subsystem for queries, and `TraversalRepository` handles Neo4j traversals.

With the `RelationshipOperationsRepository` it is possible to access, create and delete relationships between entities or nodes. The `SpatialRepository` allows geographic searches (<<reference_spatial>>)

`GraphRepository` is a convenience repository interface, combining `CRUDRepository`, `IndexRepository`, and `TraversalRepository`. Generally, it has all the desired repository methods. If other operations are required then the additional repository interfaces should be added to the individual interface declaration.

== CRUDRepository

`CRUDRepository` delegates to the configured `TypeRepresentationStrategy` (see <<reference_programming-model_typerepresentationstrategy>>) for type based queries. 

Load an entity instance via an id::
`T findOne(id)`

Check for existence of an id in the graph::
`boolean exists(id)`

Iterate over all nodes of a node entity type::
`EndResult<T> findAll()` `EndResult<T> findAll(Sort)` and `Page<T> findAll(Pageable)`

Count the instances of the repository entity type::
`Long count()`

Save entities::
`T save(T)` and `Iterable<T> save(Iterable<T>)`

Delete graph entities::
`void delete(T)`, `void; delete(Iterable<T>)`, and `deleteAll()`

== IndexRepository and NamedIndexRepository

`IndexRepository` works with the indexing subsystem and provides methods to find entities by indexed properties, ranged queries, and combinations thereof. The index key is the name of the indexed entity field, unless overridden in the `@Indexed` annotation. 

Iterate over all indexed entity instances with a certain field value::
`EndResult<T> findAllByPropertyValue(key, value)`

Get a single entity instance with a certain field value::
`T findByPropertyValue(key, value)`

Iterate over all indexed entity instances with field values in a certain numerical range (inclusive)::
`EndResult<T> findAllByRange(key, from, to)`

Iterate over all indexed entity instances with field values matching the given fulltext string or QueryContext query::
`EndResult<T> findAllByQuery(key, queryOrQueryContext)`

There is also a `NamedIndexRepository` with the same methods, but with an additional index name parameter, making it possible to query any index.

== TraversalRepository

`TraversalRepository` delegates to the Neo4j traversal framework. 

Iterate over a traversal result::
`Iterable<T> findAllByTraversal(startEntity, traversalDescription)`

== Query and Finder Methods

[[reference_programming-model_annotatedQueries]]
=== Annotated queries

Queries using the Cypher graph query language can be supplied with the `@Query` annotation. That means every method annotated with `@Query("start n=node:IndexName(key={node or 0}) match (n)-->(m) return m")` will use the supplied query string. The named or indexed parameter `{node}` will be substituted by the actual method parameter. Node and Relationship-Entities are handled directly, Iterables thereof as well. All other parameters are replaced directly (i.e. Strings, Longs, etc). There is special support for the `Sort` and `Pageable` parameters from Spring Data Commons, which are supported to add programmatic paging, slicing and sorting (alternatively static paging and sorting can be supplied in the query string itself). For using the named parameters you have to either annotate the parameters of the method with the `@Param("node")` annotation or enable debug symbols. Indexed parameters are always usable.

If it is required that paged results return the correct total count, the `@Query` annotation can be supplied with a count query in the `countQuery` attribute. This query is executed separately after the result query and its result is used to populate the `totalCount` property of the returned `Page`.

=== Named queries

Spring Data Neo4j also supports the notion of named queries which are externalized in property-config-files (`META-INF/neo4j-named-queries.properties`). Those files have the format: `Entity.finderName=query` (e.g. `Person.findBoss=start p=node({0}) match (p)<-[:BOSS]-(boss) return boss`). Otherwise named queries support the same parameters as annotated queries. For count queries the lookup name is `Entity.finderName.count=count-query`. The default query lookup names can be overriden by using an `@Query` annotation with `queryName="my-query-name"` or `countQueryName="my-query-name"`.

=== Query results

Typical results for queries are `Iterable<Type>, Iterable<Map<String,Object>>, Type, Slice<Type> and Page<Type>`. Nodes and Relationships are converted to their respective Entities (if they exist). Other values are converted using the registered Spring conversion services (e.g. enums).

=== Cypher examples

There is a http://video.neo4j.org/ybMbf/screencast-introduction-to-cypher[screencast] available showing many features of the query language. The following examples are taken from the cineasts dataset of the tutorial section. 

`start n=node(0) return n`::
returns the node with id 0

`start movie=node:Movie(title='Matrix') return movie`::
returns the nodes which are indexed with title equal to 'Matrix'

`start movie=node:Movie(title='Matrix') match (movie)<-[:ACTS_IN]-(actor) return actor.name`::
returns the names of the actors that have a ACTS_IN relationship to the movie node for 'Matrix'

`start movie=node:Movie(title='Matrix') match (movie)<-[r:RATED]-(user) where r.stars > 3 return user.name, r.stars, r.comment`::
returns users names and their ratings (>3) of the movie titled 'Matrix'

`start user=node:User(login='micha') match (user)-[:FRIEND]-(friend)-[r:RATED]->(movie) return movie.title, AVG(r.stars), COUNT(*) order by AVG(r.stars) desc, COUNT(*) desc`::
returns the movies rated by the friends of the user 'micha', aggregated by movie.title, with averaged ratings and rating-counts sorted by both

.Examples of Cypher queries placed on repository methods with `@Query` where values are replaced with method parameters, as described in the <<reference_programming-model_annotatedQueries>>) section.
====
[source,java]
----
public interface MovieRepository extends GraphRepository<Movie> {
    
    // returns the node with id equal to idOfMovie parameter  
    @Query("start n=node({0}) return n")
    Movie getMovieFromId(Integer idOfMovie);

    // returns the nodes which will use index named title equal to movieTitle parameter
    // movieTitle String must not contain any spaces, otherwise you will receive a NullPointerException.
    @Query("start movie=node:Movie(title={0}) return movie")
    Movie getMovieFromTitle(String movieTitle);

    // returns the Actors that have a ACTS_IN relationship to the movie node with the title equal to movieTitle parameter. 
    // (The parenthesis around 'movie' and 'actor' in the match clause are optional.)                       
    @Query("start movie=node:Movie(title={0}) match (movie)&lt;-[:ACTS_IN]-(actor) return actor")
    Page<Actor> getActorsThatActInMovieFromTitle(String movieTitle, PageRequest);

    // returns users who rated a movie (movie parameter) higher than rating (rating parameter)
    @Query("start movie=node:({0}) " +
           "match (movie)&lt;-[r:RATED]-(user) " +
           "where r.stars > {1} " +
           "return user")
    Iterable<User> getUsersWhoRatedMovieFromTitle(Movie movie, Integer rating);

    // returns users who rated a movie based on movie title (movieTitle parameter) higher than rating (rating parameter)
    @Query("start movie=node:Movie(title={0}) " +
           "match (movie)&lt;-[r:RATED]-(user) " +
           "where r.stars > {1} " +
           "return user")
     Iterable<User> getUsersWhoRatedMovieFromTitle(String movieTitle, Integer rating);
 }
----
====

=== Queries derived from finder-method names

As known from Rails or Grails it is possible to derive queries for domain entities from finder method names like `Iterable<Person> findByNameAndAgeGreaterThan(String name, int age)`. Using the infrastructure in Spring Data Commons that allows to collect the meta information about entities and their properties a finder method name can be split into its semantic parts and converted into a cypher query. `@Indexed` fields will be converted into index-lookups of the `start` clause, navigation along relationships will be reflected in the `match` clause properties with operators will end up as expressions in the `where` clause. Order and limiting of the query will by handled by provided `Pageable` or `Sort` parameters. The other parameters will be used in the order they appear in the method signature so they should align with the expressions stated in the method name.

.Some examples of methods and resulting Cypher queries of a PersonRepository
====
[source,java]
----
public interface PersonRepository 
               extends GraphRepository<Person> {

    // start person=node:Person(id={0}) return person
    Person findById(String id)

    // start person=node:Person({0}) return person - {0} will be "id:"+name
    Iterable<Person> findByNameLike(String name)

    // start person=node:__types__("className"="com...Person") 
    // where person.age = {0} and person.married = {1}
    // return person
    Iterable<Person> findByAgeAndMarried(int age, boolean married)

    // start person=node:__types__("className"="com...Person")
    // match person<-[:CHILD]-parent
    // where parent.age > {0} and person.married = {1}
    // return person
    Iterable<Person> findByParentAgeAndMarried(int age, boolean married)
}
----
====

=== Derived Finder Methods

Use the meta information of your domain model classes to declare repository finders that navigate along relationships and compare properties. The path defined with the method name is used to create a Cypher query that is executed on the graph.

.Repository and usage of derived finder methods
====
[source,java]
----
@NodeEntity
public static class Person {
    @GraphId Long id;
    private String name;
    private Group group;

    private Person(){}
    public Person(String name) {
        this.name = name;
    }
}

@NodeEntity
public static class Group {
    @GraphId Long id;
    private String title;
    // incoming relationship for the person -> group
    @RelatedTo(type = "group", direction = Direction.INCOMING)
    private Set<Person> members=new HashSet<Person>();

    private Group(){}
    public Group(String title, Person...people) {
        this.title = title;
        members.addAll(asList(people));
    }
}
public interface PersonRepository extends GraphRepository<Person> {
    Iterable<Person> findByGroupTitle(String name);
}

@Autowired PersonRepository personRepository;

Person oliver=personRepository.save(new Person("Oliver"));
final Group springData = new Group("spring-data",oliver);
groupRepository.save(springData);

final Iterable<Person> members = personRepository.findByGroupTitle("spring-data");
assertThat(members.iterator().next().name, is(oliver.name));
----
====

== Cypher-DSL repository

Spring Data Neo4j supports the new Cypher-DSL to write Cypher queries in a statically typed way. Just by including `CypherDslRepository` to your repository you get the `Page<T> query(Execute query, params, Pageable page)`, `Page<T> query(Execute query, Execute countQuery, params, Pageable page)` and the `EndResult<T> query(Execute query, params);`. The result type of the Cypher-DSL builder is called `Execute`.

.Examples for Cypher-DSL repository
====
[source,java]
----
import static org.neo4j.cypherdsl.CypherQuery.*;
import static org.neo4j.cypherdsl.querydsl.CypherQueryDSL.*;

public interface PersonRepository extends GraphRepository<Person>,
  CypherDslRepository<Person> {}

@Autowired PersonRepository repo;
// START company=node:Company(name={name}) MATCH company<-[:WORKS_AT]->person RETURN person

Execute query = start( lookup( "company", "Company", "name", param("name") ) ).
                          match( path().from( "company" ).in( "WORKS_AT" ).to( "person" )).
                          returns( identifier( "person" ))
Page<Person> people = repo.query(query , map("name","Neo4j"), new PageRequest(1,10));

QPerson person = QPerson.person;
QCompany company = QCompany.company;
Execute query = start( lookup( company, "Company", company.name, param("name") ) ).
                          match( path().from( company ).in( "WORKS_AT" ).to( person ).
                          .where(person.firstName.like("P*").and(person.age.gt(25))).
                          returns( identifier(person) )
EndResult<Person> people = repo.query(query , map("name","Neo4j"));
----
====

== Cypher-DSL and QueryDSL

To use Cypher-DSL with Query-DSL the Mysema dependencies have to be declared explicitly as they are optional in the Cypher-DSL project.

[source,xml]
----
<dependency>
    <groupId>com.mysema.querydsl</groupId>
    <artifactId>querydsl-core</artifactId>
    <version>2.2.3</version>
    <optional>true</optional>
</dependency>
<dependency>
    <groupId>com.mysema.querydsl</groupId>
    <artifactId>querydsl-lucene</artifactId>
    <version>2.2.3</version>
    <optional>true</optional>
    <exclusions>
        <exclusion>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.mysema.querydsl</groupId>
    <artifactId>querydsl-apt</artifactId>
    <version>2.2.3</version>
    <scope>provided</scope>
</dependency>
----

It is possible to use the Cypher-DSL along with the predicates and code generation features of the QueryDSL project. This will allow you to use Java objects as part of the query, rather than strings, for the names of properties and such. In order to get this to work you first have to add a code processor to your Maven build, which will parse your domain entities marked with `@NodeEntity`, and from that generate QPerson-style classes, as shown in the previous section. Here is what you need to include in your Maven POM file.

[source,xml]
----
<plugin>
    <groupId>com.mysema.maven</groupId>
    <artifactId>maven-apt-plugin</artifactId>
    <version>1.0.2</version>
    <configuration>
        <processor>org.springframework.data.neo4j.querydsl.SDNAnnotationProcessor</processor>
    </configuration>
    <executions>
        <execution>
            <id>test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
                <goal>test-process</goal>
            </goals>
            <configuration>
                <outputDirectory>target/generated-sources/test</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
----

This custom QueryDSL `AnnotationProcessor` will generate the query classes that can be used when constructing Cypher-DSL queries, as in the previous section.

== Creating repositories

The `Repository` instances should normally be injected but can also be created manually via the `Neo4jTemplate`.

.Using basic GraphRepository methods
====
[source,java]
----
public interface PersonRepository extends GraphRepository<Person> {}

@Autowired PersonRepository repo;
// OR
GraphRepository<Person> repo = template
                           .repositoryFor(Person.class);

Person michael = repo.save(new Person("Michael", 36));

Person dave = repo.findOne(123);

Long numberOfPeople = repo.count();

EndResult<Person> devs = graphRepository.findAllByPropertyValue("occupation", "developer");

EndResult<Person> middleAgedPeople = graphRepository.findAllByRange("age", 20, 40);

EndResult<Person> aTeam = graphRepository.findAllByQuery("name", "A*");

Iterable<Person> aTeam = repo.findAllByQuery("name", "A*");

Iterable<Person> davesFriends = repo.findAllByTraversal(dave,
    Traversal.description().pruneAfterDepth(1)
    .relationships(KNOWS).filter(returnAllButStartNode()));
----
====

== Composing repositories

The recommended way of providing repositories is to define a repository interface per domain class. The mechanisms provided by the repository infrastructure will automatically detect them, along with additional implementation classes, and create an injectable repository implementation to be used in services or other spring beans.

.Composing repositories
====
[source,java]
----
public interface PersonRepository extends GraphRepository<Person>, PersonRepositoryExtension {}

// configure the repositories, preferably via the neo4j:repositories namespace
// (template reference is optional)
<neo4j:repositories base-package="org.example.repository"
    graph-database-context-ref="template"/>

// have it injected
@Autowired
PersonRepository personRepository;
// or created via the template
PersonRepository personRepository = template.repositoryFor(Person.class);


Person michael = personRepository.save(new Person("Michael",36));

Person dave=personRepository.findOne(123);

Iterable<Person> devs = personRepository.findAllByPropertyValue("occupation","developer");

Iterable<Person> aTeam = graphRepository.findAllByQuery( "name","A*");

Iterable<Person> friends = personRepository.findFriends(dave);


// alternatively select some of the required repositories individually
public interface PersonRepository extends CRUDGraphRepository<Node,Person>,
        IndexQueryExecutor<Node,Person>, TraversalQueryExecutor<Node,Person>,
        PersonRepositoryExtension {}

// provide a custom extension if needed
public interface PersonRepositoryExtension {
    Iterable<Person> findFriends(Person person);
}

public class PersonRepositoryImpl implements PersonRepositoryExtension {
    // optionally inject default repository, or use DirectGraphRepositoryFactory
    @Autowired PersonRepository baseRepository;
    public Iterable<Person> findFriends(Person person) {
        return baseRepository.findAllByTraversal(person, friendsTraversal);
    }
}

// configure the repositories, preferably via the datagraph:repositories namespace
// (template reference is optional)
<neo4j:repositories base-package="org.springframework.data.neo4j"
    graph-database-context-ref="template"/>

// have it injected
@Autowired
PersonRepository personRepository;

Person michael = personRepository.save(new Person("Michael",36));

Person dave=personRepository.findOne(123);

EndResult<Person> devs = personRepository.findAllByPropertyValue("occupation","developer");

EndResult<Person> aTeam = graphRepository.findAllByQuery( "name","A*");

Iterable<Person> friends = personRepository.findFriends(dave);
----
====

NOTE: If you use `<context:component-scan>` in your spring config, please make sure to put it behind `<neo4j:repositories>`, as the `RepositoryFactoryBean` adds new bean definitions for all the declared repositories, the context scan doesn't pick them up otherwise.
