[[reference_spatial]]
= Geospatial Queries

`SpatialRepository` is a dedicated `Repository` for spatial queries. Spring Data Neo4j provides an optional dependency to https://github.com/neo4j/spatial[neo4j-spatial] which is an advanced library for GIS operations. So if you include the maven dependency in your `pom.xml`, Neo4j-Spatial and the required `SPATIAL` index provider is available.

Spring Data Neo4j integrates with the common geo-spatial types in Spring Data Commons, like `Circle, Box, Polygon and Point`. You can use them as parameters for repository finder methods and property values. We also provide converters between WKT and `Shape`/`Point` objects.

.Neo4j-Spatial Dependencies
====
[source,java]
----
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-spatial</artifactId>
    <version>0.13-neo4j-2.0.1</version>
</dependency>
----
====

To have your entities available for spatial index queries, please include a String property containing a "well known text", location string. WKT is the http://en.wikipedia.org/wiki/Well-known_text[Well Known Text Spatial Format] e.g. `POINT( LON LAT )` or `POLYGON (( LON1 LAT1 LON2 LAT2 LON3 LAT3 LON1 LAT1 ))`

Alternatively you can also use one of the geo-spatial primitives from Spring Data Commons which are automatically converted to WKT when stored in the graph.

.Fields of Well Known Text
====
[source,java]
----
@NodeEntity
class Venue {
   String name;
   @Indexed(type = POINT, indexName = "VenueLocation") String wkt;
   public void setLocation(float lon, float lat) {
      this.wkt = String.format("POINT( %.2f %.2f )",lon,lat);
   }
}

venue.setLocation(15,56);
----
====

.Field of Point
====
[source,java]
----
@NodeEntity
class Venue {
   String name;
   @Indexed(type = POINT, indexName = "VenueLocation") Point wkt;
}

venue.setLocation(new Point(15,56));
----
====

After adding the `SpatialRepository` to your repository you can use the `findWithinBoundingBox`, `findWithinDistance`, `findWithinWellKnownText`, `findWithinShape` methods. We recommend to use the methods using the geospatial primitives as they are more typesafe and less error-prone in mixing the coordinate order.

.Spatial Queries
====
[source,java]
----
Iterable<Person> teamMembers = personRepository.findWithinBoundingBox("personLayer", 55, 15, 57, 17);
Iterable<Person> teamMembers = personRepository.findWithinBoundingBox("personLayer", new Box(new Point(15,55), new Point(17,57));
Iterable<Person> teamMembers = personRepository.findWithinWellKnownText("personLayer", "POLYGON ((15 55, 15 57, 17 57, 17 55, 15 55))");
Iterable<Person> teamMembers = personRepository.findWithinShape("personLayer", new Polygon(new Point(15,55),new Point(15,57), new Point(17,57),new Point(17,55)));
Iterable<Person> teamMembers = personRepository.findWithinDistance("personLayer", 16,56,70);
Iterable<Person> teamMembers = personRepository.findWithinDistance("personLayer", new Circle(new Point(16,56),new Distance(70, Metrics.KILOMETERS)));
----
====

.Methods of the Spatial Repository
====
[source,java]
----
public interface SpatialRepository<T> {
    @Transactional
    EndResult<T> findWithinBoundingBox(String indexName, double lowerLeftLat,
                                              double lowerLeftLon,
                                              double upperRightLat,
                                              double upperRightLon);

    @Transactional
    EndResult<T> findWithinBoundingBox(String indexName, Box box);

    @Transactional
    EndResult<T> findWithinDistance( final String indexName, final double lat, double lon, double distanceKm);

    @Transactional
    EndResult<T> findWithinDistance( final String indexName, Circle circle);

    @Transactional
    EndResult<T> findWithinWellKnownText( final String indexName, String wellKnownText);

    /**
     * Converts the shape into a well-known text representation and executes the appropriate WKT query
     */
    @Transactional
    EndResult<T> findWithinShape( final String indexName, Shape shape);
}
----
====

.Derived Spatial Finder Methods
====
[source,java]
----
public interface PersonRepository extends GraphRepository<Person>, SpatialRepository<Person> {
    Collection<Person> findByWktNearAndName(Circle circle, String name);
    Collection<Person> findByWktWithinAndAgeGreaterThan(Circle circle, int age);
    Collection<Person> findByWktWithinAndPersonality(Polygon polygon, Personality personality);
    Collection<Person> findByWktWithin(Box box);
}
----
====
