[[reference_programming-model_template]]
= Neo4jTemplate

The `Neo4jTemplate` offers the convenient API of Spring templates for the Neo4j graph database.  
As of version 4, the Spring Data Neo4j Template wraps the underlying object-graph mapping `Session`, but still provides the core functionality to persist objects to the graph and load them in a variety of ways.  
Indeed, you can just use the `Session` directly in your code if you need greater control, but the `Neo4jTemplate` may well be easier for general use.

== Basic Operations

For Spring Data Neo4j 4, the changes to the underlying architecture have led to the pruning of the `Neo4jTemplate` feature set.  
Basic operations are now entirely limited to CRUD operations on entities and executing arbitrary Cypher queries; more low-level manipulation of the graph database is not possible.

[NOTE] 
There is no longer a way to manipulate relationship- and node-objects directly. 

Given that the latest version of the framework is driven by Cypher queries alone, there's no way to work directly with `Node` and `Relationship` objects any more in remote server mode.  
Similarly, the `traverse()` method has disappeared, again because the underlying query-driven model doesn't handle it in an efficient way.

If you find yourself in trouble because of the omission of these features, then your best options are:

. Write a Cypher query to perform the operations on the nodes/relationships instead
. Write a Neo4j server extension and call it over REST from your application

Of course, there are pros and cons to both of these approaches, but these are largely outside the scope of this document.  
In general, for low-level, very high-performance operations like complex graph traversals you'll get the best performance by writing a server-side extension.  
For most purposes, though, Cypher will be performant and expressive enough to perform the operations that you need.

== Entity Persistence

`Neo4jTemplate` allows you to `save`, `load`, `loadAll` and `delete` entities.  
However, as of SDN 4, it no longer provides the stored type information via `getStoredJavaType`.  
The eagerness with which objects are retrieved is controlled by specifying the 'depth' argument to any of the load methods.  

All of these basic CRUD methods just call onto the underlying methods of `Session`, albeit with transaction handling and exception translation managed for you.

== Cypher Queries

The `Neo4jTemplate` also allows execution of arbitrary Cypher queries via its `query`, `queryForObject` and `queryForObjects` methods.  
Cypher queries that return tabular results should be passed into the `query` method. 
An `org.neo4j.ogm.session.result.Result` is returned. This consists of `org.neo4j.ogm.session.result.QueryStatistics` representing statistics of
modifying cypher statements if applicable, and an `Iterable<Map<String,Object>>` containing the raw data, which can be either used as-is or converted into a richer type if needed.
The keys in each `Map` correspond to the names listed in the return clause of the executed Cypher query.

//For the query methods that retrieve mapped objects, the recommended query format is to return a path, which should ensure that known types get mapped correctly and joined together with relationships as appropriate.
[NOTE]
Modifications made to the graph via Cypher queries directly will not be reflected in your domain objects within the session.

== Transactions

The `Neo4jTemplate` provides implicit transactions for some of its methods. 
For instance `save`, `delete` and `query` provide auto-commit transactions.
For other modifying operations you would need to provide Spring Transaction management using `@Transactional` or the `TransactionTemplate`.

== Data Manipulation Events (formerly Lifecycle Events)

Neo4j Template utilises Spring's event mechanism through `ApplicationListener` and `ApplicationEvent` to notify interested parties about certain data manipulations performed through it.  
The following hooks are available in the form of types of application event:

* BeforeSaveEvent
* AfterSaveEvent
* BeforeDeleteEvent
* AfterDeleteEvent

The point at which these events get fired by the `Neo4jTemplate` should be pretty obvious from the names.
The following example demonstrates how to hook into the Spring application events API and register listeners that perform behaviour across types of entities as actions are performed using the template.

.Auditing Entities and Generating Unique Application-level IDs
[source,java]
----
@Configuration
@EnableNeo4jRepositories
public class ApplicationConfig extends Neo4jConfiguration {
    ...
    @Bean
    ApplicationListener<BeforeSaveEvent> beforeSaveEventApplicationListener() {
        return new ApplicationListener<BeforeSaveEvent>() {
            @Override
            public void onApplicationEvent(BeforeSaveEvent event) {
                AcmeEntity entity = (AcmeEntity) event.getEntity();
                entity.setUniqueId(acmeIdFactory.create());
            }
        };
    }

    @Bean
    ApplicationListener<AfterSaveEvent> afterSaveEventApplicationListener() {
        return new ApplicationListener<AfterSaveEvent>() {
            @Override
            public void onApplicationEvent(AfterSaveEvent event) {
                AcmeEntity entity = (AcmeEntity) event.getEntity();
                auditLog.onEventSaved(entity);
            }

    }

    @Bean
    ApplicationListener<AfterDeleteEvent> deleteEventApplicationListener() {
        return new ApplicationListener<AfterDeleteEvent>() {
            @Override
            public void onApplicationEvent(AfterDeleteEvent event) {
                AcmeEntity entity = (AcmeEntity) event.getEntity();
                auditLog.onEventDeleted(entity);
            }
        };
    }
    ...
----

Note that changes made to entities in the before-save event application listener are reflected in the stored entity - after-save ones are not.
