[[reference_programming-model_template]]
= Using the OGM Session.

[Warning]
`Session` now replaces `Neo4jTemplate`'s functionality as all functionality can be found on the OGM `Session` object.

SDN now allows you to wire up the OGM `Session` directly into your Spring managed beans.

While SDN `Repository`'s will cover a majority of user scenarios sometimes it doesn't offer enough depth. The OGM's `Session` offers a convenient API to interact more tightly with a Neo4j graph database.

== Basic Operations

For Spring Data Neo4j 4, the changes to the underlying architecture have led to the pruning of the `Neo4jTemplate` feature set.
Basic operations are now entirely limited to CRUD operations on entities and executing arbitrary Cypher queries; more low-level manipulation of the graph database is not possible.

[NOTE]
There is no longer a way to manipulate relationship- and node-objects directly.

Given that the latest version of the framework is driven by Cypher queries alone, there's no way to work directly with `Node` and `Relationship` objects any more in remote server mode.
Similarly, the `traverse()` method has disappeared, again because the underlying query-driven model doesn't handle it in an efficient way.

If you find yourself in trouble because of the omission of these features, then your best options are:

. Write a Cypher query to perform the operations on the nodes/relationships instead
. Write a Neo4j server extension and call it over REST from your application

Of course, there are pros and cons to both of these approaches, but these are largely outside the scope of this document.
In general, for low-level, very high-performance operations like complex graph traversals you'll get the best performance by writing a server-side extension.
For most purposes, though, Cypher will be performant and expressive enough to perform the operations that you need.

== Entity Persistence

`Session` allows you to `save`, `load`, `loadAll` and `delete` entities.
The eagerness with which objects are retrieved is controlled by specifying the 'depth' argument to any of the load methods.

All of these basic CRUD methods just call onto the underlying methods of `Session`, albeit with transaction handling and exception translation managed for you by SDN's Transaction Manager bean.

== Cypher Queries

The `Session` also allows execution of arbitrary Cypher queries via its `query`, `queryForObject` and `queryForObjects` methods.
Cypher queries that return tabular results should be passed into the `query` method.
An `org.neo4j.ogm.session.result.Result` is returned. This consists of `org.neo4j.ogm.session.result.QueryStatistics` representing statistics of
modifying cypher statements if applicable, and an `Iterable<Map<String,Object>>` containing the raw data, of which nodes and relationships are mapped to domain entities if possible.
The keys in each `Map` correspond to the names listed in the return clause of the executed Cypher query.

//For the query methods that retrieve mapped objects, the recommended query format is to return a path, which should ensure that known types get mapped correctly and joined together with relationships as appropriate.
[NOTE]
Modifications made to the graph via Cypher queries directly will not be reflected in your domain objects within the session.

== Transactions

If you configured the `Neo4jTransactionManager` bean, `Session`s that are managed by Spring will automatically take part in Thread contextual Transactions.
In order to do this you will need to wrap your service code using `@Transactional` or the `TransactionTemplate`.

For more details see <<reference_programming-model_transactions,Transactions>>
