[[reference_programming-model_typerepresentationstrategy]]
= Entity Type Representation

As of Spring Data Neo4j 4, type representation has been greatly simplified to the point that there is just one strategy.
The `TypeRepresentationStrategy` has disappeared and a single label-based model is all that is supported.

For `@NodeEntity` classes, the simple names of the class and each of its parent classes (excluding `java.lang.Object`)
is written as a node label.  
This node label is used in Cypher queries generated by the OGM to find objects of a particular type, and by labelling using superclasses as well it becomes possible to retrieve collections of entities as abstract super types.

.Example domain model and labels
[source,java]
----
@NodeEntity
public abstract class DomainObject {
   @GraphId
   protected Long id;
}

public class Person extends DomainObject {
   ...
}

public class Lady extends Person {
   ...
}

public class Gentleman extends Person {
   ...
}

// creates a node with labels Gentleman:Person:DomainObject
repository.save(new Gentleman());

// retrieve all ladies and gentlemen
Collection<Person> people = repository.loadAll(Person.class);
----

The label applied to a node in the database can be configured by setting the value of the `label` property in the `@NodeEntity` annotation.

//For `@RelationshipEntity` classes, the simple name of the class is used to derive the relationship type to use, although it's converted into SNAKE_CASE to honour the naming conventions of Neo4j relationships.
//Much like node entities, you can configure the relationship type to use by setting the `type` property in the `@RelationshipEntity` annotation.
In the current version, it is mandatory to specify the relationship type on a `@RelationshipEntity` annotation.
