[[reference_programming-model_typerepresentationstrategy]]
= Entity type representation

There are several ways to represent the Java type hierarchy of the data model in the graph. In general, for all node and relationship entities, type information is needed to perform certain repository operations (such as findAll()). This means that some of the type information hierarchy needs to be saved in the graph database, and SDN makes use of "Type Representation Strategies" in order to achieve this.

Implementations of `TypeRepresentationStrategy` take care of persisting this information during entity instance creation. They are also used by certain repository methods to perform their operations, like `findAll` and `count`. The derived finderMethods also use the type information for graph global queries.

There are four available implementations for node entities to choose from, Spring Data Neo4j defaults to the label based strategy. 

* `LabelBasedNodeTypeRepresentationStrategy` this is the default strategy used.
+
Stores entity types in node labels. Each node gets labeled with its type and all supertypes and interfaces that are also `@NodeEntity`-annotated. There is a special Label prefixed with _ that represents the current type of the entity.
+
* `IndexingNodeTypeRepresentationStrategy`
+
Stores entity types in the integrated index. Each entity node gets indexed with its type and all supertypes and interfaces that are also `@NodeEntity`-annotated. The special index used for this is named `__types__`. Additionally, in order to retrieve the type of an entity node, each node has a property `__type__` with the fully qualified type of that entity.
+
* `SubReferenceNodeTypeRepresentationStrategy`
+
Stores entity types in a tree in the graph representing the type and interface hierarchy. Each entity has a INSTANCE_OF relationship to a type node representing that entity's type. The type may or may not have a SUBCLASS_OF relationship to another type node.
+
* `NoopNodeTypeRepresentationStrategy`
+
Does not store any type information, and does hence not support finding by type, counting by type, or retrieving the type of any entity.

There are two implementations for relationship entities available, with the same behavior as the corresponding ones above: 

* `IndexingRelationshipTypeRepresentationStrategy`
+
Stores relationship entity types in the integrated index. Each entity relationship gets indexed with its type and all supertypes and interfaces that are also `@RelationshipEntity`-annotated. The special index used for this is named `__rel_types__`. Additionally, in order to retrieve the type of an entity relationship, each relationship has a property `__type__` with the fully qualified type of that entity.
+
* `NoopRelationshipTypeRepresentationStrategy`
+
In order to use a different Type Representation Strategy, simply register an alternative "typeRepresentationStrategyFactory" spring bean specifying the strategy required. For example to use the legacy indexing strategy for nodes you could define the following override bean. 

.XML-based configuration
====
[source,xml]
----
<bean id="typeRepresentationStrategyFactory" class="org.springframework.data.neo4j.support.typerepresentation.TypeRepresentationStrategyFactory">
    <constructor-arg ref="graphDatabase"/>
    <constructor-arg value="Indexed"/>
</bean>
----
====

Whilst in Java Config this may look as follows: 

.Java-based configuration
====
[source,java]
----
@Configuration
@EnableNeo4jRepositories(basePackages = "org.example.repositories")
static class Config extends Neo4jConfiguration {

    Config() {
        // Equivalent of setting basePackage for XML based <neo4j:config base-package=".."/>
        // (This will probably move into an/the @EnableNeo4jRepositories in the future)
        setBasePackage("org.example.domain");
    }

    @Override
    public TypeRepresentationStrategyFactory typeRepresentationStrategyFactory() {
        return new TypeRepresentationStrategyFactory(
                    graphDatabase(),
                    TypeRepresentationStrategyFactory.Strategy.Indexed);
    }

    ...

}
----
====

As some type information is also stored in labels, node/relationship-properties and/or indexes it might amount to a substantial amount of data in the graph. It is possible to use an `@TypeAlias("name")` annotation on nodes and relationships to have a short constant name for each type which is (unlike the default approach) renaming-refactoring-safe. From 3.0 onwards, Spring Data Neo4j uses the simple class name as the default whilst previous versions used to default to the fully qualified name. If you would like to use the fully qualified class name by default, you can 

* Register a `Neo4jMappingContext` bean configured with an instance of `org.springframework.data.neo4j.support.mapping.ClassNameAlias`
* Override the spring "entityAlias" bean with an instance of `org.springframework.data.neo4j.support.mapping.ClassNameAlias`. For example, using XML config this would look as follows: 

[source,xml]
----
<bean id="entityAlias" class="org.springframework.data.neo4j.support.mapping.ClassNameAlias" />
----

It is also possible to opt out of storing type information completely by using the `NoopTypeRepresentationStrategies`.

Spring Data Neo4j will by default autodetect which are the most suitable strategies for node and relationship entities. For new data stores, it will always opt for the indexing strategies (Label based for nodes, and legacy index based for relationships). If a data store was created with the older `SubReferenceNodeTypeRepresentationStrategy`, then it will continue to use that strategy for node entities. It will however in that case use the no-op strategy for relationship entities, which means that the old data stores have no support for searching for relationship entities. The indexing strategies are recommended for all new users.

== Entity type safety

While some methods such as `findAll` and count will used the stored type information to return uniformly typed entities, some others such as `findOne` will fetch the requested node regardless of its type. This may result in odd behaviors where a repository extending `GraphRepository<T>` may return entities of type other than T (see example below).

.Requests to repository without type safety enforcement
====
[source,java]
----
@NodeEntity
public class Dog {
    @GraphId Long nodeId
}

@NodeEntity
public class Cat {
    @GraphId Long nodeId
}

public interface CatRepository extends GraphRepository<Cat> {}

public interface DogRepository extends GraphRepository<Dog> {}

catRepository.save(new Cat());
dogRepository.save(new Dog());

GET /dogs/0 // returns a Cat
GET /dogs/1 // returns a Dog
----
====

In order to customize the type safety enforcement applied when creating entities from the requested nodes in the graph, you might want to register a different "typeSafetyPolicy" spring bean specifying the `TypeSafetyOption` to use.

There are 3 different type safety options available :

* `TypeSafetyOption.NONE` : Sets the system to not be type safe.
* `TypeSafetyOption.RETURNS_NULL` : Sets the system to return null if a entity should be loaded which is not of the requested type.
* `TypeSafetyOption.THROWS_EXCEPTION` : Sets the system to throw an exception if a entity should be loaded which is not of the requested type (default setting).

The `TypeSafetyPolicy` override bean can be declared in the following way :

.TypeSafetyPolicy XML-based configuration
====
[source,xml]
----
<bean id="typeSafetyPolicy" class="org.springframework.data.neo4j.support.typesafety.TypeSafetyPolicy">
    <constructor-arg value="RETURNS_NULL" />
</bean>
----
====

Or in java config :

.TypeSafetyPolicy Java-based configuration
====
[source,java]
----
@Configuration
@EnableNeo4jRepositories(basePackages = "org.example.repositories")
static class Config extends Neo4jConfiguration {

    Config() {
        // Equivalent of setting basePackage for XML based <neo4j:config base-package=".."/>
        // (This will probably move into an/the @EnableNeo4jRepositories in the future)
        setBasePackage("org.example.domain");
    }

    @Override
    public TypeSafetyPolicy typeSafetyPolicy() throws Exception {
        return new TypeSafetyPolicy(TypeSafetyOption.RETURNS_NULL);
    }

    ...

}
----
====
