/*
 * Copyright 2011-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.data.falkordb.core.schema;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.apiguardian.api.API;

/**
 * Annotation to mark a field in a {@link RelationshipProperties} annotated class as the
 * relationship's internal ID.
 * <p>
 * This annotation is used to identify the field that holds the internal ID of a
 * relationship in FalkorDB. The relationship ID is typically a {@code Long} value that is
 * automatically generated by the database and represents the unique identifier of the
 * relationship edge.
 * <p>
 * Example usage: <pre>
 * &#64;RelationshipProperties
 * public class ActedIn {
 *
 *     &#64;RelationshipId
 *     private Long id;
 *
 *     &#64;TargetNode
 *     private Person actor;
 *
 *     private List&lt;String&gt; roles;
 *     private Integer year;
 *
 *     // constructors, getters, setters...
 * }
 * </pre>
 * <p>
 * In the above example, the {@code id} field marked with {@code @RelationshipId} will
 * hold the internal ID of the relationship as assigned by FalkorDB.
 * <p>
 * This annotation is specifically designed for use with {@link RelationshipProperties}
 * annotated classes and should not be used on regular node entities. For node entities,
 * use {@link Id} or {@link org.springframework.data.annotation.Id} instead.
 *
 * @author Shahar Biron (FalkorDB adaptation)
 * @since 1.0
 * @see RelationshipProperties
 * @see TargetNode
 * @see Id
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
@Inherited
@API(status = API.Status.STABLE, since = "1.0")
public @interface RelationshipId {

}
