/*
 * Copyright (c) 2023-2025 FalkorDB Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.springframework.data.falkordb.core.schema;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import org.apiguardian.api.API;

/**
 * Annotation to mark a field in a {@link RelationshipProperties} annotated class as the
 * relationship's internal ID.
 * <p>
 * This annotation is used to identify the field that holds the internal ID of a
 * relationship in FalkorDB. The relationship ID is typically a {@code Long} value that is
 * automatically generated by the database and represents the unique identifier of the
 * relationship edge.
 * <p>
 * Example usage: <pre>
 * &#64;RelationshipProperties
 * public class ActedIn {
 *
 *     &#64;RelationshipId
 *     private Long id;
 *
 *     &#64;TargetNode
 *     private Person actor;
 *
 *     private List&lt;String&gt; roles;
 *     private Integer year;
 *
 *     // constructors, getters, setters...
 * }
 * </pre>
 * <p>
 * In the above example, the {@code id} field marked with {@code @RelationshipId} will
 * hold the internal ID of the relationship as assigned by FalkorDB.
 * <p>
 * This annotation is specifically designed for use with {@link RelationshipProperties}
 * annotated classes and should not be used on regular node entities. For node entities,
 * use {@link Id} or {@link org.springframework.data.annotation.Id} instead.
 *
 * @author Shahar Biron (FalkorDB adaptation)
 * @since 1.0
 * @see RelationshipProperties
 * @see TargetNode
 * @see Id
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
@Inherited
@API(status = API.Status.STABLE, since = "1.0")
public @interface RelationshipId {

}
