[[reference_programming_model_template]]
= Neo4jTemplate

The `Neo4jTemplate` offers the convenient API of Spring templates for the Neo4j graph database.  As of version 4, the Spring Data Neo4j Template wraps the underlying object-graph mapping `Session`, but still provides the core functionality to persist objects to the graph and load them in a variety of ways.  Indeed, you can just use the `Session` directly in your code if you need greater control, but the `Neo4jTemplate` may well be easier for general use.

== Basic operations

For Spring Data Neo4j 4, the changes to the underlying architecture have led to the pruning of the `Neo4jTemplate` feature set.  Basic operations are now entirely limited to CRUD operations on entities and executing arbitrary Cypher queries; more low-level manipulation of the graph database is not possible.

NOTE: There is no longer a way to manipulate relationships and nodes directly. 

Given that the latest version of the framework is driven by Cypher queries alone, there's no way to work directly with `Node` and `Relationship` objects any more in remote server mode.  Similarly, the `traverse()` method has disappeared, again because the underlying query-driven model doesn't handle it in an efficient way.

If you find yourself in trouble because of the omission of these features, then your best options are:

. Write a Cypher query to perform the operations on the nodes/relationships instead
. Write a Neo4j server plugin and call it over REST from your application

Of course, there are pros and cons to both of these approaches, but these are largely outside the scope of this document.  In general, for low-level operations like complex graph traversals you'll get the best performance by writing a server-side plugin, which is generally easier to test and maintain than the sort of solution available with earlier versions of SDN anyway.  For many purposes, though, Cypher will be performant and expressive enough to perform the operations that you need.


== Entity-Persistence

`Neo4jTemplate` allows to `save`, `load(One/All)` and `delete` entities.  However, as of SDN 4, it no longer provides the stored type information via `getStoredJavaType`.  The eagerness with which objects are retrieved is controlled by specifying the 'depth' argument to any of the load methods.  

All of these basic CRUD methods just call onto the corresponding methods of `Session`, albeit with transaction handling thrown in to save you the effort of manually managing them.

== Cypher Queries

The `Neo4jTemplate` also allows execution of arbitrary Cypher queries via its `query`, `queryForObject` and `queryForObjects` methods.  Cypher queries that return tabular results should be passed into the `query` method and an `Iterable<Map<String,Object>>` containing the raw data is returned, which can be either used as-is or converted into a richer type if needed.  The keys in each `Map` correspond to the names listed in the return clause of the executed Cypher query.

For the query methods that retrieve mapped objects, the recommended query format is to return a path, which should ensure that known types get mapped correctly and joined together with relationships as appropriate.

For Cypher update operations, `Neo4jTemplate` provides an `execute` method, to which an arbitrary Cypher update statement (such as CREATE, MERGE or DELETE) can be passed.

== Transactions

The `Neo4jTemplate` provides implicit transactions for some of its methods. For instance `save` uses them. For other modifying operations please provide Spring Transaction management using `@Transactional` or the `TransactionTemplate`.

== Lifecycle Events

NOTE: These events are not implemented as of milestone 1 of SDN 4.

Neo4j Template offers basic lifecycle events via Spring's event mechanism using ApplicationListener and ApplicationEvent. The following hooks are available in the form of types of application event:

* BeforeSaveEvent
* AfterSaveEvent
* DeleteEvent - after the event has been deleted

The following example demonstrates how to hook into the application lifecycle and register listeners that perform behaviour across types of entities during this life cycle:

.Auditing Entities and Generating Unique Application-level IDs
====
[source,java]
----
@Configuration
@EnableNeo4jRepositories
public class ApplicationConfig extends Neo4jConfiguration {
    ...
    @Bean
    ApplicationListener<BeforeSaveEvent> beforeSaveEventApplicationListener() {
        return new ApplicationListener<BeforeSaveEvent>() {
            @Override
            public void onApplicationEvent(BeforeSaveEvent event) {
                AcmeEntity entity = (AcmeEntity) event.getEntity();
                entity.setUniqueId(acmeIdFactory.create());
            }
        };
    }

    @Bean
    ApplicationListener<AfterSaveEvent> afterSaveEventApplicationListener() {
        return new ApplicationListener<AfterSaveEvent>() {
            @Override
            public void onApplicationEvent(AfterSaveEvent event) {
                AcmeEntity entity = (AcmeEntity) event.getEntity();
                auditLog.onEventSaved(entity);
            }
        };
    }

    @Bean
    ApplicationListener<DeleteEvent> deleteEventApplicationListener() {
        return new ApplicationListener<DeleteEvent>() {
            @Override
            public void onApplicationEvent(DeleteEvent event) {
                AcmeEntity entity = (AcmeEntity) event.getEntity();
                auditLog.onEventDeleted(entity);
            }
        };
    }
    ...
----
====

Changes made to entities in the before-save event handler are reflected in the stored entity - after-save ones are not.
