[[reference_programming-auditing]]
=== Auditing

Spring Data Neo4j integrates into the Spring Data auditing infrastructure
to keep track of who created or changed an entity and the point in time this happened.

While Spring Data Neo4j uses the same annotations for auditing as all Spring Data modules do, auditing support itself has to be explicitly enabled.
To enable Spring Data Neo4j's auditing, use `@EnableNeo4jAuditing` on a `@Configuration`-class as shown in <<EnabledAuditing>>.

[source,java]
[[EnabledAuditing]]
.Neo4jConfiguration.java
----
import org.springframework.data.neo4j.annotation.EnableNeo4jAuditing;

@Configuration
@EnableNeo4jAuditing
public class Neo4jConfiguration {}
----

[NOTE]
If you are working with custom ids by setting them directly or using your own `IdStrategy`, the auditing support is limited.
In this case it is not possible for Spring Data Neo4j to figure out if an entity is new or already exists in the database,
because it has an id field set.
As a consequence the fields annotated with `@CreatedBy` and `@CreatedDate` will never get filled.

Please refer to the <<auditing,auditing>> section of the shared Spring Data reference for further details.
