[[reference.getting_started]]
= Getting started

Depending on what type of project you are doing there are several options when it comes to creating a new SDN project:

- Use http://start.spring.io (for Spring Boot projects);
- Use the https://spring.io/tools/sts[Spring Tool Suite (based on eclipse)];
- Adding the required libraries using your dependency management tool.


If you plan on using Neo4j in server mode, you will also need a running instance.  Refer to the Getting Started section of the http://neo4j.com/docs/developer-manual/current/get-started[Neo4j Developer manual] on
how to get that up and running.

== Using Boot

To create a Spring Boot project simply go to http://start.spring.io and specify a group and artifact like: `org.spring.neo4j.example` and `demo`.
In the ***Dependencies*** box type: "Neo4J".  You can also add any other Spring support like "Web" etc. Once you are satisfied with your dependencies
hit the generate button, download the zip and unzip into your workspace.


== Using STS

To create a Spring project in STS go to File → New → Spring Template Project → Simple Spring Utility Project → press Yes when prompted. Then enter a project and a package name such as `org.spring.neo4j.example`.

Then add the following to pom.xml dependencies section.

[source,xml]
----
<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-neo4j</artifactId>
    <version>{version}</version>
  </dependency>

</dependencies>
----

Also change the version of Spring in the pom.xml to be

[source,xml]
----
<spring.framework.version>{springVersion}</spring.framework.version>
----



[[reference.getting_started.dependencies]]
== Using Dependency Management

Spring Data Neo4j projects can be built using Maven, Gradle or any other tool that supports Maven's repository system.

[NOTE]
For more in depth configuration details please consult the Configuration section of the OGM Reference Manual.

[[reference.getting_started.dependencies.maven]]
=== Maven

By default, SDN will use the BOLT driver to connect to Neo4j and you don't need to declare it as a separate dependency in your pom.
If you want to use the embedded or HTTP drivers in your production application, you must add the following dependencies as well.
(This dependency on the embedded driver is not required if you only want to use the embedded driver for testing.
See the section on <<reference.getting_started.dependencies.testing,Testing>> below for more information).



[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-releasetrain</artifactId>
            <version>${spring-data-releasetrain.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>org.springframework.data</groupId>
        <artifactId>spring-data-neo4j</artifactId>
    </dependency>

    <!-- add this dependency if you want to use the embedded driver -->
    <dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-ogm-embedded-driver</artifactId>
    </dependency>

    <!-- add this dependency if you want to use the HTTP driver -->
    <dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-ogm-http-driver</artifactId>
    </dependency>
</dependency>
----


[[reference.getting_started.dependencies.testing]]
==== Testing

.Maven dependencies for testing SDN 5 applications
[source,xml]
----
    <dependency>
        <groupId>org.neo4j.test</groupId>
        <artifactId>neo4j-harness</artifactId>
        <version>3.2.5</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-test</artifactId>
        <version>${spring.version}</version>
        <scope>test</scope>
    </dependency>
----

[NOTE]
====
Using neo4j-harness brings in a dependency on Jetty container.
If you use Spring Boot dependency management the version may be set to an incompatible version.
This may be avoided by overriding `jetty.version` property to a version required by neo4j server.
[source,xml]
----
<properties>
    <!-- version compatible with neo4j 3.3.0 -->
    <jetty.version>9.2.22.v20170606</jetty.version>
</properties>
----

Also having the jetty dependency on classpath might cause your application use jetty as servlet container in your tests
instead of default Tomcat. You can avoid that e.g. by forcing the EmbeddedTomcat autoconfiguration.

[source,java]
----
@SpringBootApplication
// Import tomcat autoconfig to avoid starting Jetty, which is on classpath because of neo4j dependencies
@Import(EmbeddedServletContainerAutoConfiguration.EmbeddedTomcat.class)
----
====

[[reference.getting_started.dependencies.gradle]]
=== Gradle

Gradle dependencies are basically the same as Maven:

[source,groovy]
----
dependencies {
    compile 'org.springframework.data:spring-data-neo4j:{version}'

    # add this dependency if you want to use the embedded driver
    compile 'org.neo4j:neo4j-ogm-embedded-driver:{ogm-version}'

    # add this dependency if you want to use the Http driver
    compile 'org.neo4j:neo4j-ogm-http-driver:{ogm-version}'

}
----

== Examples
There is an https://github.com/spring-projects/spring-data-examples[github repository with several examples] that you can download and play around with to get a feel for how the library works.


[[reference.getting_started.spring-configuration]]
== Configuration

Right now SDN only supports JavaConfig. There is no XML based support but this may change in future.

[NOTE]
For those not familiar with how to configure the Spring container using Java based bean metadata instead of XML based metadata see the high level introduction in the reference docs http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/new-in-3.0.html#new-java-configuration[here] as well as the detailed documentation http://docs.spring.io/spring/docs/4.2.9.RELEASE/spring-framework-reference/html/beans.html#beans-java-instantiating-container[here].


For most applications the following configuration is all that's needed to get up and running.


.Spring Data Neo4j repositories using JavaConfig
[source,java]
----
@Configuration
@EnableNeo4jRepositories(basePackages = "org.neo4j.example.repository")
@EnableTransactionManagement
public class MyConfiguration {

    @Bean
    public SessionFactory sessionFactory() {
        // with domain entity base package(s)
        return new SessionFactory(configuration(), "org.neo4j.example.domain");
    }

    @Bean
    public org.neo4j.ogm.config.Configuration configuration() {
        ConfigurationSource properties = new ClasspathConfigurationSource("ogm.properties");
        org.neo4j.ogm.config.Configuration configuration = new org.neo4j.ogm.config.Configuration.Builder(properties).build();
        return configuration;
    }

    @Bean
    public Neo4jTransactionManager transactionManager() {
        return new Neo4jTransactionManager(sessionFactory());
    }

}
----

Here we wire up a `SessionFactory` configured from defaults.  We can change these defaults by providing an `ogm.properties` file at the root of the
classpath or by passing in a `org.neo4j.ogm.config.Configuration` object.
The last infrastructure component declared here is the  Neo4jTransactionManager. We finally activate Spring Data Neo4j repositories using the @EnableNeo4jRepositories annotation. If no base package is configured it will use the one the configuration class resides in.

Note that you will have to activate `@EnableTransactionManagement` explicitly to get annotation based
configuration at facades working as well as define an instance of this `Neo4jTransactionManager` with the bean name `transactionManager`.
The example above assumes you are using component scanning.

To allow your query methods to be transactional simply use @Transactional at the repository interface you define.


[[reference.getting_started.driver]]
=== Driver Configuration

SDN provides support for connecting to Neo4j using different drivers.

The following drivers are available.

- Http driver
- Embedded driver
- Bolt driver

.Java Configuration

To configure the Driver programmatically, create a Configuration bean and pass it as the first argument to the `SessionFactory` constructor in your Spring configuration:

[source,java]
----
@Bean
public org.neo4j.ogm.config.Configuration configuration() {
    org.neo4j.ogm.config.Configuration configuration = new org.neo4j.ogm.config.Configuration.Builder()
            .uri("bolt://localhost")
            .credentials("user", "secret")
            .build();
    return configuration;
}


@Bean
public SessionFactory sessionFactory() {
    return new SessionFactory(configuration(), <packages> ); <1>
}
----
<1> `packages` is a list of java packages containing the annotated domain model.

Configuration can also be initialized from an external file like this.

[source,java]
----
@Bean
public org.neo4j.ogm.config.Configuration configuration() {
    ConfigurationSource properties = new ClasspathConfigurationSource("db.properties");
    return new org.neo4j.ogm.config.Configuration.Builder(properties).build();
}
----
where `db.properties` looks like
[source,properties]
----
URI=bolt://localhost
username=user
password=secret
connection.pool.size=... #see java driver doc
encryption.level=... #see java driver doc
trust.strategy=... #see java driver doc
trust.certificate.file=... #see java driver doc
connection.liveness.check.timeout=... #see java driver doc
verify.connection=... #see java driver doc
----

//TODO add configuration option with native driver

[NOTE]
The driver is automatically inferred from the URI scheme.

[NOTE]
To set up authentication, TLS or other advanced options please see the Configuration section of the OGM Reference.

[NOTE]
As of 4.2.0 the Neo4j OGM embedded driver no longer ships with the Neo4j kernel. Users are expected to provide this dependency through their dependency management system.



[[reference.getting_started.spring-configuration.boot]]
=== Spring Boot Applications

Spring Boot `2.0` works straight out of the box with Spring Data Neo4j `5.0.0`.

Update your Spring Boot Maven POM with the following.
You may need to add `<repositories>` depending on versioning (when using milestone or snapshot versions).

[source,xml]
----
    ...
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-neo4j</artifactId>
        </dependency>
    </dependencies>
    ...
----

Then add to your Spring Boot configuration class these annotations:

[source,xml]
----
@EnableNeo4jRepositories("com.company.project.repository")
@EntityScan(basePackages = "com.company.project.domain")
----

==== Configuring Events with Boot

When defining a Spring `EventListener`. Simply defining a `@Bean` will automatically register it with the `SessionFactory`.

== Connecting to Neo4j

The `SessionFactory` is needed by SDN to create instances of `org.neo4j.ogm.session.Session` as required.
When constructed, it sets up the object-graph mapping metadata, which is then used across all `Session` objects that it creates.
As seen in the above example, the packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.

There should typically be only one `SessionFactory` per application.

