[[reference.getting_started]]
= Getting started

Depending on what type of project you are doing there are several options when it comes to creating a new SDN project:

- Use http://start.spring.io (for Spring Boot projects);
- Use the https://spring.io/tools/sts[Spring Tool Suite (based on eclipse)];
- Adding the required libraries using your dependency management tool.


If you plan on using Neo4j in server mode, you will also need a running instance.  Refer to the Getting Started section of the http://neo4j.com/docs/developer-manual/current/get-started[Neo4j Developer manual] on
how to get that up and running.

== Using Boot

To create a Spring Boot project simply go to http://start.spring.io and specify a group and artifact like: `org.spring.neo4j.example` and `demo`.
In the ***Dependencies*** box type: "Neo4J".  You can also add any other Spring support like "Web" etc. Once you are satisfied with your dependencies
hit the generate button, download the zip and unzip into your workspace.


== Using STS

To create a Spring project in STS go to File → New → Spring Template Project → Simple Spring Utility Project → press Yes when prompted. Then enter a project and a package name such as `org.spring.neo4j.example`.

Then add the following to pom.xml dependencies section.

[source,xml]
----
<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-neo4j</artifactId>
    <version>{version}</version>
  </dependency>

</dependencies>
----

Also change the version of Spring in the pom.xml to be

[source,xml]
----
<spring.framework.version>{springVersion}</spring.framework.version>
----



[[reference.getting_started.dependencies]]
== Using Dependency Management

Spring Data Neo4j projects can be built using Maven, Gradle or any other tool that supports Maven's repository system.

[NOTE]
For more in depth configuration details please consult the Configuration section of the OGM Reference Manual.

[[reference.getting_started.dependencies.maven]]
=== Maven

By default, SDN will use the BOLT driver to connect to Neo4j and you don't need to declare it as a separate dependency in your pom.
If you want to use the embedded or HTTP drivers in your production application, you must add the following dependencies as well.
(This dependency on the embedded driver is not required if you only want to use the embedded driver for testing. See the section on <<testing,Testing>> below for more information).



[source,xml]
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-neo4j</artifactId>
    <version>{version}</version>
</dependency>

<!-- add this dependency if you want to use the embedded driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-embedded-driver</artifactId>
    <version>{ogm-version}</version>
</dependency>

<!-- add this dependency if you want to use the HTTP driver -->
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-ogm-http-driver</artifactId>
    <version>{ogm-version}</version>
</dependency>
----


[[reference.getting_started.dependencies.testing]]
==== Testing

.Maven dependencies for testing SDN 5 applications
[source,xml]
----
       <dependency>
           <groupId>org.springframework.data</groupId>
           <artifactId>spring-data-neo4j</artifactId>
           <version>${sdn.version}</version>
           <type>test-jar</type>
       </dependency>

       <!-- the neo4j-ogm-test jar provides access to the http and embedded drivers for testing purposes -->
       <dependency>
          <groupId>org.neo4j</groupId>
          <artifactId>neo4j-ogm-test</artifactId>
          <version>${neo4j-ogm.version}</version>
          <type>test-jar</type>
          <scope>test</scope>
      </dependency>

       <dependency>
           <groupId>org.neo4j</groupId>
            <artifactId>neo4j-kernel</artifactId>
            <version>${neo4j.version}</version>
            <type>test-jar</type>
       </dependency>

       <dependency>
            <groupId>org.neo4j.app</groupId>
            <artifactId>neo4j-server</artifactId>
            <version>${neo4j.version}</version>
            <type>test-jar</type>
       </dependency>

      <dependency>
          <groupId>org.neo4j.test</groupId>
          <artifactId>neo4j-harness</artifactId>
          <version>${neo4j.version}</version>
          <scope>test</scope>
      </dependency>
----

[NOTE]
====
The `InProcessServer` has been deprecated. This class was used in previous versions to set up an in-memory Http server so that you could run your tests.
This is no longer appropriate given the new Driver mechanism, and we recommend you configure an Embedded Driver (impermanent data store) for your integration tests instead.
====


[[reference.getting_started.dependencies.gradle]]
=== Gradle

Gradle dependencies are basically the same as Maven:

[source,groovy]
----
dependencies {
    compile 'org.springframework.data:spring-data-neo4j:{version}'

    # add this dependency if you want to use the embedded driver
    compile 'org.neo4j:neo4j-ogm-embedded-driver:{ogm-version}'

    # add this dependency if you want to use the Http driver
    compile 'org.neo4j:neo4j-ogm-http-driver:{ogm-version}'

}
----

== Examples
There is an https://github.com/spring-projects/spring-data-examples[github repository with several examples] that you can download and play around with to get a feel for how the library works.


[[reference.getting_started.spring-configuration]]
== Configuration

Right now SDN only supports JavaConfig. There is no XML based support but this may change in future.

[NOTE]
For those not familiar with how to configure the Spring container using Java based bean metadata instead of XML based metadata see the high level introduction in the reference docs http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/new-in-3.0.html#new-java-configuration[here] as well as the detailed documentation http://docs.spring.io/spring/docs/4.2.9.RELEASE/spring-framework-reference/html/beans.html#beans-java-instantiating-container[here].


For most applications the following configuration is all that's needed to get up and running.


.Spring Data Neo4j repositories using JavaConfig
[source,java]
----
@Configuration
@EnableNeo4jRepositories(basePackages = "org.neo4j.example.repository")
@EnableTransactionManagement
public class MyConfiguration {

    @Bean
    public SessionFactory sessionFactory() {
        // with domain entity base package(s)
        return new SessionFactory("org.neo4j.example.domain");
    }

    @Bean
    public Neo4jTransactionManager transactionManager() {
        return new Neo4jTransactionManager(sessionFactory());
    }

}
----

Here we wire up a `SessionFactory` configured from defaults.  We can change these defaults by providing an `ogm.properties` file at the root of the
classpath or by passing in a `org.neo4j.ogm.config.Configuration` object.
The last infrastructure component declared here is the  Neo4jTransactionManager. We finally activate Spring Data Neo4j repositories using the @EnableNeo4jRepositories annotation. If no base package is configured it will use the one the configuration class resides in.

Note that you will have to activate `@EnableTransactionManagement` explicitly to get annotation based
configuration at facades working as well as define an instance of this `Neo4jTransactionManager` with the bean name `transactionManager`.
The example above assumes you are using component scanning.

To allow your query methods to be transactional simply use @Transactional at the repository interface you define.


[[reference.getting_started.driver]]
=== Driver Configuration

SDN provides support for connecting to Neo4j using different drivers.

The following drivers are available.

- Http driver
- Embedded driver
- Bolt driver

.Java Configuration

To configure the Driver programmatically, create a Configuration bean and pass it as the first argument to the `SessionFactory` constructor in your Spring configuration:

[source,java]
----
@Bean
public org.neo4j.ogm.config.Configuration configuration() {
    org.neo4j.ogm.config.Configuration configuration = new org.neo4j.ogm.config.Configuration.Builder()
            .uri("bolt://localhost")
            .credentials("user", "secret")
            .build();
    return configuration;
}


@Bean
public SessionFactory sessionFactory() {
    return new SessionFactory(configuration(), <packages> ); <1>
}
----
<1> `packages` is a list of java packages containing the annotated domain model.

Configuration can also be initialized from an external file like this.

[source,java]
----
@Bean
public org.neo4j.ogm.config.Configuration configuration() {
    ConfigurationSource properties = new ClasspathConfigurationSource("db.properties");
    org.neo4j.ogm.config.Configuration configuration = new org.neo4j.ogm.config.Configuration.Builder(properties)
    return configuration;
}
----

.Fallback configuration
_Please note that this way of configuration might be removed in the future._

Java configuration is the preferred way of initiallizing SDN. However, if no configuration is given to the `SessionFactory`, SDN
will try to configure the driver from a file `ogm.properties`, which it expects to find on the root of the classpath.

NOTE:   SDN expects the properties file to be called "ogm.properties". If you want to configure your application using a _different_ properties file, you must either set a System property or Environment variable called "ogm.properties" pointing to the alternative configuration file you want to use.

For more detail about this properties file, please refer to the configuration section of the OGM reference.

[NOTE]
The driver is automatically inferred from the URI scheme.

[NOTE]
To set up authentication, TLS or other advanced options please see the Configuration section of the OGM Reference.

[NOTE]
As of 4.2.0 the Neo4j OGM embedded driver no longer ships with the Neo4j kernel. Users are expected to provide this dependency through their dependency management system.



[[reference.getting_started.spring-configuration.boot]]
=== Spring Boot Applications

Spring Boot `2.0` works straight out of the box with Spring Data Neo4j `5.0.0`.

To do that update the Spring Boot properties to use the current SDN version. Update your Spring Boot Maven POM with the following. You may need to add `<repositories>` depending on versioning.

[source,xml]
----
    ...
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-neo4j</artifactId>
        </dependency>
    </dependencies>
    ...
----

==== Configuring Events with Boot

When defining a Spring `EventListener`. Simply defining a `@Bean` will automatically register it with the `SessionFactory`.

== Connecting to Neo4j

The `SessionFactory` is needed by SDN to create instances of `org.neo4j.ogm.session.Session` as required.
When constructed, it sets up the object-graph mapping metadata, which is then used across all `Session` objects that it creates.
As seen in the above example, the packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.

There should typically be only one `SessionFactory` per application.

