[[neo4j.repositories]]
= Neo4J Repositories

[[neo4j-repo-intro]]
== Introduction

This chapter will point out the specialties for repository support for Neo4J and the Neo4J OGM. This builds on the core repository support explained in <<repositories>>. So make sure you've got a sound understanding of the basic concepts explained there.


[[neo4j-repo-config]]
== Configuration

As of SDN 4, this `Neo4jRepository<T>` should be the interface from which your entity repository interfaces inherit, with `T` being specified as the domain entity type to persist.

Examples of methods you get for free out of `Neo4jRepository` are as follows.
For all of these examples the ID parameter is a `Long` that matches the graph ID:

Load an entity instance via an id::
`T findOne(id)`

Check for existence of an id in the graph::
`boolean exists(id)`

Iterate over all nodes of a node entity type::
`Iterable<T> findAll()`
`Iterable<T> findAll(Sort ...)`
`Page<T> findAll(Pageable ...)`

Count the instances of the repository entity type::
`Long count()`

Save entities::
`T save(T)` and `Iterable<T> save(Iterable<T>)`

Delete graph entities::
`void delete(T)`, `void delete(Iterable<T>)`, and `void deleteAll()`


=== GraphRepository (Version 4.0.x - 4.1.x)

`Neo4jRepository` has replaced `GraphRepository` but essentially have the same features. This is only provided for legacy reasons
and has been deprecated.


== Usage

=== Creating repositories

The `Repository` instances are only created through Spring and can be auto-wired into your Spring beans as required.

.Using basic Neo4jRepository CRUD-methods
[source,java]
----
@Repository
public interface PersonRepository extends Neo4jRepository<Person, Long> {}

public class MySpringBean {
   @Autowired
   private PersonRepository repo;
   ...
}

// then you can use the repository as you would any other object
Person michael = repo.save(new Person("Michael", 36));

Person dave = repo.load(123);

long numberOfPeople = repo.count();
----

The recommended way of providing repositories is to define a repository interface per domain class.
The underlying Spring repository infrastructure will automatically detect these repositories, along with additional implementation classes,
and create an injectable repository implementation to be used in services or other spring beans.



[[reference_programming-model_repositories]]
=== CRUD with repositories

The repositories provided by Spring Data Neo4j build on the composable repository infrastructure in http://static.springsource.org/spring-data/data-commons/docs/current/reference/html/#repositories[Spring Data Commons].
These allow for interface-based composition of repositories consisting of provided default implementations for certain interfaces and additional custom implementations for other methods.

Spring Data Neo4j comes with a single `org.springframework.data.repository.PagingAndSortingRepository` specialisation called
`Neo4jRepository<T>` used for all object-graph mapping repositories.
This sub-interface also adds specific finder methods that take a _depth_ argument to control the horizon with which related entities are fetched and saved.
Generally, it provides all the desired repository methods.
If other operations are required then the additional repository interfaces should be added to the individual interface declaration.

[NOTE]
====
`Neo4jRepository` no longer combines `IndexRepository` and `TraversalRepository` because, for reasons explained
earlier, these features are no longer supported in Spring Data Neo4j as of version 4.
====


== Query Methods


=== Query and Finder Methods

Most of the data access operations you usually trigger on a repository result a query being executed against the Neo4j database. Defining such a query is just a matter of declaring a method on the repository interface

.PersonRepository with query methods
====
[source,java]
----
public interface PersonRepository extends PagingAndSortingRepository<Person, String> {

    List<Person> findByLastname(String lastname);                      <1>

    Page<Person> findByFirstname(String firstname, Pageable pageable); <2>

    Person findByShippingAddresses(Address address);                   <3>

    Stream<Person> findAllBy();                                        <4>
}
----
<1> The method shows a query for all people with the given lastname. The query will be derived parsing the method name for constraints which can be concatenated with `And` and `Or`. Thus the method name will result in a query expression of `{"lastname" : lastname}`.
<2> Applies pagination to a query. Just equip your method signature with a `Pageable` parameter and let the method return a `Page` instance and we will automatically page the query accordingly.
<3> Shows that you can query based on properties which are not a primitive type.
<4> Uses a Java 8 `Stream` which reads and converts individual elements while iterating the stream.
====



[cols="1,2,3", options="header"]
.Supported keywords for query methods
|===============
|Logical keyword|Keyword expressions|Restrictions
|`AND`|`And`|
|`OR`|`Or`|Cannot be used to OR nested properties
|`GREATER_THAN`|`GreaterThan`, `IsGreaterThan`|
|`LESS_THAN`|`LessThan`, `IsLessThan`|
|`LIKE`|`Like`, `IsLike`|
|`NOT`|`Not`, `IsNot`|
|`NOT_LIKE`|`NotLike`, `IsNotLike`|
|`REGEX`|`Regex`, `MatchesRegex`, `Matches`|
|`NEAR`|`Near`, `IsNear`|
|===============


[[reference_programming_model_annotatedQueries]]
=== Annotated queries

Queries using the Cypher graph query language can be supplied with the `@Query` annotation.

That means a repository method annotated with +
`@Query("MATCH (:Actor {name:{name}})-[:ACTED_IN]->(m:Movie) return m")` +
will use the supplied query query to retrieve data from Neo4j.

The named or indexed parameter `{param}` will be substituted by the actual method parameter.
Node and Relationship-Entities are handled directly and converted into their respective ids.
All other parameters types are provided directly (i.e. Strings, Longs, etc).

There is special support for the Pageable parameter from Spring Data Commons, which is supported to add programmatic paging and slicing(alternatively static paging and sorting can be supplied in the query string itself).

If it is required that paged results return the correct total count, the @Query annotation can be supplied with a count query in the countQuery attribute.
This query is executed separately after the result query and its result is used to populate the number of elements on the Page.

[NOTE]
====
Custom queries do not support a custom depth.
Additionally, `@Query` does not support mapping a path to domain entities, as such, a path should not be returned from a Cypher query.
Instead, return nodes and relationships to have them mapped to domain entities.
====

=== Query results

Typical results for queries are `Iterable<Type>`, `Iterable<Map<String,Object>>` or simply `Type`.
Nodes and relationships are converted to their respective entities (if they exist).
Other values are converted using the registered <<reference_programming-model_conversion,conversion services>> (e.g. enums).

=== Cypher examples

`MATCH (n) WHERE id(n)=9 RETURN n`::
returns the node with id 9

`MATCH (movie:Movie {title:'Matrix'}) RETURN movie`::
returns the nodes which are indexed with title equal to 'Matrix'

`MATCH (movie:Movie {title:'Matrix'})<-[:ACTS_IN]-(actor) RETURN actor.name`::
returns the names of the actors that have a ACTS_IN relationship to the movie node for 'Matrix'

`MATCH (movie:Movie {title:'Matrix'})<-[r:RATED]-(user) WHERE r.stars > 3 RETURN user.name, r.stars, r.comment`::
returns users names and their ratings (>3) of the movie titled 'Matrix'

`MATCH (user:User {name='Michael'})-[:FRIEND]-(friend)-[r:RATED]->(movie) RETURN movie.title, AVG(r.stars), COUNT(\*) ORDER BY AVG(r.stars) DESC, COUNT(*) DESC`::
returns the movies rated by the friends of the user 'Michael', aggregated by `movie.title`, with averaged ratings and rating-counts sorted by both

Examples of Cypher queries placed on repository methods with @Query where values are replaced with method parameters,
as described in the <<reference_programming_model_annotatedQueries>>) section.

[source,java]
----
public interface MovieRepository extends Neo4jRepository<Movie> {

    // returns the node with id equal to idOfMovie parameter
    @Query("MATCH (n) WHERE id(n)={0} RETURN n")
    Movie getMovieFromId(Integer idOfMovie);

    // returns the nodes which have a title according to the movieTitle parameter
    @Query("MATCH (movie:Movie {title={0}}) RETURN movie")
    Movie getMovieFromTitle(String movieTitle);

	// returns a Page of Actors that have a ACTS_IN relationship to the movie node with the title equal to movieTitle parameter.
	@Query("MATCH (movie:Movie {title={0}})<-[:ACTS_IN]-(actor) RETURN actor")
	Page<Actor> getActorsThatActInMovieFromTitle(String movieTitle, PageRequest page);

    // returns a Page of Actors that have a ACTS_IN relationship to the movie node with the title equal to movieTitle parameter with an accurate total count
	@Query("MATCH (movie:Movie {title={0}})<-[:ACTS_IN]-(actor) RETURN actor", countQuery = "MATCH (movie:Movie {title={0}})<-[:ACTS_IN]-(actor) RETURN count(*)")
	Page<Actor> getActorsThatActInMovieFromTitle(String movieTitle, Pageable page);

    // returns a Slice of Actors that have a ACTS_IN relationship to the movie node with the title equal to movieTitle parameter.
	@Query("MATCH (movie:Movie {title={0}})<-[:ACTS_IN]-(actor) RETURN actor")
	Slice<Actor> getActorsThatActInMovieFromTitle(String movieTitle, Pageable page);

    // returns users who rated a movie (movie parameter) higher than rating (rating parameter)
    @Query("MATCH (movie:Movie)<-[r:RATED]-(user) " +
           "WHERE id(movie)={movieId} AND r.stars > {rating} " +
           "RETURN user")
    Iterable<User> getUsersWhoRatedMovieFromTitle(@Param("movieId") Movie movie, @Param("rating") Integer rating);

    // returns users who rated a movie based on movie title (movieTitle parameter) higher than rating (rating parameter)
    @Query("MATCH (movie:Movie {title:{0}})<-[r:RATED]-(user) " +
           "WHERE r.stars > {1} " +
           "RETURN user")
     Iterable<User> getUsersWhoRatedMovieFromTitle(String movieTitle, Integer rating);
}
----

=== Queries derived from finder-method names

Using the metadata infrastructure in the underlying object-graph mapper, a finder method name can be split into its semantic parts and converted into a cypher query.
Navigation along relationships will be reflected in the generated `MATCH` clause and properties with operators will end up as expressions in the `WHERE` clause.
The parameters will be used in the order they appear in the method signature so they should align with the expressions stated in the method name.

.Some examples of methods and corresponding Cypher queries of a PersonRepository
[source,java]
----
public interface PersonRepository extends Neo4jRepository<Person> {

    // MATCH (person:Person {name={0}}) RETURN person
    Person findByName(String name);

    // MATCH (person:Person)
    // WHERE person.age = {0} AND person.married = {1}
    // RETURN person
    Iterable<Person> findByAgeAndMarried(int age, boolean married);

    // MATCH (person:Person)
    // WHERE person.age = {0}
    // RETURN person ORDER BY person.name SKIP {skip} LIMIT {limit}
    Page<Person> findByAge(int age, Pageable pageable);

    // MATCH (person:Person)
    // WHERE person.age = {0}
    // RETURN person ORDER BY person.name
    List<Person> findByAge(int age, Sort sort);

    //Allow a custom depth as a parameter
    Person findByName(String name, @Depth int depth);

    //Fix the depth for the query
    @Depth(value = 0)
    Person findBySurname(String surname);

}
----


[[reference_programming-model_mapresult]]
=== Mapping Query Results

For queries executed via `@Query` repository methods, it's possible to specify a conversion of complex query results to POJOs. These result objects are then populated with the query result data and can be serialized and sent to a different part of the application, e.g. a frontend-ui.  To take advantage of this feature, use a class annotated with `@QueryResult` as the method return type.

.Example of query result mapping
[source,java]
----
public interface MovieRepository extends GraphRepository<Movie> {

    @Query("MATCH (movie:Movie)-[r:RATING]->(), (movie)<-[:ACTS_IN]-(actor:Actor) " +
           "WHERE movie.id={0} " +
           "RETURN movie as movie, COLLECT(actor) AS 'cast', AVG(r.stars) AS 'averageRating'")
    MovieData getMovieData(String movieId);

    @QueryResult
    public class MovieData {
        Movie movie;
        Double averageRating;
        Set<Actor> cast;
    }

}
----

[[reference_programming-model_sorting_and_paging]]
=== Sorting and Paging
Spring Data Neo4j supports sorting and paging of results when using Spring Data's `Pageable` and `Sort` interfaces.

====
.Repository-based paging
[source,java]
----
Pageable pageable = new PageRequest(0, 3);
Page<World> page = worldRepository.findAll(pageable, 0);
----

.Repository-based sorting
[source,java]
----
Sort sort = new Sort(Sort.Direction.ASC, "name");
Iterable<World> worlds = worldRepository.findAll(sort, 0)) {
----

.Repository-based sorting with paging
[source,java]
----
Pageable pageable = new PageRequest(0, 3, Sort.Direction.ASC, "name");
Page<World> page = worldRepository.findAll(pageable, 0);
----
====

[NOTE]
====
The total number of pages reported by the `PagingAndSortingRepository` `findAll` methods are estimates and should not be relied upon for accuracy
====


== Miscellaneous

=== JSR-303 (Bean Validation) Support

Spring Data Neo4J allows developers to use JSR-303 annotations like `@NotNull` etc. on their domain models.
While this is provided it's not a best practice. It is highly recommended to create JSR-303 annotations on actual Java Beans,
similar to things like Data Transfer Objects (DTOs).

=== Conversion Service
It is possible to have Spring Data Neo4j 4 use converters registered with http://docs.spring.io/spring/docs/current/spring-framework-reference/html/validation.html#core-convert[Spring's ConversionService].
In order to do this, provide `org.springframework.data.neo4j.conversion.MetaDataDrivenConversionService` as a Spring bean.

.Provide MetaDataDrivenConversionService as a Spring bean
[source,java]
----
@Bean
public ConversionService conversionService() {
    return new MetaDataDrivenConversionService(getSessionFactory().metaData());
}
----

Then, instead of defining an implementation of `org.neo4j.ogm.typeconversion.AttributeConverter` on the `@Convert` annotation,
use the `graphPropertyType` attribute to define the type to convert to.

.Using graphPropertyType
[source,java]
----
@NodeEntity
public class MyEntity {

    @Convert(graphPropertyType = Integer.class)
    private DecimalCurrencyAmount fundValue;

}
----

Spring Data Neo4j 4 will look for converters registered with Spring's ConversionService that can convert
both to and from the type specified by `graphPropertyType` and use them if they exist.

[NOTE]
====
Default converters and those defined explicitly via an implementation of `org.neo4j.ogm.typeconversion.AttributeConverter`
will take precedence over converters registered with Spring's ConversionService.
====


=== CDI integration

Instances of the repository interfaces are usually created by a container, which Spring is the most natural choice when working with Spring Data. There's sophisticated support to easily set up Spring to create bean instances documented in <<repositories.create-instances>>. As of version 4.1.5 Spring Data Neo4j ships with a custom CDI extension that allows using the repository abstraction in CDI environments. The extension is part of the JAR so all you need to do to activate it is dropping the Spring Data Neo4j JAR into your classpath.

You can now set up the infrastructure by implementing a CDI Producer for the `SessionFactory` and `Session`:

[source, java]
----
class sessionFactoryProducer {

  @Produces
  @ApplicationScoped
  public SessionFactory createSessionFactory() {
    return new SessionFactory("package");
  }

  public void close(@Disposes SessionFactory sessionFactory) {
    sessionFactory.close();
  }
}
----

The necessary setup can vary depending on the JavaEE environment you run in. It might also just be enough to redeclare a `session` as CDI bean as follows:

[source, java]
----
class CdiConfig {

  @Produces
  @RequestScoped
  @PersistenceContext
  public session session;
}
----

In this example, the container has to be capable of creating OGM `Sessions` itself. All the configuration does is re-exporting the OGM `Session` as CDI bean.

The Spring Data Neo4J CDI extension will pick up all sessions availables as CDI beans and create a proxy for a Spring Data repository whenever an bean of a repository type is requested by the container. Thus obtaining an instance of a Spring Data repository is a matter of declaring an `@Injected` property:

[source, java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----










