[[reference.ogm-support]]
= Neo4j OGM Support


To get started, you need only your domain model and the annotations provided by the OGM library.
You use annotations to mark domain objects to be reflected by nodes and relationships of the graph database.
For individual fields the annotations allow you to declare how they should be processed and mapped to the graph.
For property fields and references to other entities this is straightforward.

Refer to the OGM documentation for more details.


[[introduction-graph-database]]
== What is an OGM?

An OGM (Object Graph Mapper) maps nodes and relationships in the graph to objects and references in your domain model.
Object instances are mapped to nodes while object references are mapped using relationships, or serialized to properties (e.g. references to a Date).
JVM primitives are mapped to node or relationship properties.
An OGM abstracts the database and provides a convenient way to persist your domain model in the graph and query it without using low level drivers.
It also provides the flexibility to the developer to supply custom queries where the queries generated by the OGM are insufficient.

The OGM can be thought of as analogous to Hibernate or JPA. It is expected users have a working understanding of the OGM when using this guide.


[WARNING]
`Session` now replaces `Neo4jTemplate` functionality as all functionality can be found on the OGM `Session` object.

SDN now allows you to wire up the OGM `Session` directly into your Spring managed beans.

While SDN `Repository` will cover a majority of user scenarios sometimes it doesn't offer enough options. The OGM's `Session` offers a convenient API to interact more tightly with a Neo4j graph database.

[[reference.architecture.session]]
=== Understanding the Session

A `Session` is used to drive the object-graph mapping framework. All repository implementations are driven by the `Session`.
It keeps track of the changes that have been made to entities and their relationships.
The reason it does this is so that only entities and relationships that have changed get persisted on save, which is particularly efficient when working with large graphs.


Sessions are usually bound to a thread by default and rely on the garbage collector to clean it up once it is out of scope of processing.
For most users this means there is nothing to configure.
Request/response type applications SDN will take care of Session management for you (as defined in the Configuration section above).
If you have a batch or long running desktop type application you may want to know how you can control using the session a bit more.

.Design Consideration: Session caching
****
Once an entity is tracked by the session, reloading this entity within the scope of the same session will result in the session cache
returning the previously loaded entity. However, the subgraph in the session will expand if the entity or its related
entities retrieve additional relationships from the graph.

If you want to fetch fresh data from the graph, then this can be achieved by using a new session or clearing the current
sessions context using `org.neo4j.ogm.session.Session.clear()`.

The lifetime of the `Session` can be managed in code. For example, associated with single _fetch-update-save_ cycle or unit of work.

If your application relies on long-running sessions then you may not see changes made from other users and find yourself working with outdated objects.
On the other hand, if your sessions have too narrow a scope then your save operations can be unnecessarily expensive, as updates will be made to all objects if the session isn't aware of the those that were originally loaded.

There's therefore a trade off between the two approaches.
In general, the scope of a `Session` should correspond to a "unit of work" in your application.
****

== Basic Operations

For Spring Data Neo4j, low level operations are handled by the OGM `Session`.
Basic operations are now entirely limited to CRUD operations on entities and executing arbitrary Cypher queries; more low-level manipulation of the graph database is not possible.

[NOTE]
There is no longer a way to manipulate relationship- and node-objects directly.

Given that the latest version of the framework is driven by Cypher queries alone, there's no way to work directly with `Node` and `Relationship` objects any more in remote server mode.
Similarly, the `traverse()` method has disappeared, again because the underlying query-driven model doesn't handle it in an efficient way.

If you find yourself in trouble because of the omission of these features, then your best options are:

. Write a Cypher query to perform the operations on the nodes/relationships instead
. Write a Neo4j server extension and call it over REST from your application

Of course, there are pros and cons to both of these approaches, but these are largely outside the scope of this document.
In general, for low-level, very high-performance operations like complex graph traversals you'll get the best performance by writing a server-side extension.
For most purposes, though, Cypher will be performant and expressive enough to perform the operations that you need.

== Entity Persistence

`Session` allows you to `save`, `load`, `loadAll` and `delete` entities.
The eagerness with which objects are retrieved is controlled by specifying the 'depth' argument to any of the load methods.

All of these basic CRUD methods just call onto the underlying methods of `Session`, albeit with transaction handling and exception translation managed for you by SDN's Transaction Manager bean.

== Cypher Queries

The `Session` also allows execution of arbitrary Cypher queries via its `query`, `queryForObject` and `queryForObjects` methods.
Cypher queries that return tabular results should be passed into the `query` method.
An `org.neo4j.ogm.session.result.Result` is returned. This consists of `org.neo4j.ogm.session.result.QueryStatistics` representing statistics of
modifying cypher statements if applicable, and an `Iterable<Map<String,Object>>` containing the raw data, of which nodes and relationships are mapped to domain entities if possible.
The keys in each `Map` correspond to the names listed in the return clause of the executed Cypher query.

//For the query methods that retrieve mapped objects, the recommended query format is to return a path, which should ensure that known types get mapped correctly and joined together with relationships as appropriate.
[NOTE]
Modifications made to the graph via Cypher queries directly will not be reflected in your domain objects within the session.


== Transactions

If you configured the `Neo4jTransactionManager` bean, any `Session` that is managed by Spring will automatically take part in Thread contextual Transactions.
In order to do this you will need to wrap your service code using `@Transactional` or the `TransactionTemplate`.

[NOTE]
It is important to know that if you enable Transactions *ALL* code that uses the `Session` or a `Repository` must be enclosed in a `@Transactional` annotation.

For more details see <<reference_programming-model_transactions,Transactions>>
