[abstract]
--
This reference guide covers information about the programming model, APIs, concepts, annotations and technical details of
Spring Data Neo4j.
--

[[reference.overview]]
= Overview

For version 4.0, Spring Data Neo4j was rewritten from scratch to natively support Neo4j deployments in standalone server mode.
It uses Cypher, the Neo4j query language, and the HTTP protocol to communicate with the database.
It's therefore worth noting that there *will be backward compatibility issues* when migrating to version 4.x, so be sure to check the <<migration,Migration Guide>> to avoid any unwanted surprises.

Version 4.1 introduced support for connecting to an embedded instance of Neo4j and connecting to a remote instance using the Bolt protocol introduced by Neo4j 3.0.
Version 4.2 introduces an updated developer API more akin to other Spring Data Projects.

The explanation of Spring Data Neo4j's programming model starts with some underlying details.
The basic concepts of the http://neo4j.com/docs/ogm-manual/current/[OGM library] used by Spring Data Neo4j internally, is explained in the initial chapter.


[[introduction-graph-database]]
== What is an OGM?

An OGM (Object Graph Mapper) maps nodes and relationships in the graph to objects and references in your domain model.
Object instances are mapped to nodes while object references are mapped using relationships, or serialized to properties (e.g. references to a Date).
JVM primitives are mapped to node or relationship properties.
An OGM abstracts the database and provides a convenient way to persist your domain model in the graph and query it without using low level drivers.
It also provides the flexibility to the developer to supply custom queries where the queries generated by the OGM are insufficient.

The OGM can be thought of as analogous to Hibernate or JPA. It is expected users have a working understanding of the OGM when using this guide.

[[reference.overview.features]]
== SDN Key Features

Below you'll find a quick run down of the main features SDN provides.

=== Repositories

Spring Data Commons provides a very powerful repository infrastructure that is also leveraged in Spring Data Neo4j.
Those repositories consist of a composition of interfaces that declare the available functionality in each repository.
The implementation details of commonly-used persistence methods are handled by the library, which makes them very convenient for typical CRUD and query operations.
The repositories are extensible by annotated, named or derived finder methods (like in (G)Rails).
For custom implementations of repository methods you are free to add your own code. (<<reference_programming-model_repositories,CRUD with repositories>>).

=== Sessions

Spring Data Neo4j supports the usage of OGM <<reference.architecture.session,Session>>s for interacting with the mapped entities and the Neo4j graph database if you don't want to use repositories.
Support for Spring Data Neo4j Repositories is also based on the `Session`, so the underlying functionality is identical.

=== Transactional Support

Neo4j uses transactions to guarantee the integrity of your data and Spring Data Neo4j supports this fully.
The implications of this are described in the chapter around <<reference_programming-model_transactions>>.

=== Configuration

Currently, only JavaConfig configuration is supported. XML based configuration has experimental support.  See <<reference.getting_started.spring-configuration>> for more details.

=== Performance

Spring Data Neo4j 4 has been rebuilt from the ground up with performance in mind.
More information can be found in <<reference_performance,Performance Considerations>>.


