This reference guide covers information about the programming model, APIs, concepts, annotations and technical details of
Spring Data Neo4j Version 4.2.

[[reference.overview]]
= Overview

For version 4.0, Spring Data Neo4j was rewritten from scratch to natively support Neo4j deployments in standalone server mode.
It uses Cypher, the Neo4j query language, and the HTTP protocol to communicate with the database.
It's therefore worth noting that there *will be backward compatibility issues* when migrating to version 4.x, so be sure to check the <<migration,Migration Guide>> to avoid any unwanted surprises.

Version 4.1 introduced support for connecting to an embedded instance of Neo4j and connecting to a remote instance using the Bolt protocol introduced by Neo4j 3.0.
Version 4.2 introduces an updated developer API more akin to other Spring Data Projects.

For integration of Neo4j and other languages, please see http://neo4j.com/developer/language-guides/[Language Guides].

The explanation of Spring Data Neo4j's programming model starts with some underlying details.
The basic concepts of the http://neo4j.com/docs/ogm-manual/current/ (OGM) library] used by Spring Data Neo4j internally, is explained in the initial chapter.

[[reference.overview.features]]
== Features

Below you'll find a quick run down of the main features SDN provides.

=== Adding Neo4j Graph Queries

To use advanced functionality like Cypher queries, a basic understanding of the graph data model is required.
The graph data model is explained in the chapter about Neo4j, see <<neo4j>>.

=== Managing Relationships

Relationships between entities are first class citizens in a graph database and therefore worth a separate chapter
(<<reference_programming-model_relationships>>) describing their usage in Spring Data Neo4j.

=== Repositories

Spring Data Commons provides a very powerful repository infrastructure that is also leveraged in Spring Data Neo4j.
Those repositories consist of a composition of interfaces that declare the available functionality in each repository.
The implementation details of commonly-used persistence methods are handled by the library, which makes them very convenient for typical CRUD and query operations.
The repositories are extensible by annotated, named or derived finder methods (like in (G)Rails).
For custom implementations of repository methods you are free to add your own code. (<<reference_programming-model_repositories,CRUD with repositories>>).

=== Sessions

Spring Data Neo4j supports the usage of OGM <<reference.architecture.session,Session>>s for interacting with the mapped entities and the Neo4j graph database if you don't want to use repositories.
Support for Spring Data Neo4j Repositories is also based on the `Session`, so the underlying functionality is identical.


=== Mapping Strategies

Because Neo4j is a schema-free database, Spring Data Neo4j uses a simple mechanism to map Java types to Neo4j nodes using labels.
How that works is explained here: <<reference_programming-model_simple-mapping,Simplified Object Graph Mapping>>.

=== Transactional Support

Neo4j uses transactions to guarantee the integrity of your data and Spring Data Neo4j supports this fully.
The implications of this are described in the chapter around <<reference_programming-model_transactions>>.

=== Configuration

Currently, only JavaConfig configuration is supported. XML based configuration has experimental support.  See <<reference.getting_started.spring-configuration>> for more details.

=== Performance

Spring Data Neo4j 4 has been rebuilt from the ground up with performance in mind.
More information can be found in <<reference_performance,Performance Considerations>>.

[[reference.overview.getting-help]]
== Getting Help

If you encounter issues or you are just looking for advice, feel free to use one of the links below:

To learn more refer to:

* the http://static.springsource.org/spring-data/data-neo4j/docs/current/reference/html/[Reference Manual];
* the https://github.com/neo4j-examples/sdn4-university/tree/4.1[sample project: SDN Univeristy].  More example projects for Spring Data Neo4j 4 are available in the https://github.com/neo4j-examples?query=sdn4[Neo4j-Examples] repository
* The main http://projects.spring.io/spring-data-neo4j[SpringSource project site] contains links to basic project information such as source code, JavaDocs, Issue tracking, etc.
* the http://docs.spring.io/spring-data/neo4j/docs/current/api[Javadocs];
* for more detailed questions, use http://stackoverflow.com/questions/tagged/spring-data-neo4j-4[Spring Data Neo4j on StackOverflow]

If you are new to Spring as well as to Spring Data, look for information about http://www.springsource.org/projects[Spring projects].

[[reference.overview.feedback]]
== Got feedback?

Whenever you look for the means to employ the full power of the Spring Data Neo4j library, you should be able to find
your answers in this document.
Hopefully we've created a guide that is well-received by our peers in the development community but sometimes things aren't
detailed enough or have enough documentation. We are a very quick turnaround development team so if you don't see what, please inform us about missing or incorrect content.


If you have any feedback on Spring Data Neo4j or this book, please provide it via:

* https://jira.spring.io/browse/DATAGRAPH[SpringSource JIRA]
* http://stackoverflow.com/questions/tagged/spring-data-neo4j[StackOverflow]
* http://groups.google.com/group/neo4j[The Neo4j Google Group].

