[[reference_programming-projections]]
=== Projections

Spring Data Repositories usually return the domain model when using query methods. However, sometimes, you may need to alter the view of that model for various reasons. In this section, you will learn how to define projections to serve up simplified and reduced views of resources.

Look at the following domain model:

[source,java]
----
@NodeEntity
public class Cinema {

  private Long id;
  private String name, location;

  @Relationship(type = "VISITED", direction = Relationship.INCOMING)
  private Set<User> visited = new HashSet<>();

  @Relationship(type = "BLOCKBUSTER", direction = Relationship.OUTGOING)
  private Movie blockbusterOfTheWeek;
  …
}
----

This `Cinema` has several attributes:

* `id` is the graph id
* `name` and `location` are data attributes
* `visited` and `blockbusterOfTheWeek` are links to other domain objects

Now assume we create a corresponding repository as follows:

[source,java]
----
public interface CinemaRepository extends Neo4jRepository<Cinema, Long> {

  Cinema findByName(String name);
}
----

Spring Data will return the domain object including all of its attributes, including all the users that visited this cinema. That can be a big amount of data and can lead to performance issues.

There are several ways to avoid that :

* use a custom `depth` for loading (see <<reference_derived-queries>>)
* use a custom annotated query (see <<reference_programming_model_annotatedQueries>>)
* use a projection

.Simple Projection
====
[source,java]
----
public interface CinemaNameAndBlockbuster {  <1>

	public String getName(); <2>
	public Movie getBlockbusterOfTheWeek();
}
----
This projection has the following details:

<1> A plain Java interface making it declarative.
<2> Only some attributes of the entity are exported.
====

The `CinemaNameAndBlockbuster` projection only has getters for `name` and `blockbusterOfTheWeek` meaning that it will not serve up any user information. The query method definition returns in this case `CinemaNameAndBlockbuster` instead of `Cinema`.

[source,java]
----
interface CinemaRepository extends Neo4jRepository<Cinema, Long> {

  CinemaNameAndBlockbuster findByName(String name);
}
----

Projections declare a contract between the underlying type and the method signatures related to the exposed properties. Hence it is required to name getter methods according to the property name of the underlying type. If the underlying property is named `name`, then the getter method must be named `getName` otherwise Spring Data is not able to look up the source property.
This type of projection is also called _closed projection_.

NOTE: Closed projections expose a subset of properties that could be used to optimize the query in a way to reduce the selected fields from the data store. However, it is not implemented at the moment. For performance sensitive querying, you can still use custom queries with maps or `QueryResult` (see <<reference_programming-model_mapresult>>)

The other type is, as you might imagine, an _open projection_.

[[projections.remodelling-data]]
==== Remodelling data

So far, you have seen how projections can be used to reduce the information that is presented to the user. Projections can be used to adjust the exposed data model. You can add virtual properties to your projection. Look at the following projection interface:

.Renaming a property
====
[source,java]
----
interface RenamedProperty {    <1>

  @Value("#{target.name}")
  String getCinemaName();       <2>

  @Value("#{target.blockbusterOfTheWeek.name}")
  String getBlockbusterOfTheWeekName();            <3>
}
----
This projection has the following details:

<1> A plain Java interface making it declarative.
<2> Expose the `name` attribute as a virtual property called `cinemaName`.
<3> Export the `name` sub-property of the linked `Movie` entity as a virtual property.
====

The backing domain model does not have these properties so we need to tell Spring Data from where they are obtained.
Virtual properties are the place where `@Value` comes into play. The `cinemaName` getter is annotated with `@Value` to use https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[SpEL expressions] pointing to the backing property `name`. You may have noticed `name` is prefixed with `target` which is the variable name pointing to the backing object. Using `@Value` on methods allows defining where and how the value is obtained.

`@Value` gives full access to the target object and its nested properties. SpEL expressions are extremely powerful as the definition is always applied to the projection method.

We could imagine this :

[source,java]
----
interface RenamedProperty {

  @Value("#{target.name} #{(target.location == null) ? '' : target.location}")
  String getNameAndLocation();
}
----

In this example, the location is appended to the cinema name only if it is available.