[[reference.releasetrain]]
= Spring Data Release Train Dependencies

Due to different inception dates of individual Spring Data modules, most of them carry different major and minor version numbers. The easiest way to find compatible ones is by relying on the Spring Data Release Train BOM we ship with the compatible versions defined. In a Maven project you'd declare this dependency in the `<dependencyManagement />` section of your POM:

.Using the Spring Data release train BOM
====
[source, xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-releasetrain</artifactId>
      <version>${release-train}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>
----
====

[[reference.releasetrain.train-names]]
The current release train version is `Ingalls-M1`. The train names are ascending alphabetically and currently available ones are listed https://github.com/spring-projects/spring-data-commons/wiki/Release-planning[here]. The version name follows the following pattern: `${name}-${release}` where release can be one of the following:

* `BUILD-SNAPSHOT` - current snapshots
* `M1`, `M2` etc. - milestones
* `RC1`, `RC2` etc. - release candidates
* `RELEASE` - GA release
* `SR1`, `SR2` etc. - service releases

A working example of using the BOMs can be found in our https://github.com/spring-projects/spring-data-examples/tree/master/bom[Spring Data examples repository]. If that's in place declare the Spring Data modules you'd like to use without a version in the `<dependencies />` block.

.Declaring a dependency to a Spring Data module
====
[source, xml]
----
<dependencies>
  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-neo4j</artifactId>
  </dependency>
<dependencies>
----
====

[[reference.releasetrain.spring-boot]]
== Dependency management with Spring Boot

Spring Boot already selects a very recent version of Spring Data modules for you. In case you want to upgrade to a newer version nonetheless, simply configure the property `spring-data-releasetrain.version` to the train name and iteration you'd like to use.

To override the version of the OGM that you want to use configure the property `neo4j-ogm.version`.

[[reference.releasetrain.spring-framework]]
== Spring Framework

The current version of Spring Data modules require Spring Framework in version {springVersion} or better. The modules might also work with an older bugfix version of that minor version. However, using the most recent version within that generation is highly recommended.
