[[reference_setup]]
= Getting started

Spring Data Neo4j dramatically simplifies development, but some setup is naturally required.
For building the application, your build automation tool needs to be configured to include the Spring Data Neo4j dependencies and after the build setup is complete, the Spring application needs to be configured to make use of Spring Data Neo4j.
Examples for these different setups can be found in the http://github.com/neo4j-examples[Spring Data Neo4j examples].

Spring Data Neo4j projects can be built using Maven, Gradle or Ant/Ivy.

== Dependencies for Spring Data Neo4j

.Maven dependencies for Spring Data Neo4j
[source,xml]
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-neo4j</artifactId>
    <version>{version}</version>
</dependency>
----

.Gradle dependencies for Neo4j OGM
[source,xml]
----
dependencies {
    compile 'org.springframework.data:spring-data-neo4j:{version}'
}
----

.Ivy dependencies for Neo4j OGM
[source,xml]
----
<dependency org="org.springframework.data" name="spring-data-neo4j" rev="{version}"/>
----

== Spring configuration

Users of Spring Data Neo4j 4 can currently only configure their applications using Java-based bean configuration.
Support for XML namespace configuration is expected to be available in later versions.

=== Java-based bean configuration

In order to configure Spring Data Neo4j with Java-based bean config, your Spring context must extend the core `Neo4jConfiguration` class that comes with Spring Data Neo4j. 
The example below shows how this can be done.

NOTE:   You will need to override `getSessionFactory()` and `getSession()` bean definitions to provide
the required context for your own application. This is explained in more detail below.

.Pure Java Configuration
[source,java]
----
@Configuration
@EnableNeo4jRepositories(basePackages = "org.neo4j.example.repository")
@EnableTransactionManagement
public class MyConfiguration extends Neo4jConfiguration {

    @Bean
    public SessionFactory getSessionFactory() {
        // with domain entity base package(s)
        return new SessionFactory("org.neo4j.example.domain");
    }

    // needed for session in view in web-applications
    @Bean
    @Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
    public Session getSession() throws Exception {
        return super.getSession();
    }

}
----

== Drivers

As of 4.1, Spring Data Neo4j provides suppport for connecting to Neo4j using different drivers. As a result, the `RemoteServer` and `InProcessServer` classes should not be used, and are no longer directly supported in the configuration. The following drivers are available.

- Http driver
- Embedded driver

There are two basic ways to do this: using a single properties file, or programmatically.

=== Properties file

Unless you supply an explicit Configuration object to the SessionFactory (see Java Configuration, below), Spring Data Neo4j will attempt to auto-configure itself using a file called `ogm.properties`, which it expects to find on the classpath.

If you want to configure your application using a _different_ properties file, you must either set a System property or Environment variable called 'ogm.properties' pointing to the alternative configuration file you want to use.

=== Java Configuration

In many cases you won't want to, or will not be able to provide configuration information via a properties file.
In these cases you can configure your application programmatically instead.

The following sections describe how to configure Spring Data Neo4j using either a properties file or via Java Configuration.

==== Configuring the Http Driver

The Http Driver connects to and communicates with a Neo4j server over Http. An Http Driver must be used if your application is running in client-server mode. Please note the Http Driver can't be used for spinning up an in-process server.
The Http Driver is the default driver for SDN 4.1, and doesn't need to be explicitly declared in your pom file.

.Properties file

```
driver=org.neo4j.ogm.drivers.http.driver.HttpDriver
URI=http://user:password@localhost:7474
```

.Java Configuration

The simplest way to configure the Driver is to create a Configuration bean and pass it as the first argument to the SessionFactory constructor in your Spring configuration:

[source,java]
----
import org.neo4j.ogm.config.Configuration;
...

@Bean
public Configuration getConfiguration() {
   Configuration config = new Configuration();
   config
       .driverConfiguration()
       .setDriverClassName
        ("org.neo4j.ogm.drivers.http.driver.HttpDriver")
       .setURI("http://user:password@localhost:7474");
   return config;
}

@Bean
public SessionFactory getSessionFactory() {
    return new SessionFactory(getConfiguration(), <packages> );
}
----

_Note: Please see the section below describing the different ways you can pass credentials to the Http Driver_

==== Configuring the Embedded Driver

The Embedded Driver connects directly to the Neo4j database engine. There is no server involved, therefore no network overhead between your application code and the database.
You should use the Embedded driver if you don't want to use a client-server model, or if your application is running as a Neo4j Unmanaged Extension.

*Please note, if you want to use the Embedded driver in your deployed application, you will need to explicitly declare the required driver dependency in your project's pom file:
*
[source,xml]
----
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-ogm-embedded-driver</artifactId>
      <version>${ogm-version}</version>
    </dependency>
----

You can specify a permanent data store location to provide durability of your data after your application shuts down, or you can use an impermanent data store, which will only exist while your application is running.

.Properties file (permanent data store)
```
driver=org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
URI=file:///var/tmp/graph.db
```

.Properties file (impermanent data store)
```
driver=org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
```

.Java Configuration (permanent data store)

The same technique is used for configuring the Embedded driver as for the Http Driver.
Set up a Configuration bean and pass it as the first argument to the SessionFactory constructor:

[source,java]
----
import org.neo4j.ogm.config.Configuration;
...

@Bean
public Configuration getConfiguration() {
   Configuration config = new Configuration();
   config
       .driverConfiguration()
       .setDriverClassName
        ("org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver")
       .setURI("file:///var/tmp/graph.db");
   return config;
}

@Bean
public SessionFactory getSessionFactory() {
    return new SessionFactory(getConfiguration(), <packages> );
}
----

If you want to use an impermanent data store simply omit the URI attribute from the Configuration:

[source,java]
----
@Bean
public Configuration getConfiguration() {
   Configuration config = new Configuration();
   config
       .driverConfiguration()
       .setDriverClassName
        ("org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver");
   return config;
}
----

==== Authentication

If you are using the Http Driver you have a number of different ways to supply credentials to the Driver Configuration.

.Properties file options:
```
# embedded in the URI
URI=http://user:password@localhost:7474

# as separate attributes
username="user"
password="password"
```

.Java Configuration options
[source,java]
----
// embedded
Components.configuration()
             .driverConfiguration()
             .setURI("bolt://user:password@localhost");

// separately as plain text
Components.configuration()
             .driverConfiguration()
             .setCredentials("user", "password);

// using a Credentials object
Credentials credentials = new UsernameAndPasswordCredentials("user", "password");
Components.configuration()
             .driverConfiguration()
             .setCredentials(credentials);
----

[NOTE]
====
Currently only Basic Authentication is supported by Neo4j, so the only Credentials implementation available is `UsernameAndPasswordCredentials`
====

=== Testing

.Maven dependencies for Spring Data Neo4j Test classes
[source,xml]
----
       <dependency>
           <groupId>org.springframework.data</groupId>
           <artifactId>spring-data-neo4j</artifactId>
           <version>${sdn.version}</version>
           <type>test-jar</type>
       </dependency>

       <dependency>
           <groupId>org.neo4j</groupId>
            <artifactId>neo4j-kernel</artifactId>
            <version>${neo4j.version}</version>
            <type>test-jar</type>
       </dependency>

       <dependency>
            <groupId>org.neo4j.app</groupId>
            <artifactId>neo4j-server</artifactId>
            <version>${neo4j.version}</version>
            <type>test-jar</type>
       </dependency>

       <dependency>
          <groupId>org.neo4j</groupId>
          <artifactId>neo4j-ogm</artifactId>
          <version>${neo4j-ogm.version}</version>
          <type>test-jar</type>
          <scope>test</scope>
      </dependency>

      <dependency>
          <groupId>org.neo4j.test</groupId>
          <artifactId>neo4j-harness</artifactId>
          <version>${neo4j.version}</version>
          <scope>test</scope>
      </dependency>
----

[NOTE]
====
In SDN 4.1, the `InProcessServer` has been deprecated. This class was used to set up an in-memory Http server so that you could run your tests.
This is no longer appropriate given the new Driver mechanism, and we recommend you configure an Embedded Driver (impermanent data store) for your integration tests.
====
=== SessionFactory Bean

The `SessionFactory` is needed by SDN to create instances of `org.neo4j.ogm.session.Session` as required.  
When constructed, it sets up the object-graph mapping metadata, which is then used across all `Session` objects that it creates.
As seen in the above example, the packages to scan for domain object metadata should be provided to the `SessionFactory` constructor.

Note that the session factory should typically be application-scoped.
While you can use a narrower scope for this if you like, although there is typically no advantage in doing so.

=== Session Bean

A `Session` is used to drive the object-graph mapping framework on which Spring Data Neo4j is based.  
All repository implementations and `Neo4jTemplate` are driven by the `Session`, and you can also auto-wire it into your Spring beans and code against it directly if you wish.

The life cycle of a `Session` is important to consider because it keeps track of the changes that have been made to entities and their relationships.  
The reason it does this is so that only entities and relationships that have changed get persisted on save, which is particularly efficient when working with large graphs.  
Note, however, that the `Session` *does not ever return cached objects* so there's no risk of getting stale data on load; it always hits the database.

If your application relies on long-running sessions and does not reload entities then you may not see changes made from other users and find yourself working with outdated objects.
On the other hand, if your sessions have too narrow a scope then your save operations can be unnecessarily expensive, as updates will be made to all objects if the session isn't aware of the those that were originally loaded.

There's therefore a trade off between the two approaches.  
In general, the scope of a `Session` should correspond to a "unit of work" in your application.  
What this means depends on the usage scenario, but in a typical web-based Spring application we recommend using a request-scoped or HTTP-session-scoped `Session`.  
Either way, if you make sure you load fresh data at the beginning of each unit of work then data integrity shouldn't be a problem.

Additional beans can be configured to be included in the Neo4j-Configuration just by defining them in the Spring context in the normal way.

