[[reference_programming-model_transactions]]
= Transactions

Neo4j is a transactional database, only allowing operations to be performed within transaction boundaries.
Spring Data Neo4j integrates nicely with both the declarative transaction support with `@Transactional` as well as the manual transaction handling with `TransactionTemplate`.

Demarcating @Transactional is required for all methods that interact with SDN.
CRUD methods on `Repository` instances are transactional by default. If you are simply just looking up an object through a repository for example,
then you do not need to define anything else: SDN will take of everything for you.  That said, it is strongly recommended that you always annotate any service boundaries to the database with a `@Transactional` annotation. This way all your code for that method will always run in one transaction, even if you add a write operation later on.

More standard behaviour with Transactions is using a facade or service implementation that typically covers more than one repository or database call as part of a 'Unit of Work'. Its purpose is to define transactional boundaries for non-CRUD operations:

[IMPORTANT]
It is important to know that if you enable Transactions *ALL* code that uses the `Session` or `Neo4jTemplate` must have a @Transactional annotation.

[NOTE]
SDN only supports PROPAGATION_REQUIRED and ISOLATION_DEFAULT type transactions.

.Using a facade to define transactions for multiple repository calls
[source,java]
----
@Service
class UserManagementImpl implements UserManagement {

  private final UserRepository userRepository;
  private final RoleRepository roleRepository;

  @Autowired
  public UserManagementImpl(UserRepository userRepository,
    RoleRepository roleRepository) {
    this.userRepository = userRepository;
    this.roleRepository = roleRepository;
  }

  @Transactional
  public void addRoleToAllUsers(String roleName) {

    Role role = roleRepository.findByName(roleName);

    for (User user : userRepository.findAll()) {
      user.addRole(role);
      userRepository.save(user);
    }
}
----
This will cause call to `addRoleToAllUsers(…)` to run inside a transaction (participating in an existing one or create a new one if
none already running). The transaction configuration at the repositories will be neglected then as the outer transaction configuration
determines the actual one used.

It is highly recommended that users understand how Spring Transactions work. Below are some excellent resources:

* http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/transaction.html[Spring Transaction Management]
* http://graphaware.com/neo4j/2016/09/30/upgrading-to-sdn-42.html[Upgrading to Spring Data Neo4j 4.2]

== Read only Transactions

As of SDN 4.2 you can also define read only transactions.

You can start a read only transaction by marking a class or method with `@Transactional(readOnly=true)`.

[CAUTION]
Note that if you open a read only transaction from, for example a service method, and then call a mutating method that is marked as read/write your transaction semantics will always be defined by the outermost transaction. Be wary!

== Configuration

Note that you will have to activate `@EnableTransactionManagement` explicitly to get annotation based
configuration at facades working as well as define an instance of this `Neo4jTransactionManager` with the bean name `transactionManager`.
The example above assumes you are using component scanning.

To allow your query methods to be transactional simply use @Transactional at the repository interface you define.



== Transaction Bound Events
_Formally Data Manipulation Events/ Lifecycle Events_


SDN provides the ability to bind the listener of an event to a phase of the transaction. The typical example is to handle the event
when the transaction has completed successfully: this allows events to be used with more flexibility when the outcome of the current
transaction actually matters to the listener.

Spring Framework is currently structured in such a way that the context is not aware of the transaction support and has an open infrastructure to allow additional components to be registered and influence the way event listeners are created.

The transaction module implements an `EventListenerFactory` that looks for the new `@TransactionalEventListener` (as of Spring 4.2) annotation. When this one is present, an extended event listener that is aware of the transaction is registered instead of the default.

.Example: An order creation listener.
[source,java]
----
@Component
public class MyComponent {

  @TransactionalEventListener(condition = "#creationEvent.awesome")
  public void handleOrderCreatedEvent(CreationEvent<Order> creationEvent) {
    ...
  }

}
----

`@TransactionalEventListener` is a regular `@EventListener` and also exposes a `TransactionPhase`, the default being `AFTER_COMMIT`. You can also hook other phases of the transaction (`BEFORE_COMMIT`, `AFTER_ROLLBACK` and `AFTER_COMPLETION` that is just an alias for `AFTER_COMMIT` and `AFTER_ROLLBACK`).

By default, if no transaction is running the event isn’t sent at all as we can’t obviously honor the requested phase, but there is a fallbackExecution attribute in `@TransactionalEventListener` that tells Spring to invoke the listener immediately if there is no transaction.

[NOTE]
Only public methods in a managed bean can be annotated with `@EventListener` to consume events.
`@TransactionalEventListener` is the annotation that provides transaction-bound event support described here.

To find out more about Spring's Event listening capabilities see http://docs.spring.io/spring/docs/current/spring-framework-reference/html/beans.html#context-functionality-events-annotation[the Spring reference manual] and https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2[How to build Transaction aware Eventing with Spring 4.2].

