[[spring-data-neo4j-reference-documentation]]
= Spring Data Neo4j
:revnumber: {version}
:revdate: {localdate}
:feature-scroll: true

_Spring Data for Apache Cassandra provides repository support for the Apache Cassandra database.
It eases development of applications with a consistent programming model that need to access Cassandra data sources._

[horizontal]
// xref:cassandra.adoc[Cassandra] :: Apache Cassandra support and connectivity
// xref:repositories.adoc[Repositories] :: Apache Cassandra Repositories
// xref:observability.adoc[Observability] :: Observability Integration
// xref:kotlin.adoc[Kotlin] :: Kotlin support
// xref:migration-guides.adoc[Migration] :: Migration Guides
https://github.com/spring-projects/spring-data-commons/wiki[Wiki] :: What's New, Upgrade Notes, Supported Versions, additional cross-version information.

David Webb, Matthew Adams, John Blum, Mark Paluch, Jay Bryant

(C) 2008-2023 VMware, Inc.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.