[[reference_migration]]
= Migrating from previous versions of Spring Data Neo4j

== Package changes
Because the Neo4j Object Graph Mapper can be used independently of Spring Data Neo4j, the core annotations have been
moved out of the spring framework packages:

`org.springframework.data.neo4j.annotation` -> `org.neo4j.ogm.annotation`

[NOTE]
====
The `@Query` and `@QueryResult` annotations are only supported in the Spring modules, and are not used by the core
mapping framework. These annotations have not changed.
====

== Annotation changes
There have been some changes to the annotations that were used in previous versions of Spring Data Neo4j.
Wherever possible we have tried to maintain the previous annotations verbatim, but in a few cases this has not been
possible, usually for technical reasons but sometimes for aesthetic ones. Our goal has been to minimise the number
of annotations you need to use as well as trying to make them more self-explanatory. The following annotations
have been changed.

|===
h| Old h| New
m| @RelatedTo m| @Relationship
m| @RelatedToVia m| @Relationship
m| @GraphProperty m| @Property
m| Relationship Direction.BOTH m| Relationship.UNDIRECTED
|===

[[custom_converters]]
== Custom Type Conversion
SDN 4 provides automatic type conversion for the obvious candidates: byte[] and Byte[] arrays, Dates, BigDecimal and
BigInteger types. In order to define bespoke type conversions for particular entity attribute, you can annotate a
field or method with `@Convert` to specify your own implementation of `org.neo4j.ogm.typeconversion.AttributeConverter`.

You can find out more about type conversions here: <<reference_programming-model_conversion-custom,Custom Converters>>

== Obsolete annotations

The following annotations are no longer used, either because they are no longer needed, or cannot be supported via Cypher.

* @GraphTraversal
* @RelatedToVia
* @RelatedTo
* @Index
* @TypeAlias
* @Fetch

== Features no longer supported

Some features of the previous annotations have been dropped.

=== Overriding @Property types
Support for overriding property types via arguments to @Property has been dropped. If your attribute requires
a non-default conversion to and from a database property, you can use a <<custom_converters,Custom Converter>> instead.

=== @Relationship `enforceTargetType`
In previous versions of Spring Data Neo4j, you would have to add an `enforceTargetType` attribute into every clashing
`@Relationship` annotation.  Thanks to changes in the underlying object-graph mapping mechanism, this is no longer
necessary.

.Clashing Relationship Types
[source,java]
----
@NodeEntity
class Person {
    @Relationship(type="OWNS")
    private Car car;

    @Relationship(type="OWNS")
    private Pet pet;
...
}
----

=== Cross-store Persistence
Neo4j is dropping XA support and therefore SDN 4 does not provide any capability for cross-store persistence

=== TypeRepresentationStrategy
SDN 4 replaces the existing TypeRepresentionStrategy configuration with a straightforwad convention based on simple class-names
or entities using `@NodeEntity(label=...)`

Please refer to <<reference_programming_model_typerepresentationstrategy,Entity Type Representation>> for more details.

=== AspectJ Support
Support for Aspect J based persistence has been removed from SDN 4 as the write- and read-through approach only works with an integrated, embedded database, not Neo4j server. The performance improvements in SDN 4 should make the use as a performance optimization unnecessary.


== Changes to Neo4jTemplate

The `Neo4jTemplate` has been slimmed-down significantly for SDN 4 with many of the method signatures changed to reflect the updated behaviour.

Many of the operations are no longer needed or can be expressed with a straightforward Cypher query.

=== API Changes

The following table shows the `Neo4jTemplate` functions that have been retained for version 4 of Spring Data Neo4j.  In some cases the method names have changed but the same functionality is offered under the new version.

[cols="1,1,2"]
.Neo4j Template Method Migration
|===
|Old Method Name|New Method Name|Notes

|`findOne`
|`load`
|Overloaded to take optional depth parameter

|`findAll`
|`loadAll`
|Overloaded to take optional depth parameter, also now returns a `Collection` rather than a `Result`

|`query`
|`query`
|Return type changed from `Result` to be `Iterable`

|`save`
|`save`
|

|`delete`
|`delete`
|

|`count`
|`count`
|No longer defines generic type parameters

|`findByIndexedValue`
|`loadByProperty`
|Indexes are not supported natively, but you can index node properties in your database setup and use this method to find by them

|===
 
To achieve the old `template.fetch(entity)` equivalent behaviour, you should call one of the load methods specifying the fetch depth as a parameter.

It's also worth noting that `exec(GraphCallback)` and the `create...()` methods have been made obsolete by Cypher.
Instead, you should now issue a Cypher query to the new `execute` method to create the nodes or relationships that you need.

== Indexing

The best way for retrieving start nodes for traversals and queries is by using Neo4j's integrated index facilities.
Spring Data Neo4j takes the view that index maintenance should not be part of your application code. For that reason,
it does not provide any explicit index-related functionality.

However, it is very important that indices are in place for efficient node lookups.
Make sure those are applied to your test and especially production databases to guarantee efficient query execution.
Please make sure you read http://neo4j.com/docs/stable/query-schema-index.html[Neo4j Documentation]
on indices.

=== Built-In Query DSL Support
Previous versions of SDN allowed you to use a DSL to generate Cypher queries. There are many different DSL
libraries available and you're free to use which of these - or none - that you want. With Cypher changing on a regular
basis, avoiding a DSL implementation in SDN means less ongoing maintenance and less likelihood of your code
being incompatible with future versions of Neo4j.

=== Graph Traversal and Node/Relationship Manipulation
These features cannot be supported by Cypher and have therefore been dropped from `Neo4jTemplate`.


Please provide feedback on the new APIs of SDN 4 and the migration needs to spring-data-neo4j@neotechnology.com or via a https://jira.spring.io/browse/DATAGRAPH[JIRA issue]