[[logging]]
= Logging

Spring Data Neo4j provides multiple loggers for https://neo4j.com/docs/status-codes/current/notifications/all-notifications/[Cypher notifications], starting with version 7.1.5.
The logger `org.springframework.data.neo4j.cypher` includes all statements that were invoked by Spring Data Neo4j and all notifications sent from the server.
To exclude or elevate some categories, the following loggers are in place:

* `org.springframework.data.neo4j.cypher.performance`
+
Includes `Neo.ClientNotification.Statement.CartesianProduct`,
`Neo.ClientNotification.Statement.UnboundedVariableLengthPattern`,
`Neo.ClientNotification.Statement.ExhaustiveShortestPath`,
`Neo.ClientNotification.Statement.NoApplicableIndex`,
`Neo.ClientNotification.Statement.EagerOperator`,
`Neo.ClientNotification.Statement.DynamicProperty`,
`Neo.ClientNotification.Statement.CodeGenerationFailed`

* `org.springframework.data.neo4j.cypher.hint`
+
Includes `Neo.ClientNotification.Statement.JoinHintUnfulfillableWarning`,
`Neo.ClientNotification.Schema.HintedIndexNotFound`

* `org.springframework.data.neo4j.cypher.unrecognized`
+
Includes `Neo.ClientNotification.Database.HomeDatabaseNotFound`,
`Neo.ClientNotification.Statement.UnknownLabelWarning`,
`Neo.ClientNotification.Statement.UnknownRelationshipTypeWarning`,
`Neo.ClientNotification.Statement.UnknownPropertyKeyWarning`

* `org.springframework.data.neo4j.cypher.unsupported`
+
Includes `Neo.ClientNotification.Statement.RuntimeUnsupportedWarning`,
`Neo.ClientNotification.Statement.RuntimeExperimental`

* `org.springframework.data.neo4j.cypher.deprecation`
+
Includes `Neo.ClientNotification.Statement.FeatureDeprecationWarning`,
`Neo.ClientNotification.Request.DeprecatedFormat`

* `org.springframework.data.neo4j.cypher.generic`
+
Includes `Neo.ClientNotification.Statement.SubqueryVariableShadowing`,
`Neo.ClientNotification.Statement.ParameterNotProvided`,
`Neo.ClientNotification.Procedure.ProcedureWarning`,
`Neo.ClientNotification.Statement.UnsatisfiableRelationshipTypeExpression`,
`Neo.ClientNotification.Statement.RepeatedRelationshipReference`