[preface]
= About this guide book

== The Spring Data Neo4j Project

Welcome to the Spring Data Neo4j Guide Book. 
Thank you for taking the time to get an in-depth look into http://projects.spring.io/spring-data-neo4j/[Spring Data Neo4j]. 
This project is part of the http://projects.spring.io/spring-data[Spring Data project], which brings the convenient programming model of the Spring Framework to modern NOSQL databases. Spring Data Neo4j, as the name alludes to, aims to provide support for the graph database http://neo4j.com[Neo4j].

== Feedback

It was written by developers for developers. Hopefully we've created a guide that is well received by our peers.

If you have any feedback on Spring Data Neo4j or this book, please provide it via the https://jira.spring.io/browse/DATAGRAPH[SpringSource JIRA],  http://stackoverflow.com/questions/tagged/spring-data-neo4j[StackOverflow] or the http://groups.google.com/group/neo4j[Neo4j Google Group].

== Format of the Book

////
This book is presented as a http://martinfowler.com/bliki/DuplexBook.html[duplex book], a term coined by Martin Fowler. A duplex book consists of at least two parts. The first part is an easily accessible tutorial or narrative that gives the reader an overview of the topics contained in the book. It contains lots of examples and discussion topics. This part of the book is highly suited for cover-to-cover reading.

We chose a tutorial describing the creation of a web application that allows movie enthusiasts to find their favorite movies, rate them, connect with fellow movie geeks, and enjoy social features such as recommendations. The application is running on Neo4j using Spring Data Neo4j and the well-known Spring Web Stack.

The second part of the book is the 
////
This book is a classic reference documentation, containing detailed information about the library. It discusses the programming model, the underlying assumptions, and internals, as well as the APIs for the object-graph mapping. The reference documentation is typically used to look up concrete bits of information, or to drill down into certain topics. 

== Acknowledgements

We would like to thank everyone who contributed to this book, especially Oliver Gierke, the lead of the Spring Data Project, who helped a lot during the development of the library as well.

Many thanks to our colleagues at Neo Technology and Graph Aware who not only contributed to Spring Data Neo4j but also provided content and feedback for this book.

We also appreciate very much the foresight of Rod Johnson and Emil Eifrem to initiate the original project. Their leadership inspired collaboration between the engineering teams at SpringSource and Neo Technology, a tremendous help during the making of Spring Data Neo4j.

Last but not least we thank our vibrant community for giving us feedback, reporting issues and suggesting improvements. Without that important feedback we wouldn't be where we are today.

Enjoy the book!


