[preface]
= About this guide book

== The Spring Data Neo4j Project

Welcome to the Spring Data Neo4j Guide Book. 
Thank you for taking the time to get an in-depth look into http://projects.spring.io/spring-data-neo4j/[Spring Data Neo4j]. 
This project is part of the http://projects.spring.io/spring-data[Spring Data project], which brings the convenient programming model of the Spring Framework to modern NOSQL databases. Spring Data Neo4j, as the name alludes to, aims to provide support for the graph database http://neo4j.com[Neo4j].

== Feedback

It was written by developers for developers. Hopefully we've created a guide that is well-received by our peers.

If you have any feedback on Spring Data Neo4j or this book, please provide it via the https://jira.spring.io/browse/DATAGRAPH[SpringSource JIRA],  http://stackoverflow.com/questions/tagged/spring-data-neo4j[StackOverflow] or the http://groups.google.com/group/neo4j[Neo4j Google Group].

== Format of the Book


This book is a classic reference document, containing detailed information about the library. It discusses the programming model, the underlying assumptions, and internals, as well as the APIs for the object-graph mapping. The reference documentation is typically used to look up particular pieces of information or to drill down into certain topics. 

== Acknowledgements

We would like to thank everyone who contributed to this book, especially Oliver Gierke, the lead of the Spring Data Project.

Many thanks to our colleagues at Neo Technology and Graph Aware who not only contributed to Spring Data Neo4j but also provided content and feedback for this book.

We also appreciate very much the foresight of Rod Johnson and Emil Eifrem to initiate the original project. Their leadership inspired collaboration between the engineering teams at SpringSource and Neo Technology, a tremendous help during the making of Spring Data Neo4j.

Last but not least we thank our vibrant community for giving us feedback, reporting issues and suggesting improvements. Without that important feedback we wouldn't be where we are today.

Enjoy the book!


