package org.springframework.persistence.test;

import java.util.ArrayList;
import java.util.List;

import org.neo4j.graphdb.Direction;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.Node;
import org.neo4j.graphdb.Relationship;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.persistence.graph.neo4j.Neo4jHelper;

/**
 * EXAMPLE OF CODE THAT SHOULD BE GENERATED BY ROO BESIDES EACH GRAPHENTITY CLASS 
 * 
 * Note: Combines X_Roo_Entity with X_Roo_Finder, as
 * we need only a single aspect for entities.
 * @author rodjohnson
 *
 */
privileged aspect Person_Graph_Entity {
	
	// TODO should be a better way of getting this? Could at least pull out gdsholder class
	private static GraphDatabaseService graphDatabaseService() {
		return new GdsHolder().gds;
	}
	
	@Configurable
	public static class GdsHolder {
		@Autowired
		public GraphDatabaseService gds;
	}
	
	/**
	 * Add constructor that takes node.
	 * @param node
	 */
	public Person.new(Node node) {
		setUnderlyingNode(node);
	}

	public static long Person.countPeople() {
		return Neo4jHelper.count(Person.class, Person_Graph_Entity.graphDatabaseService());
	}

	public static List<Person> Person.findAllPeople() {
		Node subrefNode = Neo4jHelper.findSubreferenceNode(Person.class, graphDatabaseService());
		// TODO Neo4j should add lazy list on top of graph
		List<Person> people = new ArrayList<Person>((int) countPeople());		
		for (Relationship rel : subrefNode.getRelationships(Neo4jHelper.INSTANCE_OF_RELATIONSHIP_TYPE, Direction.INCOMING)) {
			Node personNode = rel.getStartNode();
			people.add(new Person(personNode));
		}
		return people;
	}

	public static Person Person.findPerson(Long id) {
		Node n = Person_Graph_Entity.graphDatabaseService().getNodeById(id);
		Person found = new Person(n);
		return found;
	}
	

	// Pluggable query executors/resolvers, discussed with PL
//	public static Person.findFooBars(int a, int b) {
//		return executeQuery("foobar", a, b);
//		// First look for String, then for method
//		// QueryInterceptionResolver
//	}

//	public static List<Person> Person.findPersonEntries(int firstResult,
//			int maxResults) {
//		throw new UnsupportedOperationException();
//	}
}
