== Spring Boot / Imperative Web Example

=== Building SDN/RX and Examples.

NOTE: *You need to have JDK 12 installed.

You can either built the complete project, including the examples.
Thus, the examples will use your copy of SDN/RX, and any potential changes you made:

[source,bash]
----
git clone git@github.com:neo4j/sdn-rx
cd sdn-rx
./mvnw -DskipTests -Drevision=1.0.0 -Dchangelist=-SNAPSHOT clean package
----

If you want to only try out the examples with the currently released version,
pick out the example you like (for example the `imperative-web` example) and build it like this:

[source,bash]
----
git clone git@github.com:neo4j/sdn-rx
cd sdn-rx/examples/imperative-web
mvn -DskipTests clean package
cd ../..
----

=== Running the examples.

You'll need a Neo4j 4 instance that has a user name `neo4j` with a password of `secret`.
Please use `:play movies` in Neo4j browser to get some data in your graph.
With from SDN/RX root folder run

[source,bash]
----
java -jar examples/imperative-web/target/movie-api.jar
----

If your database has different credentials or is on a different host, run

[source,bash]
----
java -jar examples/reactive-web/target/movie-api.jar \
--org.neo4j.driver.uri=neo4j://yourhost:7687 \
--org.neo4j.driver.authentication.username=youruser \
--org.neo4j.driver.authentication.password=yourpassword
----

with parameters fitting to your needs.

Here are some _curl_ commands, you can try out.
The same examples are also available in the file `movie-api-examples.http` that you can call from IDEA.

[source,bash]
.Create a new movie
----
curl -X "PUT" "http://localhost:8080/movies" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "title": "Aeon Flux",
  "description": "Reactive is the new cool"
}'
----

[source,bash]
.List all movies.
----
curl http://localhost:8080/movies
----

[source,bash]
.Query a movie by title.
----
curl http://localhost:8080/movies/by-title\?title\=Aeon%20Flux
----

[source,bash]
.Delete a movie by id (use the one returned above for example)
----
curl -X DELETE http://localhost:8080/movies/847
----
