[[faq]]
= Frequently Asked Questions

Here are a couple of more frequently asked question in addition to the ones in the <<what-is-sdn,preface>>.

[[faq.multidatabase]]
== Neo4j 4.0 supports multiple databases - How can I use them?

You can either statically configure the database name or run your own database name provider.
Bear in mind that SDN will not create the databases for you.
You can do this with the help of a https://github.com/michael-simons/neo4j-migrations[migrations tool]
or of course with a simple script upfront.

=== Statically configured

Configure the database name to use in your Spring Boot configuration like this (The same property applies of course for YML or environment based configuration, with Spring Boots conventions applied):

[source,properties]
----
org.neo4j.data.database = yourDatabase
----

With that configuration in place, all queries generated by all instances of SDN repositories (both reactive and imperative) and by the `ReactiveNeo4jTemplate` respectively `Neo4jTemplate` will be executed against the database `yourDatabase`.

=== Dynamically configured

Provide a bean with the type `Neo4jDatabaseNameProvider` or `ReactiveDatabaseSelectionProvider` depending on the type of your Spring application.

That bean could use for example Spring's security context to retrieve a tenant.
Here is a working example for an imperative application secured with Spring Security:

[source,java]
[[faq.databaseSelectionProvider]]
.Neo4jConfig.java
----
import org.neo4j.springframework.data.core.DatabaseSelection;
import org.neo4j.springframework.data.core.DatabaseSelectionProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;

include::../../../../src/test/java/org/springframework/data/neo4j/documentation/Neo4jConfig.java[tags=faq.multidatabase]
----

NOTE: Be careful that you don't mix up entities retrieved from one database with another database.
The database name is requested for each new transaction, so you might end up with less or more entities than expected when changing the database name in between calls.
Or worse, you could inevitable store the wrong entities in the wrong database.

== Do I need specific configuration so that transactions work seamless with a Neo4j Causal Cluster?

No, you don't.
SDN uses Neo4j Causal Cluster bookmarks internally without any configuration on your side required.
Transactions in the same thread or the same reactive stream following each other will be able to read their previously changed values as you would expect.

== Do I need to use Neo4j specific annotations?

No.
You are free to use the following, equivalent Spring Data annotations:

[cols="4*",options="header"]
|===

|SDN specific annotation
|Spring Data common annotation
|Purpose
|Difference

|`org.springframework.data.neo4j.core.schema.Id`
|`org.springframework.data.annotation.Id`
|Marks the annotated attribute as the unique id.
|Specific annotation has no additional features.

|`org.springframework.data.neo4j.core.schema.Node`
|`org.springframework.data.annotation.Persistent`
|Marks the class as persistent entity.
|`@Node` allows customizing the labels

|===

== How do I use assigned ids?

Just `@Id` without `@GeneratedValue` and fill your id attribute via a constructor parameter or a setter or _wither_.
See this https://medium.com/neo4j/neo4j-ogm-and-spring-data-neo4j-a55a866df68c[blog post] for some general remarks about finding good ids.

== How do I use externally generated ids?

We provide the interface `org.springframework.data.neo4j.core.schema.IdGenerator`.
Implement it anyway you want and configure your implementation like this:

[source,java]
.ThingWithGeneratedId.java
----
@Node
public class ThingWithGeneratedId {

	@Id @GeneratedValue(TestSequenceGenerator.class)
	private String theId;
}
----

If you pass in the name of a class to `@GeneratedValue`, this class must have a no-args default constructor.
You can however use a string as well:

[source,java]
.ThingWithIdGeneratedByBean.java
----
@Node
public class ThingWithIdGeneratedByBean {

	@Id @GeneratedValue(generatorRef = "idGeneratingBean")
	private String theId;
}
----

With that, `idGeneratingBean` refers to a bean in the Spring context.
This might be useful for sequence generating.

NOTE: Setters are not required on non-final fields for the id.

[[template-support]]
== Do I have to create repositories for each domain class?

No.
Have a look at the <<sdn-building-blocks, SDN building blocks>> and find the `Neo4jTemplate` respectively the `ReactiveNeo4jTemplate.`

Those templates know your domain and provide all necessary basic CRUD methods for retrieving, writing and counting entities.

This is our canonical movie example with the imperative template:

[source,java]
[[imperative-template-example]]
.TemplateExampleTest.java
----
include::../../../../src/test/java/org/springframework/data/neo4j/documentation/spring_boot/TemplateExampleTest.java[tags=faq.template-imperative]
----

And here is the reactive version, omitting the setup for brevity:

[source,java]
[[reactive-template-example]]
.ReactiveTemplateExampleTest.java
----
include::../../../../src/test/java/org/springframework/data/neo4j/documentation/spring_boot/ReactiveTemplateExampleTest.java[tags=faq.template-reactive]
----

== How do I specify parameters in custom queries?

You do this exactly the same way as in a standard Cypher query issued in the Neo4j Browser or the Cypher-Shell, with the `$` syntax (from Neo4j 4.0 on upwards, the old `{foo}` syntax for Cypher parameters has been removed from the database);

[source,java,indent=0]
[[custom-queries-with-parameters]]
.ARepository.java
----
include::../../../../src/test/java/org/springframework/data/neo4j/documentation/repositories/domain_events/ARepository.java[tags=standard-parameter]
----
<.> Here we are referring to the parameter by its name.
You can also use `$0` etc. instead.

NOTE: You need to compile your Java 8+ project with `-parameters` to make named parameters work without further annotations.
The Spring Boot Maven and Gradle plugins do this automatically for you.
If this is not feasible for any reason, you can either add
`@Param`  and specify the name explicitly or use the parameters index.

== How do I use Spring Expression Language in custom queries?

{spring-framework-ref}/core.html#expressions[Spring Expression Language (SpEL)] can be used in custom queries inside `:#{}`.
This is the standard Spring Data way of defining a block of text inside a query that undergoes SpEL evaluation.

The following example basically defines the same query as above, but uses a `WHERE` clause to avoid even more curly braces:

[source,java,indent=0]
[[custom-queries-with-spel]]
.ARepository.java
----
include::../../../../src/test/java/org/springframework/data/neo4j/documentation/repositories/domain_events/ARepository.java[tags=spel]
----

The SpEL blocked starts with `:#{` and than refers to the given `String` parameters by name (`#pt1`).
Don't confuse this with the above Cypher syntax!
The SpEL expression concatenates both parameters into one single value that is eventually passed on to the <<neo4j-client>>.
The SpEL block ends with `}`.

== How do I audit entities?

All Spring Data annotations are supported.
Those are

* `org.springframework.data.annotation.CreatedBy`
* `org.springframework.data.annotation.CreatedDate`
* `org.springframework.data.annotation.LastModifiedBy`
* `org.springframework.data.annotation.LastModifiedDate`

== How do I use "Find by example"?

"Find by example" is a new feature in SDN.
You instantiate an entity or use an existing one.
With this instance you create an `org.springframework.data.domain.Example`.
If your repository extends `org.springframework.data.neo4j.repository.Neo4jRepository` or `org.springframework.data.neo4j.repository.ReactiveNeo4jRepository`, you can immediately use the available `findBy` methods taking in an example, like shown in <<find-by-example-example>>

[source,java]
[[find-by-example-example]]
.findByExample in Action
----
Example<MovieEntity> movieExample = Example.of(new MovieEntity("The Matrix", null));
Flux<MovieEntity> movies = this.movieRepository.findAll(movieExample);

movieExample = Example.of(
	new MovieEntity("Matrix", null),
	ExampleMatcher
	    .matchingAny()
        .withMatcher(
        	"title",
        	ExampleMatcher.GenericPropertyMatcher.of(ExampleMatcher.StringMatcher.CONTAINING)
        )
);
movies = this.movieRepository.findAll(movieExample);
----

== Do I need Spring Boot to use Spring Data Neo4j?

No, you don't.
While the automatic configuration of many Spring aspects through Spring Boot takes away a lot of manual cruft and is the recommended approach for setting up new Spring projects, you don't need to have to use this. 

The following dependency is required for the solutions described above:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
	<groupId>{neo4jGroupId}</groupId>
	<artifactId>{artifactId}</artifactId>
	<version>{spring-data-neo4j-version}</version>
</dependency>
----

The coordinates for a Gradle setup are the same.

To select a different database - either statically or dynamically - you can add a Bean of type `DatabaseSelectionProvider` as explained in <<faq.multidatabase>>.
For a reactive scenario, we provide `ReactiveDatabaseSelectionProvider`.

=== Using Spring Data Neo4j inside a Spring context without Spring Boot

We provide two abstract configuration classes to support you in bringing in the necessary beans: `AbstractNeo4jConfig` for imperative database access and `AbstractReactiveNeo4jConfig` for the reactive version.
They are meant to be used with `@EnableNeo4jRepositories` and `@EnableReactiveNeo4jRepositories` respectively. 
See <<bootless-imperative-configuration>> and <<bootless-reactive-configuration>> for an example usage.
Both classes require you to override `driver()` in which you are supposed to create the driver.

To get the imperative version of the <<neo4j-client,Neo4j client>>, the template and support for imperative repositories, use something similar as shown here:

[source,java]
[[bootless-imperative-configuration]]
.Enabling Spring Data Neo4j infrastructure for imperative database access
----
import org.neo4j.driver.Driver;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import org.springframework.transaction.annotation.EnableTransactionManagement;

import org.springframework.data.neo4j.config.AbstractNeo4jConfig;
import org.springframework.data.neo4j.core.DatabaseSelectionProvider;
import org.springframework.data.neo4j.repository.config.EnableNeo4jRepositories;

@Configuration
@EnableNeo4jRepositories
@EnableTransactionManagement
class MyConfiguration extends AbstractNeo4jConfig {

    @Override @Bean
    public Driver driver() { // <.>
        return GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "secret"));
    }

    @Override
    protected Collection<String> getMappingBasePackages() {
        return Collections.singletonList(Person.class.getPackage().getName());
    }

    @Override @Bean // <.>
    protected DatabaseSelectionProvider databaseSelectionProvider() {

        return DatabaseSelectionProvider.createStaticDatabaseSelectionProvider("yourDatabase");
    }
}
----
<.> The driver bean is required.
<.> This statically selects a database named `yourDatabase` and is *optional*.

The following listing provides the reactive Neo4j client and template, enables reactive transaction management and discovers Neo4j related repositories:

[source,java]
[[bootless-reactive-configuration]]
.Enabling Spring Data Neo4j infrastructure for reactive database access
----
import org.neo4j.driver.Driver;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.neo4j.config.AbstractReactiveNeo4jConfig;
import org.springframework.data.neo4j.repository.config.EnableReactiveNeo4jRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@Configuration
@EnableReactiveNeo4jRepositories
@EnableTransactionManagement
class MyConfiguration extends AbstractReactiveNeo4jConfig {

    @Bean
    @Override
    public Driver driver() {
        return GraphDatabase.driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "secret"));
    }

    @Override
    protected Collection<String> getMappingBasePackages() {
        return Collections.singletonList(Person.class.getPackage().getName());
    }
}
----

=== Using Spring Data Neo4j in a CDI 2.0 environment

For your convenience we provide a CDI extension with `Neo4jCdiExtension`.
When run in a compatible CDI 2.0 container, it will be automatically be registered and loaded through https://docs.oracle.com/javase/tutorial/ext/basics/spi.html[Java's service loader SPI].

The only thing you have to bring into your application is an annotated type that produces the Neo4j Java Driver:

[source,java]
[[cdi-driver-producer]]
.A CDI producer for the Neo4j Java Driver
----
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Disposes;
import javax.enterprise.inject.Produces;

import org.neo4j.driver.AuthTokens;
import org.neo4j.driver.Driver;
import org.neo4j.driver.GraphDatabase;

public class Neo4jConfig {

    @Produces @ApplicationScoped
    public Driver driver() { // <.>
        return GraphDatabase
            .driver("bolt://localhost:7687", AuthTokens.basic("neo4j", "secret"));
    }

    public void close(@Disposes Driver driver) {
        driver.close();
    }

    @Produces @Singleton
    public DatabaseSelectionProvider getDatabaseSelectionProvider() { // <.>
        return DatabaseSelectionProvider.createStaticDatabaseSelectionProvider("yourDatabase");
    }
}
----
<.> Same as with plain Spring in <<bootless-imperative-configuration>>, but annotated with the corresponding CDI infrastructure.
<.> This is *optional*. However, if you run a custom database selection provider, you _must_ not qualify this bean.

If you are running in a SE Container - like the one https://weld.cdi-spec.org[Weld] provides for example, you can enable the extension like that:

[source,java]
[[cdi-driver-producer-se]]
.Enabling the Neo4j CDI extension in a SE container
----
import javax.enterprise.inject.se.SeContainer;
import javax.enterprise.inject.se.SeContainerInitializer;

import org.springframework.data.neo4j.config.Neo4jCdiExtension;

public class SomeClass {
    void someMethod() {
        try (SeContainer container = SeContainerInitializer.newInstance()
                .disableDiscovery()
                .addExtensions(Neo4jCdiExtension.class)
                .addBeanClasses(YourDriverFactory.class)
                .addPackages(Package.getPackage("your.domain.package"))
            .initialize()
        ) {
            SomeRepository someRepository = container.select(SomeRepository.class).get();
        }
    }
}
----