[[building-blocks]]
= Building blocks of Spring Data Neo4j

== Overview

SDN consists of composable building blocks.
It builds on top of the https://github.com/neo4j/neo4j-java-driver[Neo4j Java Driver].
The instance of the Java driver is provided through Spring Boot's automatic configuration itself.
All configuration options of the driver are accessible in the namespace `spring.neo4j`.
The driver bean provides imperative, asynchronous and reactive methods to interact with Neo4j.

You can use all transaction methods the driver provides on that bean such as https://neo4j.com/docs/driver-manual/4.0/terminology/#term-auto-commit[auto-commit transactions],
https://neo4j.com/docs/driver-manual/4.0/terminology/#term-transaction-function[transaction functions] and unmanaged transactions.
Be aware that those transactions are not tight to an ongoing Spring transaction.

Integration with Spring Data and Spring's platform or reactive transaction manager starts at the xref:appendix/neo4j-client.adoc#neo4j-client[Neo4j Client].
The client is part of SDN is configured through a separate starter, `{artifactIdStarter}`.
The configuration namespace of that starter is `spring.data.neo4j`.

The client is mapping agnostic.
It doesn't know about your domain classes, and you are responsible for mapping a result to an object suiting your needs.

The next higher level of abstraction is the Neo4j Template.
It is aware of your domain, and you can use it to query arbitrary domain objects.
The template comes in handy in scenarios with a large number of domain classes or custom queries for which you don't want to create an additional repository abstraction each.

The highest level of abstraction is a Spring Data repository.

All abstractions of SDN come in both imperative and reactive fashions.
It is not recommended mixing both programming styles in the same application.
The reactive infrastructure requires a Neo4j 4.0+ database.

[[sdn-building-blocks]]
[ditaa,sdn-buildingblocks,png]
.SDN building blocks
----
+---------------------------------------------------------+
|                                                         |
|  SDN                   +----------------------------+   |
|                        |                            |   |
|                        |  Spring Data Repositories  |   |
|                        |                            |   |
|                        +-------------+--------------+   |
|                                      |                  |
|                                      |                  |
|                                      v                  |
|                        +-------------+--------------+   |                    +---------------------------------------+
|                        |                            |   |    Provides        |                                       |
|                        |    Neo4j Template          |   | <------------------+     sdn-spring-boot-starter           |
|                        |                            |   |                    |                                       |
|                        +-------------+--------------+   |                    +---------------------------------------+
|                                      |                  |
|                                      |                  |
|                                      v                  |
|                        +-------------+--------------+   |
|  Integration with      |                            |   |
|  Spring Transactions   |      Neo4j Client          |   |
|  from here on          |                            |   |
|                        +-------------+--------------+   |
|                                      |                  |
|                                      |                  |
+--------------------------------------|------------------+
                                       |
                                       v
                         +-------------+--------------+                        +---------------------------------------+
                         |                            |        Provides        |                                       |
                         |      Neo4j Java Driver     |      <-----------------+     spring-boot-starter               |
                         |                            |                        |                                       |
                         +----------------------------+                        +---------------------------------------+
----

The template mechanism is similar to the templates of others stores.
Find some more information about it in xref:faq.adoc#template-support[our FAQ].
The Neo4j Client as such is unique to SDN.
You will find its documentation in the xref:appendix/neo4j-client.adoc#neo4j-client[appendix].

[[sdn-packages]]
== On the package level

[%header,cols=2*]
|===
|Package
|Description

|`org.springframework.data.neo4j.config`
|
include::example$config/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.core`
|
include::example$core/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.core.convert`
|
include::example$core/convert/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.core.support`
|
include::example$core/support/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.core.transaction`
|
include::example$core/transaction/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.repository`
|
include::example$repository/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.repository.config`
|
include::example$repository/config/package-info.java[tags=intent,indent=0]

|`org.springframework.data.neo4j.repository.support`
|
include::example$repository/support/package-info.java[tags=intent,indent=0]

|===
