[[reference_performance]]
= Performance Considerations

As with any other object mapping framework, the domain entities that are created, read, or persisted potentially represent only a small fraction of the data stored in the database.
This is the set needed for a certain use-case to be displayed, edited or processed in a low throughput fashion.
The main advantages of using an object mapper in this case are the ease of use of real domain objects in your business logic and also the integration with existing frameworks and libraries that expect Java POJOs as input or create them as results.

Although adding layers of abstraction is a common pattern in software development, each of these layers generally adds overhead and performance penalties. 
This chapter discusses the performance implications of using Spring Data Neo4j.

== Focus on performance
This new version 4 of SDN has been rebuilt from the ground up.
It is based on the understanding that the majority of users wants to run application servers that connect to remote database instances.
They will therefore need to communicate "over the wire".
Neo4j provides the capability to do this now with its powerful Cypher language, which is exposed via a remote protocol.

What we have attempted to do is to ensure that, as much as possible, we don't overload that communication channel.
This is important for two reasons. 
Firstly, every network interaction involves an overhead (both bandwidth but more so latency) which impacts the response times of your application. 
Secondly, network requests containing redundant operations (such as updaing an object which hasn't changed) are unnecessary, and have similar impacts.
We have approached this problem in a number of ways:

=== Variable-depth persistence
You can now tailor your persistence requests according to the characteristics of the portions of your graph you want to work with. 
This means you can choose to make deeper or shallower fetches based on fine tuning the types and amounts of data you want to transfer based on your individual constraints.

If you know that you aren't going to need an object's related objects, you can choose not to fetch them by specifying the fetch-depth as 0. 
Alternatively if you know that you will always want to a person's complete set of friends-of-friends, you can set the depth to 2.

=== Smart object-mapping
SDN 4 introduces smart object-mapping. 
This means that all other things being equal, it is possible to reliably detect which nodes and relationships needs to be changed in the database, and which don't.

Knowing what needs to be changed means we don't need to flood Neo4j with requests to update objects that don't require changing, or create relationships that already exist. 
We can minimise the amount of data we send across the wire as a result, which results in a faster network interaction, and fewer CPU cycles consumed on the server.

=== User-definable Session lifetime
Supporting the smart object-mapping capability is the `Neo4jSession`. 
This object can be declared with different lifetimes, depending on the requirements of your application. 
For web-based applications, you might choose between HTTP Request-scoped lifetime or HTTP Session-scoped lifetimes.
For a standalone application, you may choose to maintain a single session for the entire lifetime of the application.

The advantage of longer-running sessions is that you will be able to make more efficient requests to the database at the expense of the additional memory associated with the session. 
The advantage of shorter sessions is they impose almost no overhead on memory, but will result in less efficient requests to Neo4j when storing and retrieving data.

It is also possible to manage your session lifetimes in code. For example, associated with single _fetch-update-save_ cycle or unit of work.

