= Spring Data Neo4j⚡️RX
Michael Simons <michael.simons@neo4j.com>
Gerrit Meier <gerrit.meier@neo4j.com>
:toc:
ifndef::manualIncludeDir[]
:manualIncludeDir: ../
endif::[]
:lang: en
:listing-caption: Listing
:source-highlighter: coderay
:icons: font
:sectlink: true
:sectanchors: true
:numbered: true
:xrefstyle: short
:gh_base: https://github.com/neo4j/sdn-rx

include::{manualIncludeDir}/README.adoc[tags=versions]

== Intro

WARNING: Please download the public milestone release of Neo4j 4.0 to use the reactive features of SDN/RX.
         You'll find it in the https://neo4j.com/download-center/#enterprise[Download Center] under "Pre-Releases" as _Neo4j 4.0.0-alpha09mr02_.
         Reactive functionality is used by `org.neo4j.springframework.data.core.ReactiveNeo4jClient` and `org.neo4j.springframework.data.repository.ReactiveNeo4jRepository``
         You can of course use SDN/RX against Neo4j 3.5 but only with `org.neo4j.springframework.data.core.Neo4jClient` and the imperative repositories
         (`org.neo4j.springframework.data.repository.Neo4jRepository`, `org.springframework.data.repository.CrudRepository` and related).

=== What's in the box?

Spring Data Neo4j⚡️RX or in short "SDN/RX" is a next-generation https://spring.io/projects/spring-data[Spring Data] module,
created and maintained by https://neo4j.com[Neo4j, Inc.] in close collaboration with https://pivotal.io[Pivotals] Spring Data Team.

SDN/RX relies completely on the https://github.com/neo4j/neo4j-java-driver[Neo4j Java Driver],
without introducing another "driver" or "transport" layer between the mapping framework and the driver.
The Neo4j Java Driver - sometimes dubbed Bolt or the Bolt driver - is used as a protocol much like JDBC is with relational databases.

Noteworthy features that differentiate SDN/RX from Spring Data Neo4j + OGM are

* Full support for immutable entities and thus full support for Kotlin's data classes right from the start
* Full support for the reactive programming model in the Spring Framework itself and Spring Data
* Brand new Neo4j client and reactive client feature, resurrecting the idea of a template over the plain driver, easing database access

SDN/RX is currently developed with https://github.com/spring-projects/spring-data-neo4j[Spring Data Neo4j] in parallel and will replace it eventually when they are on feature parity in regards of repository support and mapping.

=== Why should I use SDN/RX in favor of SDN+OGM

SDN/RX has several features not present in SDN+OGM, notably

* Full support for Springs reactive story, including reactive transaction
* Full support for https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example[Query By Example]
* Full support for fully immutable entities
* Support for all modifiers and variations of derived finder methods, including spatial queries

=== Do I need both SDN/RX and Spring Data Neo4j?

No.

They are mutually exclusive and you cannot mix them in one project.

=== How does SDN/RX relate to Neo4j-OGM?

https://neo4j.com/docs/ogm-manual/current/[Neo4j-OGM] is an Object Graph Mapping library, which is mainly used by Spring Data Neo4j as it's backend for the heavy lifting of mapping Nodes and Relationships into domain object.
SDN/RX *does not need* and *does not support* Neo4j-OGM.
SDN/RX uses Spring Data's mapping context exclusively for scanning classes and building the meta model.

While this pins SDN-Rx to the Spring eco systems, it has several advantages, among them the smaller footprint in regards of CPU and memory usage and especially, all the features of Springs mapping context.

=== Does SDN/RX support connections over HTTP to Neo4j?

No.

=== Does SDN/RX support embedded Neo4j?

Embedded Neo4j has multiple facets to it:

==== Does SDN/RX provide an embedded instance for your application?

No.

==== Does SDN/RX interact directly with an embedded instance?

No.
An embedded database is usually represented by an instance of `org.neo4j.graphdb.GraphDatabaseService` and has no Bolt connector out of the box.

SDN/RX can however work very much with Neo4j's test harness, the test harness is specially meant to be a drop-in replacement for the real database.

==== What about a Neo4j template class?

Please see <<neo4j-client,Neo4j client>>.

== Getting started

We provide a Spring Boot starter for SDN/RX.
As with any other Spring Boot starter, the only thing you have to do is to include the starter module via your dependency management.
If you don't configure anything, than the starter assumes `bolt://localhost:7687` as Neo4j URI and a server that has disabled authentication.
As the SDN/RX starter depends on the starter for the Java Driver, all things regarding configuration said there, apply here as well.
For reference, look the https://github.com/neo4j/neo4j-java-driver-spring-boot-starter/blob/master/docs/manual.adoc[dedicated manual], too.

SDN/RX supports

* The well known and understood imperative aka blocking programming model (much like Spring Data JDBC or JPA)
* Reactive programming based on http://www.reactive-streams.org[Reactive Streams], including full support for https://spring.io/blog/2019/05/16/reactive-transactions-with-spring[reactive transactions].

Those are all included in the same binary.
The reactive programming model requires a 4.0 Neo4j server on the database side and reactive Spring on the other hand.
Have a look at the {gh_base}/tree/master/examples[examples directory] for all examples.

=== Preparing the database

For this example, we stay within the https://neo4j.com/developer/movie-database/[movie graph],
as it comes for free with every Neo4j instance.

If you don't have a running database but Docker installed, please run:

[source,console,subs="verbatim,attributes"]
[[start-docker-neo4j]]
.Start a local Neo4j instance inside Docker.
----
docker run --publish=7474:7474 --publish=7687:7687 neo4j:{neo4j_version}
----

You know can access http://localhost:7474/browser/?cmd=play&arg=movies[http://localhost:7474].
At first visit, you have to change your password. We chose `secret`  in the examples.
Note the command ready to run in the prompt.
Execute it to fill your database with some test data.

=== Create a new Spring Boot project

The easiest way to setup a Spring Boot project is https://start.spring.io[start.spring.io]
 (which is integrated in the major IDEs as well, in case you don't want to use the website).

Select the "Spring Web Starter" to get all the dependencies needed for creating a Spring based web application.
The Spring Initializr will take care of creating a valid project structure for you,
with all the files and settings in place for the selected build tool.

WARNING: Don't choose Spring Data Neo4j here, as it will get you the previous generation of Spring Data Neo4j including OGM and additional abstraction over the driver.

==== Maven

You can issue a _curl_ request against the Spring Initializer to create a basic Maven project:

[source,bash,subs="verbatim,attributes"]
[[generate-maven-project]]
.Create a basic Maven project with the Spring Initializr
----
curl https://start.spring.io/starter.tgz \
  -d dependencies=webflux,actuator \
  -d bootVersion={spring-boot_version} \
  -d baseDir=Neo4jSpringBootExample \
  -d name=Neo4j%20SpringBoot%20Example | tar -xzvf -
----

This will create a new folder `Neo4jSpringBootExample`.
As this starter is not yet on the initializer, you'll have to add the following dependency manually to your  `pom.xml`:

[source,xml,subs="verbatim,attributes"]
[[dependencies-maven]]
.Inclusion of the spring-data-neo4j-rx-spring-boot-starter in a Maven project
----
<dependency>
	<groupId>{groupId}</groupId>
	<artifactId>{artifactIdStarter}</artifactId>
	<version>{spring-data-neo4j-rx_version}</version>
</dependency>
----

You would also add the dependency manually in case of an existing project.

==== Gradle

The idea is the same, just generate a Gradle project:

[source,bash,subs="verbatim,attributes"]
[[generate-gradle-project]]
.Create a basic Gradle project with the Spring Initializr
----
curl https://start.spring.io/starter.tgz \
  -d dependencies=webflux,actuator \
  -d type=gradle-project \
  -d bootVersion={spring-boot_version} \
  -d baseDir=Neo4jSpringBootExampleGradle \
  -d name=Neo4j%20SpringBoot%20Example | tar -xzvf -
----

The dependency for Gradle looks like this and must be added to `build.gradle`:

[source,groovy,subs="verbatim,attributes"]
.Inclusion of the spring-data-neo4j-rx-spring-boot-starter in a Gradle project
----
dependencies {
    compile '{groupId}:{artifactIdStarter}:{spring-data-neo4j-rx_version}'
}
----

You would also add the dependency manually in case of an existing project.

==== Configuration

Now open any of those projects in your favorite IDE.
Find `application.properties` and configure your Neo4j credentials:

[source,properties]
----
org.neo4j.driver.uri=bolt://localhost:7687
org.neo4j.driver.authentication.username=neo4j
org.neo4j.driver.authentication.password=secret
----

This is the bare minimum of what you need to connect to a Neo4j instance.

NOTE: It is not necessary to add any programmatically configuration of the driver when you use this starter.
      SDN/RX repositories will be automatically enabled by this starter.

=== Creating your domain

Our domain layer should accomplish two things:

* Map your Graph to objects
* Provide access to those

==== Example Node-Entity

SDN/RX fully supports unmodifiable entities, for both Java and `data` classes in Kotlin.
Therefor we will focus on immutable entities here, <<movie-entity>> shows a such an entity.

NOTE: SDN/RX supports all data types the Neo4j Java Driver supports,
      see https://neo4j.com/docs/driver-manual/current/cypher-values/#driver-neo4j-type-system[Map Neo4j types to native language types] inside the chapter "The Cypher type system".
      Future versions will support additional converters.

[source,java]
[[movie-entity]]
.MovieEntity.java
----
import org.neo4j.springframework.data.core.schema.GeneratedValue;
import org.neo4j.springframework.data.core.schema.Id;
import org.neo4j.springframework.data.core.schema.Node;
import org.neo4j.springframework.data.core.schema.Property;

import org.springframework.data.annotation.PersistenceConstructor;

@Node("Movie") // <1>
public class MovieEntity {

	@Id @GeneratedValue // <2>
	private Long id;

	private final String title;

	@Property("tagline") // <3>
	private final String description;

	public MovieEntity(String title, String description) { // <4>
		this.id = null;
		this.title = title;
		this.description = description;
	}

	public Long getId() {
		return id;
	}

	public String getTitle() {
		return title;
	}

	public String getDescription() {
		return description;
	}

	public MovieEntity withId(Long id) { // <5>
		if (this.id == id) {
			return this;
		} else {
			MovieEntity newObject = new MovieEntity(this.title, this.description);
			newObject.id = id;
			return newObject;
		}
	}
}
----
<1> `@Node` is used to mark this class as a managed entity. It also is used to configure the Neo4j label. The label defaults to the name of the class, if you're just using plain `@Node`
<2> Each entity has to have an id. The combination of `@Id` and `@GeneratedValue` configures SDN/RX to use Neo4j's internal id.
<3> This shows `@Property` as a way to use a different name for the field than for the Graphs property.
<4> This is the constructor to be used by your application code. It set's the id to null, as the field containing the internal id should never be manipulated.
<5> This is a so-called "wither" for the `id`-attribute. It creates a new entity and set's the field accordingly, without modifying the original entity, thus making it immutable.

As a general remark: Immutable entities using internally, generated ids are a bit contradictory, as SDN/RX needs a way to set the field with the value generated by the database.

The same entity using https://projectlombok.org[Project Lombok] annotations for creating value objects is shown in <<movie-entity-lombok>>

[source,java]
[[movie-entity-lombok]]
.MovieEntity.java
----
import lombok.Value;

import org.neo4j.springframework.data.core.schema.GeneratedValue;
import org.neo4j.springframework.data.core.schema.Id;
import org.neo4j.springframework.data.core.schema.Node;
import org.neo4j.springframework.data.core.schema.Property;

@Node("Movie")
@Value(staticConstructor = "of")
public class MovieEntity {

	@Id @GeneratedValue
	private Long id;

	private String title;

	@Property("tagline")
	private String description;
}
----

And finally, <<movie-entity-kotlin>> shows the corresponding entity as a Kotlin https://kotlinlang.org/docs/reference/data-classes.html[Data Class].

[source,kotlin]
[[movie-entity-kotlin]]
.MovieEntity.kt
----
@Node("Movie")
data class MovieEntity (

    @Id
    @GeneratedValue
    val id: Long? = null,

    val title: String,

    @Property("tagline")
    val description: String
)

----

==== Declaring Spring Data repositories

You basically have two options here:
You can work store agnostic with SDN/RX and make your domain specific extends one of

* `org.springframework.data.repository.Repository`
* `org.springframework.data.repository.CrudRepository`
* `org.springframework.data.repository.reactive.ReactiveCrudRepository`
* `org.springframework.data.repository.reactive.ReactiveSortingRepository`

Chose imperative and reactive accordingly.

WARNING: While technically not prohibited, it is not recommended to mix imperative and reactive database acccess in the same application.
         We won't support scenarios like this.

The other option is to settle on a store specific implementation and gain all the methods we support out of the box.
The advantage of this approach is also it's biggest disadvantage: Once out, all those methods will be part of your API.
Most of the time it's harder to take something away, than add.
Furthermore, using store specifics leaks your store into your domain.
From a performance point of view, there is no penalty.

We like the store agnostic way of doing things and chose the first approach in the example.
A repository fitting to any of the movie entites above looks like this:

[source,java]
[[movie-repository]]
.MovieRepository.java
----
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import org.springframework.data.domain.Example;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;

public interface MovieRepository extends ReactiveCrudRepository<MovieEntity, Long> {

	Mono<MovieEntity> findOneByTitle(String title); // <1>

	Flux<MovieEntity> findAll(Example<MovieEntity> example);
}
----
<1> The declaration of these two methods is purely optional, if not needed, don't add them. We use them in <<find-by-example-example>> and <<movie-controller>>.

This repository can be used in any Spring component like this:


[source,java]
[[movie-controller]]
.MovieController.java
----
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import org.neo4j.springframework.data.examples.spring_boot.domain.MovieEntity;
import org.neo4j.springframework.data.examples.spring_boot.domain.MovieRepository;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/movies")
public class MovieController {

	private final MovieRepository movieRepository;

	public MovieController(MovieRepository movieRepository) {
		this.movieRepository = movieRepository;
	}

	@PutMapping
	Mono<MovieEntity> createOrUpdateMovie(@RequestBody MovieEntity newMovie) {
		return movieRepository.save(newMovie);
	}

	@GetMapping(value = { "", "/" }, produces = MediaType.TEXT_EVENT_STREAM_VALUE)
	Flux<MovieEntity> getMovies() {
		return movieRepository
			.findAll();
	}

	@GetMapping("/by-title")
	Mono<MovieEntity> byTitle(@RequestParam String title) {
		return movieRepository.findOneByTitle(title);
	}

	@DeleteMapping("/{id}")
	Mono<Void> delete(@PathVariable Long id) {
		return movieRepository.deleteById(id);
	}
}
----

TIP: Testing reactive code is done with a `reactor.test.StepVerifier`. Have a look at the corresponding https://projectreactor.io/docs/core/release/reference/#testing[documentation of Project Reactor].

include::{manualIncludeDir}docs/conversions.adoc[]

include::{manualIncludeDir}docs/neo4j-client.adoc[]

== Q&A

=== Do I need to use Neo4j specific annotations?

No.
You are free to use the following, equivalent Spring Data annotations:

[cols="4*", options="header"]
|===

|SDN/RX Neo4j specific annotation
|Spring Data common annotation
|Purpose
|Difference

|`org.neo4j.springframework.data.core.schema.Id`
|`org.springframework.data.annotation.Id`
|Marks the annotated attribute as the unique id.
|Specific annotation has no additional features.

|`org.neo4j.springframework.data.core.schema.Node`
|`org.springframework.data.annotation.Persistent`
|Marks the class as persistent entity.
|`@Node` allows customizing the labels

|===

=== Howto use assigned ids?

Just `@Id` without `@GeneratedValue` and fill your id attribute via a  constructor parameter or a setter or wither.
See this https://medium.com/neo4j/neo4j-ogm-and-spring-data-neo4j-a55a866df68c[blog post] for some general remarks about finding good ids.

=== Howto use externally generated ids?

We provide the interface `org.neo4j.springframework.data.core.schema.IdGenerator`.
Implement it anyway you want and configure your implementation like this:

[source,java]
.ThingWithGeneratedId.java
----
@Node
public class ThingWithGeneratedId {

	@Id @GeneratedValue(TestSequenceGenerator.class)
	private String theId;
}
----

If you pass in the name of a class to `@GeneratedValue`, this class must have a no-args default constructor.
You can however use a string as well:

[source,java]
.ThingWithIdGeneratedByBean.java
----
@Node
public class ThingWithIdGeneratedByBean {

	@Id @GeneratedValue(generatorRef = "idGeneratingBean")
	private String theId;
}
----

With that, `idGeneratingBean` refers to a bean in the Spring context.
This might be useful for sequence generating.

NOTE: Setters are not required on non-final fields for the id.

=== Howto audit entities?

All Spring Data annotations are supported.
Those are

* `org.springframework.data.annotation.CreatedBy`
* `org.springframework.data.annotation.CreatedDate`
* `org.springframework.data.annotation.LastModifiedBy`
* `org.springframework.data.annotation.LastModifiedDate`

=== Howto use Find by example?

Find by example is a new feature in SDN/RX.
You instantiate an entity or use one already persisted and from it, you create an `org.springframework.data.domain.Example`.
If you repository extends `org.neo4j.springframework.data.repository.Neo4jRepository` or `org.neo4j.springframework.data.repository.ReactiveNeo4jRepository`, you can immedialty use the available `findBy` methods taking in an example, like shown in <<find-by-example-example>>

[source,java]
[[find-by-example-example]]
.findByExample in Action
----
Example<MovieEntity> movieExample = Example.of(new MovieEntity("The Matrix", null));
Flux<MovieEntity> movies = this.movieRepository.findAll(movieExample);

movieExample = Example.of(
	new MovieEntity("Matrix", null),
	ExampleMatcher
	    .matchingAny()
        .withMatcher(
        	"title",
        	ExampleMatcher.GenericPropertyMatcher.of(ExampleMatcher.StringMatcher.CONTAINING)
        )
);
movies = this.movieRepository.findAll(movieExample);
----

=== Can I use SDN/RX without Spring Boot?

Yes, see our `README`.
We provide `org.neo4j.springframework.data.config.AbstractNeo4jConfig` and `org.neo4j.springframework.data.config.AbstractReactiveNeo4jConfig` for that purpose.

== Features to be added

* Versioning support
* Some events
* Custom datatype converters

include::{manualIncludeDir}docs/migrating.adoc[]
