= Benchmarks
:sectanchors:

[abstract]
--
SDN/RX is a new project and aims to replace SDN+OGM eventually.
We want to make sure that SDN/RX is not slower than SDN+OGM, so we created a set of Benchmarks to establish a baseline, which is SDN+OGM.
We also created two versions based on pure Bolt, one imperative and one reactive, to judge the overhead that the mapping framework adds on top when using the Spring Data Repository abstraction.

The benchmarks are not meant to test the read and write performance of the database itself.

Take note that these kind of benchmarks usually don't represent a real world scenario.
In a standard application architecture, your database is usually not on the same machine and queries are more complicated than a simple `MATCH (n {name: $name}) RETURN n` or `SELECT * FROM movies`,
thus having usually much more affect to the execution time.
--

== Prerequisites

All benchmarks require Java 12.
The benchmarks are build with https://openjdk.java.net/projects/code-tools/jmh/[JMH], a Java harness for building, running, and analysing nano/micro/milli/macro benchmarks written in Java and other languages targetting the JVM.
The final Jars support all standard JMH options.

=== SDN/RX

As long as SDN/RX itself is not yet on central, you have to build a snapshot your self.
Please do this on the top level of SDN/RX with

```
./mvnw -DskipTests -Drevision=999 -Dchangelist=-BENCHMARK clean install
```

=== Neo4j

You either need a running database somewhere or a working Docker installation on your machine.

== Run

Each benchmark can be build with

```
mvn clean package
```

and run with

```
java -jar target/benchmark.jar
```

In this case, the benchmarks will fire up a https://www.testcontainers.org[Testcontainer] with Neo4j and the result is probably lower.

To use a locally running instance, start each test like:

```
SDN_RX_NEO4J_URL=bolt://localhost:7687 SDN_RX_NEO4J_PASSWORD=benchmark java -jar target/benchmark.jar
```
